// Additional stops (v4). tier: 1 = top highlight, 2 = highlight (major), 3 = regular.
const STOPS_EXTRA = [
// ---- Peru ----
{id:"nazca",name:"Nazca Lines",cc:"PE",lat:-14.74,lon:-75.13,kind:"ruins",major:true,tags:["ruins","desert","flight"],days:1,dorm:11,
 tag:"2,000-year-old desert drawings, only readable from the air.",best:"Morning flights (less turbulence).",
 blurb:"Two hours south of Huacachina. A 35-minute Cessna flight over the hummingbird, monkey and spider (~$90, morning slots), or the free viewing tower from the Panamericana if you'd rather not fly. Continue on the night bus to Arequipa.",
 hi:["Overflight of the lines (book a morning slot)","Chauchilla mummies","Cantalloc aqueducts"],
 hostels:[{n:"Nasca Trails Hostel",v:"chill",area:"Centre",price:"$",f:["breakfast","tours"],verify:true,t:"Family-run, books the flights."},{n:"Nanasqa Hostel",v:"social",area:"Centre",price:"$",f:["kitchen","garden"],verify:true,t:"Cheap, garden, close to the bus stations."}]},
{id:"tambopata",name:"Tambopata (Puerto Maldonado)",cc:"PE",lat:-12.60,lon:-69.19,kind:"jungle",major:true,tags:["jungle","wildlife","river"],days:3,dorm:12,
 tag:"Cusco's jungle: macaw clay licks, giant otters, cheap lodges.",best:"Sep–Nov drier; macaws most active at the clay licks.",
 blurb:"10-hour bus (or 1-hour flight) from Cusco to Puerto Maldonado, then a boat to a lodge on the Tambopata or Madre de Dios river. Lake Sandoval for otters, the Chuncho clay lick for hundreds of macaws. Easier and cheaper than Iquitos if you're already in Cusco.",
 hi:["Chuncho / Colorado macaw clay lick at dawn","Lake Sandoval giant otters","Night caiman spotting by boat","Canopy tower at sunrise"],
 hostels:[{n:"Tambopata Hostel",v:"social",area:"Puerto Maldonado",price:"$",f:["pool","tours"],verify:true,t:"Town base with pool, arranges lodge trips."},{n:"Explorer's Inn / Wasai Lodge",v:"eco",area:"Tambopata river",price:"$$$",f:["dinner","tours","quiet"],gem:true,verify:true,t:"Classic research lodges deep in the reserve, 2–3 night packages."}]},
// ---- Ecuador ----
{id:"puertolopez",name:"Puerto López & Isla de la Plata",cc:"EC",lat:-1.56,lon:-80.82,kind:"beach",tags:["wildlife","whales","beach"],days:2,dorm:10,
 tag:"Humpback whales Jun–Oct, blue-footed boobies, Los Frailes beach.",best:"Whales until mid-Oct; boobies all year.",
 blurb:"Fishing town 40 min north of Montañita. Isla de la Plata day trip (\"poor man's Galápagos\": boobies, frigatebirds, snorkelling), whale watching in season, and Los Frailes, Ecuador's best beach, in Machalilla park.",
 hi:["Isla de la Plata boat + snorkel","Whale watching (until Oct)","Los Frailes beach","Agua Blanca community and sulphur lagoon"],
 hostels:[{n:"Hostal Maxima",v:"chill",area:"Centre",price:"$",f:["breakfast","garden"],verify:true,t:"Quiet, family-run, books boats."},{n:"Sol Inn Hostel",v:"social",area:"Beach road",price:"$",f:["kitchen","hammocks"],verify:true,t:"Bamboo house, hammocks, social."}]},
{id:"cuyabeno",name:"Cuyabeno reserve",cc:"EC",lat:-0.02,lon:-75.92,kind:"jungle",major:true,tags:["jungle","wildlife","river"],days:4,dorm:60,
 tag:"Flooded Amazon forest, pink dolphins, the cheapest proper jungle trip in Ecuador.",best:"Sep–Nov drier; lagoon may shrink but wildlife concentrates.",
 blurb:"Night bus Quito → Lago Agrio, then 2 h by road and 2 h by canoe to a lodge on the Laguna Grande. 4-day/3-night packages from ~$250 all-in: caiman at night, pink dolphins, piranha fishing, a Siona community visit. Better value than Peru's Iquitos lodges.",
 hi:["Sunset swim in Laguna Grande with dolphins","Night canoe for caimans","Canopy and medicinal-plant walk","Siona community bread-making"],
 hostels:[{n:"Cuyabeno lodges (Siona, Caiman, Jamu, Nicky)",v:"eco",area:"Laguna Grande",price:"$$$",f:["dinner","tours","hammocks"],t:"Book the package in Quito or online; all include transport from Lago Agrio, meals and guide."}]},
// ---- Colombia ----
{id:"sanandres",name:"San Andrés & Providencia",cc:"CO",lat:12.55,lon:-81.72,kind:"island",major:true,tags:["island","beach","diving"],days:4,dorm:16,
 tag:"Caribbean islands 700 km off the coast. Seven-colour sea, reggae, diving.",best:"Dry Jan–Apr; Sep–Nov is hurricane-season rain (rarely hits).",
 blurb:"Cheap flights from Cartagena/Medellín (~$80 each way). San Andrés is busy and duty-free; the 20-minute hop to Providencia is the real thing: quiet, English-speaking, the third-biggest barrier reef in the world. Needs a tourist card (~$30) on entry.",
 hi:["Johnny Cay and the Acuario natural pool","Diving or snorkelling the Providencia reef","Scooter loop of San Andrés","Crab Cay and the Providencia–Santa Catalina bridge"],
 hostels:[{n:"El Viajero San Andrés",v:"social",area:"Town",price:"$$",f:["bar","kitchen","tours"],t:"The backpacker hub of the island."},{n:"Posadas nativas on Providencia",v:"chill",area:"Providencia",price:"$$",f:["beach","quiet"],gem:true,verify:true,t:"Family guesthouses; book ahead, ferries and planes are small."}]},
{id:"villadeleyva",name:"Villa de Leyva",cc:"CO",lat:5.63,lon:-73.53,kind:"culture",tags:["colonial","hiking","day-trip"],days:2,dorm:11,
 tag:"Cobbled colonial town with the biggest plaza in Colombia, fossils, vineyards.",best:"Dry Dec–Feb; cool nights all year.",
 blurb:"3–4 hours from Bogotá, on the way north to San Gil. Whitewashed streets, a giant kronosaurus fossil, the Pozos Azules, hikes to the Paso del Ángel. Weekends fill with Bogotanos.",
 hi:["Plaza Mayor at dusk","El Fósil kronosaurus","Pozos Azules","Ráquira pottery village"],
 hostels:[{n:"Renacer Guesthouse",v:"chill",area:"Edge of town",price:"$",f:["garden","kitchen","view"],gem:true,t:"Colombian Highlands' own hostel: garden, fireplace, hikes from the door."},{n:"Hostal Casa Sofía",v:"social",area:"Centre",price:"$",f:["kitchen"],verify:true,t:"Central, cheap, courtyard."}]},
{id:"jardin",name:"Jardín",cc:"CO",lat:5.60,lon:-75.82,kind:"culture",major:true,tags:["coffee","culture","chill"],days:2,dorm:11,
 tag:"The prettiest pueblo in Antioquia. Painted balconies, cable cars, cock-of-the-rock.",best:"Dry Dec–Feb; Oct–Nov wet but green.",
 blurb:"3.5 hours south of Medellín and worth the detour over Salento if you want the coffee-town feel without the crowds: plaza full of coloured chairs, two wooden cable cars, a cock-of-the-rock reserve five minutes from the square, waterfalls, and the Cueva del Esplendor.",
 hi:["Plaza at 5 pm with a tinto","Cock-of-the-rock reserve at dawn","Garrucha cable car","Cueva del Esplendor hike or horse ride"],
 hostels:[{n:"Kantarrana Hostel",v:"chill",area:"Riverside, 5 min walk",price:"$",f:["garden","kitchen","quiet"],gem:true,t:"Cabins in a garden by the river, quiet, run by locals."},{n:"Hostal Casa Selva y Café",v:"chill",area:"Edge of town",price:"$$",f:["garden","breakfast","view"],verify:true,t:"Coffee-farm feel, balconies over the valley."}]},
{id:"tatacoa",name:"Tatacoa desert",cc:"CO",lat:3.23,lon:-75.17,kind:"desert",tags:["desert","stars","off-beat"],days:2,dorm:10,
 tag:"Red and grey badlands, the clearest night sky in Colombia.",best:"Dry Dec–Feb and Jul–Aug; hot always.",
 blurb:"Between Bogotá and the south (Cali / Popayán / San Agustín). Two canyons to walk at sunrise, an observatory for the stars, pool in the desert. Base in Villavieja.",
 hi:["Cusco (red) desert walk at sunrise","Los Hoyos (grey) desert and pool","Observatory night with the astronomers"],
 hostels:[{n:"Noches de Saturno",v:"chill",area:"In the desert",price:"$",f:["pool","view","quiet"],verify:true,t:"Cabins and hammocks next to the observatory, pool."},{n:"Hostels in Villavieja",v:"chill",area:"Villavieja",price:"$",f:["kitchen"],verify:true,t:"Cheaper, mototaxi into the desert."}]},
{id:"cabodelavela",name:"Cabo de la Vela & Punta Gallinas",cc:"CO",lat:12.20,lon:-72.16,kind:"desert",major:true,tags:["desert","beach","off-beat","kite"],days:3,dorm:9,
 tag:"Desert meets Caribbean at the top of the continent. Hammocks, kite-surf, Wayuu land.",best:"Dry Dec–Apr; Sep–Nov rains are brief.",
 blurb:"Beyond Palomino: 4x4 from Riohacha/Uribia into La Guajira. Cabo de la Vela is a Wayuu fishing village with a kite school and sunset from the Pilón de Azúcar; Punta Gallinas, the northernmost point of South America, is a 2-day tour on from there with dunes that fall into the sea.",
 hi:["Sunset at Pilón de Azúcar and the lighthouse","Kite-surf lesson in flat water","Taroa dunes at Punta Gallinas","Sleep in a chinchorro hammock"],
 hostels:[{n:"Rancherías in Cabo de la Vela",v:"chill",area:"Beach",price:"$",f:["hammocks","beach"],t:"Wayuu family guesthouses: hammock ~$5, cabin ~$15. No hot water, little electricity."},{n:"Hospedaje Luzmila (Punta Gallinas)",v:"chill",area:"Punta Gallinas",price:"$",f:["hammocks","dinner"],verify:true,t:"One of two places to sleep at the tip; comes with the tour."}]},
{id:"nuqui",name:"Nuquí (Pacific coast)",cc:"CO",lat:5.71,lon:-77.27,kind:"jungle",tags:["whales","jungle","beach","off-beat"],days:3,dorm:25,
 tag:"Jungle to the sea, humpback whales, thermal springs, no roads.",best:"Whales Jul–Oct; rains year-round (wettest place in the Americas).",
 blurb:"Fly from Medellín (small plane, ~$150 each way). Black-sand beaches backed by rainforest, whales breaching from the shore in season, the Termales hot springs, surf at El Valle. Expensive and slow, but nothing else on the route feels like this.",
 hi:["Whale watching from a lancha (until Oct)","Termales hot springs in the jungle","Utría national park boat trip","Surf at El Valle / Termales"],
 hostels:[{n:"El Cantil Ecolodge",v:"eco",area:"Termales",price:"$$$",f:["dinner","beach","quiet"],gem:true,t:"Cabins on the beach, all meals, whale boats."},{n:"Guesthouses in Nuquí town",v:"chill",area:"Nuquí",price:"$$",f:["kitchen"],verify:true,t:"Cheaper base; boats to the beaches."}]},
// ---- Guianas ----
{id:"iwokrama",name:"Iwokrama & Atta canopy",cc:"GY",lat:4.67,lon:-58.68,kind:"jungle",major:true,tags:["jungle","wildlife","canopy"],days:2,dorm:40,
 tag:"One million acres of rainforest, a 30 m canopy walkway, jaguar country.",best:"Dry Sep–Mar; the Georgetown–Lethem road is passable.",
 blurb:"On the road between Georgetown and Lethem. Atta Rainforest Lodge sits at the canopy walkway; Iwokrama River Lodge on the Essequibo does Turtle Mountain and night boat trips. Jaguar sightings on the road are real, if lucky.",
 hi:["Canopy walkway at dawn and dusk","Turtle Mountain climb","Night drive for jaguars and tapirs","Essequibo river boat"],
 hostels:[{n:"Atta Rainforest Lodge",v:"eco",area:"Canopy walkway",price:"$$$",f:["dinner","tours","quiet"],gem:true,t:"Eight rooms in the forest, walkway included, ~$150/night full board."},{n:"Iwokrama River Lodge",v:"eco",area:"Essequibo river",price:"$$$",f:["dinner","tours"],t:"Research station with cabins; cheaper hammock option."}]},
{id:"brownsberg",name:"Brownsberg & Brokopondo",cc:"SR",lat:4.95,lon:-55.18,kind:"mountain",tags:["jungle","waterfalls","day-trip"],days:2,dorm:20,
 tag:"Table mountain over a drowned forest lake, waterfalls, howler monkeys.",best:"Dry Aug–Nov.",
 blurb:"Two hours from Paramaribo: a plateau at 500 m in the rainforest with views over the Brokopondo reservoir and its dead-tree forest, waterfall trails, and a STINASU lodge. The easy 1–2 night jungle taste before or instead of the Upper Suriname river.",
 hi:["Mazaroni top viewpoint over Brokopondo","Leo and Irene waterfalls","Howler monkeys at dawn","Boat among the drowned trees"],
 hostels:[{n:"STINASU lodge & hammock camp",v:"eco",area:"Plateau",price:"$$",f:["hammocks","quiet","view"],verify:true,t:"Basic cabins and hammock space; book through STINASU in Paramaribo."}]},
{id:"saintlaurent",name:"Saint-Laurent-du-Maroni",cc:"GF",lat:5.50,lon:-54.03,kind:"culture",tags:["history","river","culture"],days:1,dorm:35,
 tag:"Papillon's prison camp on the Maroni river, Maroon villages by pirogue.",best:"Dry Aug–Nov.",
 blurb:"Where you enter French Guiana from Suriname. The Camp de la Transportation (the penal colony's reception camp) is one of the most affecting sites in South America; pirogue trips upriver to Maroon and Amerindian villages leave from the market. Half a day, then on to Kourou/Cayenne.",
 hi:["Camp de la Transportation guided tour","Pirogue on the Maroni to a Maroon village","Sunday market: Hmong and Creole food"],
 hostels:[{n:"Hôtel La Tentiaire / guesthouses",v:"chill",area:"Centre",price:"$$$",f:["breakfast"],verify:true,t:"No hostels; small hotels from ~€60. Most people do it as a stop en route."}]},
// ---- Bolivia ----
{id:"sucre",name:"Sucre",cc:"BO",lat:-19.03,lon:-65.26,kind:"city",major:true,tags:["colonial","city","food","spanish"],days:3,dorm:9,
 tag:"White colonial capital at 2,800 m. Dinosaur footprints, Sunday Tarabuco market, cheapest Spanish lessons on the continent.",best:"Sunny and mild Sep–Nov.",
 blurb:"Between La Paz/Potosí and Uyuni. The most liveable city in Bolivia: white churches, rooftop cafés, a wall of 5,000 dinosaur footprints, the Tarabuco market (Sundays), the 7 Cascadas hike. Backpackers stay a week for $5/hour Spanish classes.",
 hi:["Cal Orck'o dinosaur wall","Tarabuco Sunday market","Sunset from La Recoleta","Maragua crater trek, 2 days"],
 hostels:[{n:"KulturBerlin Hostel",v:"party",area:"Centre",price:"$",f:["bar","rooftop","kitchen"],t:"Bar, events, the social hub."},{n:"Casa Verde B&B",v:"chill",area:"Centre",price:"$$",f:["pool","breakfast","garden"],gem:true,t:"Small pool, big breakfast, calm courtyard."},{n:"Beehive Hostel",v:"social",area:"Centre",price:"$",f:["kitchen","garden"],verify:true,t:"Garden, hammocks, budget."}]},
{id:"potosi",name:"Potosí",cc:"BO",lat:-19.59,lon:-65.75,kind:"city",tags:["history","mines","altitude"],days:2,dorm:8,
 tag:"4,090 m mining city that financed the Spanish empire. Cooperative mine tour.",best:"Dry Sep–Nov; cold nights.",
 blurb:"Highest city of its size in the world, 3 hours from Sucre and 4 from Uyuni. The Cerro Rico mine tour with working miners is sobering (bring dynamite as a gift, honestly), the Casa de la Moneda is the best museum in Bolivia.",
 hi:["Cerro Rico cooperative mine tour","Casa de la Moneda","Miners' market","Colonial centre at 4,000 m"],
 hostels:[{n:"Koala Den",v:"social",area:"Centre",price:"$",f:["kitchen","tours"],t:"Runs the most respected mine tour."},{n:"Hostal Casona Potosí",v:"chill",area:"Centre",price:"$",f:["breakfast","quiet"],verify:true,t:"Colonial house, warm rooms."}]},
{id:"rurrenabaque",name:"Rurrenabaque (Madidi & pampas)",cc:"BO",lat:-14.44,lon:-67.53,kind:"jungle",major:true,tags:["jungle","wildlife","river"],days:4,dorm:9,
 tag:"Bolivia's Amazon: pampas boat safaris with caimans, monkeys and anacondas, or Madidi jungle lodges.",best:"Dry May–Oct; Nov–Jan wetter, roads muddy but pampas still work.",
 blurb:"Fly from La Paz (40 min, ~$100) or take the infamous 18-hour bus. The 3-day pampas tour (~$200) is the wildlife-densest trip on the continent; Madidi lodges (Chalalán, Madidi Jungle Ecolodge) are the deeper, quieter option.",
 hi:["Pampas: pink dolphins, capybara, squirrel monkeys on your boat","Anaconda hunt in the swamp","Madidi community lodge, 3 nights","Sunset beer at the Mirador"],
 hostels:[{n:"Hostal El Curichal",v:"social",area:"Town",price:"$",f:["pool","hammocks","bar"],t:"Pool and hammocks, the pre-tour meeting point."},{n:"Madidi Jungle Ecolodge",v:"eco",area:"Madidi park",price:"$$$",f:["dinner","tours","quiet"],gem:true,t:"Community-run lodge 3 h upriver; 3-night packages."}]},
{id:"samaipata",name:"Samaipata",cc:"BO",lat:-18.18,lon:-63.87,kind:"mountain",tags:["ruins","chill","hiking","off-beat"],days:3,dorm:9,
 tag:"Hippie village in the hills near Santa Cruz. Pre-Inca El Fuerte, giant ferns, condors.",best:"Dry Apr–Oct; mild all year at 1,650 m.",
 blurb:"Three hours from Santa Cruz, the east-side alternative to the altiplano: El Fuerte carved rock, Amboró park's giant-fern forest, condor viewpoint hikes, wineries, and a laid-back expat-and-artist scene. Good exit point towards Brazil via Santa Cruz.",
 hi:["El Fuerte at sunrise","Giant ferns in Amboró (Codo de los Andes)","Condor viewpoint trek","La Pajcha waterfall"],
 hostels:[{n:"El Jardín Hostel",v:"chill",area:"Edge of village",price:"$",f:["garden","kitchen","hammocks"],gem:true,t:"Garden cabins, hammocks, fire pit."},{n:"Andoriña Hostal",v:"chill",area:"Village",price:"$",f:["garden","breakfast"],verify:true,t:"Dutch-run, calm, good breakfast."}]},
// ---- Brazil ----
{id:"alterdochao",name:"Alter do Chão",cc:"BR",lat:-2.51,lon:-54.95,kind:"beach",major:true,tags:["river","beach","jungle","chill"],days:3,dorm:12,
 tag:"White-sand river beaches on the Tapajós, the 'Caribbean of the Amazon'.",best:"Low water Aug–Dec exposes the beaches; Ilha do Amor is best Sep–Nov.",
 blurb:"Half an hour from Santarém, between Manaus and Belém (boat stops here, or fly). Ilha do Amor beach in the village, canoe trips into the flooded forest, the Tapajós national forest with giant samaúma trees, sunset boats. The easiest, cheapest way to love the Amazon.",
 hi:["Ilha do Amor at sunset","Canoe through the igapó (flooded forest)","Floresta Nacional do Tapajós: giant samaúma trees","Piracaia beach barbecue by boat"],
 hostels:[{n:"Alter Hostel",v:"social",area:"Village",price:"$",f:["kitchen","garden"],verify:true,t:"Central, hammocks, boat tours."},{n:"Pousada Tupaiulândia",v:"chill",area:"Beach",price:"$$",f:["beach","garden","quiet"],gem:true,verify:true,t:"Garden pousada steps from the beach."}]},
{id:"noronha",name:"Fernando de Noronha",cc:"BR",lat:-3.85,lon:-32.42,kind:"island",major:true,tags:["island","diving","beach","splurge"],days:4,dorm:35,
 tag:"Brazil's most beautiful island. Baía do Sancho, dolphins every morning, world-class diving.",best:"Sep–Feb dry, visibility 30–50 m.",
 blurb:"Flights from Recife or Natal (~$250 return), plus a daily environmental tax (~$18/day) and park fee. Expensive for Brazil but Baía do Sancho is regularly voted the best beach on earth, spinner dolphins come into the bay at dawn, and the diving is the best in the country. 3–4 days.",
 hi:["Baía do Sancho via the cliff ladder","Dolphin bay at sunrise","Dive or snorkel Baía dos Porcos","Sunset at Forte do Boldró"],
 hostels:[{n:"Pousadas in Vila do Trinta / Floresta",v:"chill",area:"Island",price:"$$$",f:["breakfast"],verify:true,t:"No real hostels; simplest pousadas ~$60–80. Book weeks ahead."}]},
{id:"trancoso",name:"Trancoso & Arraial d'Ajuda",cc:"BR",lat:-16.59,lon:-39.09,kind:"beach",major:true,tags:["beach","chill","boutique"],days:3,dorm:15,
 tag:"The Quadrado: a grass square of pastel houses on a cliff above empty beaches.",best:"Sep–Feb sunny; Christmas–New Year very busy and pricey.",
 blurb:"South Bahia, between Salvador/Morro and Rio (fly via Porto Seguro). Arraial d'Ajuda is the backpacker village; Trancoso, 40 minutes on, is the fashionable one, still magical at dawn on the Quadrado. Beaches for days: Espelho, Itapororoca, Nativos.",
 hi:["Quadrado at sunrise and at candle-lit night","Praia do Espelho","Beach walk Trancoso → Itapororoca","Caraíva, the car-free village further south"],
 hostels:[{n:"Arraial d'Ajuda Hostel",v:"social",area:"Arraial",price:"$$",f:["pool","bar","kitchen"],verify:true,t:"Pool, social, cheaper base 40 min from Trancoso."},{n:"Pousadas off the Quadrado",v:"boutique",area:"Trancoso",price:"$$$",f:["garden","breakfast","quiet"],gem:true,verify:true,t:"Small pousadas two streets back are half the price of the square."}]},
{id:"ouropreto",name:"Ouro Preto",cc:"BR",lat:-20.39,lon:-43.51,kind:"culture",major:true,tags:["colonial","culture","history"],days:2,dorm:13,
 tag:"Baroque gold-rush town in the hills of Minas. Aleijadinho churches, student repúblicas.",best:"Dry Apr–Sep; Dec–Jan wet but green.",
 blurb:"Two hours from Belo Horizonte (fly or 7 h bus from Rio). Steep cobbled streets, 13 baroque churches, gold-mine tours, and the best food state in Brazil (pão de queijo, feijão tropeiro). Pairs with Mariana and Tiradentes.",
 hi:["São Francisco de Assis church (Aleijadinho)","Mina da Passagem gold mine","Minas food at a per-kilo lunch","Day trip to Mariana by steam train"],
 hostels:[{n:"Goiabada com Queijo Hostel",v:"social",area:"Centre",price:"$",f:["kitchen","view"],verify:true,t:"Old house, views, sociable."},{n:"Pousada Chico Rei",v:"boutique",area:"Centre",price:"$$$",f:["breakfast","quiet"],gem:true,t:"18th-century house, antique rooms, huge breakfast."}]},
{id:"saopaulo",name:"São Paulo",cc:"BR",lat:-23.55,lon:-46.63,kind:"city",major:true,tags:["city","food","nightlife","art"],days:3,dorm:14,
 tag:"20 million people, the best food and nightlife in South America. Skip it and you'll regret it.",best:"Any; Dec–Jan hot with storms.",
 blurb:"Not pretty, but Vila Madalena bars, Beco do Batman street art, the Mercado Municipal, Japanese food in Liberdade, MASP on Paulista, and a nightlife that outlasts Rio's. Hub for flights to Foz, Floripa and the south.",
 hi:["Vila Madalena bar crawl","Beco do Batman + Sunday Paulista","Mercado Municipal mortadella sandwich","Liberdade Japanese district","Copan building and the centre"],
 hostels:[{n:"O de Casa Hostel",v:"social",area:"Vila Madalena",price:"$$",f:["bar","kitchen"],t:"In the nightlife district, bar, social."},{n:"We Hostel Design",v:"boutique",area:"Vila Mariana",price:"$$",f:["garden","kitchen","quiet"],gem:true,t:"Beautiful old house near Ibirapuera park."},{n:"Ô de Casa / Selina Madalena",v:"social",area:"Vila Madalena",price:"$$",f:["cowork","bar"],verify:true,t:"Coworking and bar."}]},
{id:"bonito",name:"Bonito",cc:"BR",lat:-21.13,lon:-56.48,kind:"nature",major:true,tags:["rivers","snorkelling","caves","nature"],days:3,dorm:14,
 tag:"Crystal rivers you float down among fish, blue caves, macaw sinkhole.",best:"Dry May–Oct clearest water; Dec–Jan rain can cloud rivers.",
 blurb:"Eco-tourism model town in Mato Grosso do Sul, 5 hours from Campo Grande. Everything is ticketed and capped: floating the Rio da Prata, Gruta do Lago Azul, the Buraco das Araras macaw sinkhole, Abismo Anhumas rappel. Pairs with the Pantanal.",
 hi:["Float down the Rio da Prata with the dourados","Gruta do Lago Azul","Buraco das Araras at sunrise","Balneário Municipal for free"],
 hostels:[{n:"Papaya Hostel",v:"social",area:"Centre",price:"$$",f:["pool","bar","tours"],verify:true,t:"Pool, tour desk, the backpacker choice."},{n:"Bonito HI Hostel",v:"chill",area:"Centre",price:"$$",f:["pool","kitchen"],verify:true,t:"Hostelling International, pool, calm."}]},
{id:"pantanal",name:"Pantanal",cc:"BR",lat:-19.60,lon:-56.80,kind:"nature",major:true,tags:["wildlife","jaguars","nature"],days:3,dorm:40,
 tag:"The world's largest wetland. Jaguars, caimans by the thousand, hyacinth macaws, giant otters.",best:"Dry Jul–Oct is jaguar season and easiest access; Nov–Jan the rains return and roads flood.",
 blurb:"Better wildlife than the Amazon because there are no trees in the way. South Pantanal from Campo Grande (budget lodges, ~$100/day all-in) or north from Cuiabá (Porto Jofre jaguar boats, pricier). Horse rides, night safaris, piranha fishing, boat trips.",
 hi:["Jaguar boat safari at Porto Jofre (north)","Night spotlight drive: caimans, ocelots, anteaters","Hyacinth macaws at the lodge","Sunrise horse ride through the wetlands"],
 hostels:[{n:"Pantanal Jungle Lodge / Passo do Lontra",v:"eco",area:"South Pantanal (Estrada Parque)",price:"$$$",f:["dinner","tours","hammocks"],t:"Backpacker-priced lodge packages from Campo Grande, 3 days ~$300 all-in."},{n:"Pousada Rio Claro",v:"eco",area:"North Pantanal (Transpantaneira)",price:"$$$",f:["dinner","tours","pool"],verify:true,t:"On the Transpantaneira; jaguar trips to Porto Jofre from here."}]},
{id:"veadeiros",name:"Chapada dos Veadeiros",cc:"BR",lat:-14.13,lon:-47.52,kind:"mountain",major:true,tags:["hiking","waterfalls","nature"],days:3,dorm:13,
 tag:"Quartz-crystal plateau of waterfalls and canyons, Brazil's hippie-hiker highlands.",best:"Dry May–Sep clearest; Nov–Jan rains fill the falls but trails get muddy.",
 blurb:"Four hours north of Brasília. Alto Paraíso is the base, São Jorge the village at the park gate: Santa Bárbara's blue pools, the Saltos do Rio Preto, Vale da Lua moonscape, Cataratas dos Couros. A detour, but the best hiking in central Brazil.",
 hi:["Cachoeira Santa Bárbara (Cavalcante)","Saltos do Rio Preto in the park","Vale da Lua at sunset","Cataratas dos Couros"],
 hostels:[{n:"Hostels in São Jorge",v:"chill",area:"São Jorge",price:"$$",f:["garden","kitchen"],verify:true,t:"Small, dusty, lovely; at the park entrance."},{n:"Alto Paraíso hostels",v:"social",area:"Alto Paraíso",price:"$",f:["kitchen","tours"],verify:true,t:"More choice, tours leave from here."}]},
// ---- Western Amazon ----
{id:"mamiraua",name:"Mamirauá reserve (Tefé)",cc:"BR",lat:-3.35,lon:-64.72,kind:"jungle",major:true,tags:["jungle","wildlife","river"],days:4,dorm:80,
 tag:"Flooded forest, uakari monkeys, the best wildlife lodge in the Brazilian Amazon.",best:"High water Apr–Jul for canoeing under the canopy; Sep–Nov low water, more walking, caimans everywhere.",
 blurb:"Halfway between Leticia and Manaus (boat stops at Tefé; or a 1 h flight from Manaus). The Uakari Floating Lodge inside the reserve runs 3–4 night packages with researchers: red-faced uakaris, sloths, caimans, pink dolphins. The one Amazon stop that beats the Peruvian lodges.",
 hi:["Uakari monkeys at dawn","Night caiman count by canoe","Jaguar tracking in the low-water months","Tefé market and the Solimões riverfront"],
 hostels:[{n:"Uakari Floating Lodge",v:"eco",area:"Inside the reserve",price:"$$$",f:["dinner","tours","quiet"],gem:true,t:"Community-run floating lodge, 3–4 nights all-in (~$900+). Book months ahead."},{n:"Pousadas in Tefé",v:"chill",area:"Tefé",price:"$",f:["breakfast"],verify:true,t:"Simple town pousadas for the night before the lodge boat."}]},
{id:"anavilhanas",name:"Anavilhanas & Presidente Figueiredo",cc:"BR",lat:-2.62,lon:-60.94,kind:"nature",tags:["river","wildlife","waterfalls","day-trip"],days:2,dorm:14,
 tag:"400 river islands with pink dolphins, and a waterfall town two hours from Manaus.",best:"Sep–Nov low water: beaches on the Rio Negro.",
 blurb:"Novo Airão (3 h from Manaus) is the base for the Anavilhanas archipelago: swim with wild pink dolphins, beaches, sunset boats. Presidente Figueiredo, north of Manaus, is a day of caves and waterfalls. Both cheap alternatives to a lodge.",
 hi:["Pink dolphins at Novo Airão","Anavilhanas beaches by boat","Iracema and Santuário waterfalls (Presidente Figueiredo)","Rio Negro sunset"],
 hostels:[{n:"Pousadas in Novo Airão",v:"chill",area:"Novo Airão",price:"$$",f:["breakfast","garden"],verify:true,t:"Small pousadas by the river; the Anavilhanas Jungle Lodge is the splurge."}]},
{id:"pacaya",name:"Pacaya-Samiria (Nauta)",cc:"PE",lat:-4.75,lon:-74.30,kind:"jungle",tags:["jungle","wildlife","river","off-beat"],days:4,dorm:15,
 tag:"Peru's largest reserve, canoe camping instead of a lodge.",best:"Sep–Nov low water: beaches, easier wildlife spotting.",
 blurb:"Two hours from Iquitos by road to Nauta, then days of canoeing through flooded forest with a local guide, sleeping in ranger stations and tents. Cheaper and wilder than the Iquitos lodges; needs 4–6 days.",
 hi:["Canoe through the mirror-black lagoons","Giant river otters and macaws","Camp at a ranger station","Piranha fishing for dinner"],
 hostels:[{n:"Guides and camps via Nauta / Iquitos agencies",v:"eco",area:"Inside the reserve",price:"$$",f:["tours","dinner"],verify:true,t:"~$80–100/day all-in with a licensed guide; book in Iquitos."}]},
{id:"yasuni",name:"Yasuní (Coca)",cc:"EC",lat:-0.85,lon:-76.20,kind:"jungle",major:true,tags:["jungle","wildlife","river"],days:4,dorm:60,
 tag:"The most biodiverse place on earth. Parrot clay licks, canopy towers, Kichwa lodges.",best:"Any; Sep–Nov slightly drier.",
 blurb:"Night bus or flight to Coca, then 2–3 hours down the Napo by motor canoe. Napo Wildlife Center is the famous one ($$$); Sani Lodge and Shiripuno are the community-run, cheaper options. Compare with Cuyabeno: Yasuní has more species, Cuyabeno is cheaper.",
 hi:["Parrot and parakeet clay licks at dawn","Canopy tower above the forest","Night walk: tarantulas, frogs, caimans","Kichwa community visit"],
 hostels:[{n:"Sani Lodge",v:"eco",area:"Napo river",price:"$$$",f:["dinner","tours","quiet"],gem:true,t:"Community-owned by the Sani Kichwa, canopy tower, 3–4 night packages."},{n:"Hostels in Coca",v:"chill",area:"Coca",price:"$",f:["kitchen"],verify:true,t:"For the night before the canoe."}]},
{id:"xapuri",name:"Xapuri & Rio Branco (Acre)",cc:"BR",lat:-10.65,lon:-68.50,kind:"culture",tags:["history","off-beat","jungle"],days:2,dorm:12,
 tag:"Chico Mendes' rubber-tapper town and the far west of Brazil.",best:"Dry Jun–Sep; Oct onwards wet.",
 blurb:"Only if you cross between Puerto Maldonado and Brazil by road. Xapuri has Chico Mendes' house and the rubber-tapper reserve; Rio Branco the Palácio and Amazon museums. A history stop, not a nature one.",
 hi:["Chico Mendes house museum","Seringal Cachoeira rubber reserve","Rio Branco riverfront at night"],
 hostels:[{n:"Pousadas in Xapuri",v:"chill",area:"Xapuri",price:"$",f:["breakfast"],verify:true,t:"Simple pousadas; Rio Branco has a few hostels."}]},
];
// Tiering of existing stops. 1 = top highlight (shown biggest, with a star), 2 = highlight.
const TIER1=["machu","cusco","galapagos","huaraz","mancora","cartagena","tayrona","medellin","kaieteur","kourou","lencois","jeri","salvador","rio","uyuni","iguazu","pantanal","noronha","quilotoa","leticia","rurrenabaque","cabodelavela","sanandres"];
