// vibe: party | social | chill | boutique | surf | eco.  price: $ (<12) $$ (12-20) $$$ (>20) per dorm bed / cheapest room.
// f (features): pool bar rooftop cowork surf dinner breakfast kitchen hammocks beach tours quiet garden brewery hottub view
const STOPS = [
// ===================== PERU =====================
{id:"lima",name:"Lima",cc:"PE",lat:-12.05,lon:-77.04,kind:"city",major:true,tags:["food","city","surf","nightlife"],days:2,dorm:13,hood:"miraflores",
 tag:"Arrival city. Ceviche, Barranco nightlife, then leave.",best:"Grey and cool Sep–Nov (garúa), but the food doesn't care.",
 blurb:"Base in Miraflores or Barranco, not the centre. Two days is enough: Barranco bars, the cliff-top malecón, one big ceviche lunch. You'll pass through again on night buses and flights, so don't over-invest now.",
 hi:["Ceviche at a market (Surquillo) or a cevichería lunch","Barranco: Puente de los Suspiros, bars on Sáenz Peña","Paragliding off the Miraflores cliffs","Historic centre + catacombs of San Francisco"],
 hostels:[
  {n:"Kokopelli Hostel Lima",v:"party",area:"Barranco",price:"$$",f:["bar","rooftop","kitchen"],hood:"barranco",t:"Huge bar, pub crawls, the classic first-night hostel."},
  {n:"Pariwana Hostel Lima",v:"social",area:"Miraflores",price:"$$",f:["bar","rooftop","breakfast"],t:"Big, well-run, easy to find a bus-buddy for the north."},
  {n:"Selina Miraflores",v:"boutique",area:"Miraflores",price:"$$",f:["cowork","rooftop","bar"],t:"Coworking, rooftop, quieter crowd. Good if you need to work a day."},
  {n:"1900 Backpackers Hostel",v:"social",area:"Centro",price:"$",f:["kitchen","bar"],gem:true,t:"Belle-époque mansion in the historic centre. Faded grandeur, cheap, close to the old town."},
  {n:"Dragonfly Hostel Miraflores",v:"chill",area:"Miraflores",price:"$$",f:["kitchen","garden","quiet"],t:"Small, calm, great location near Kennedy park."}]},
{id:"mancora",name:"Máncora",cc:"PE",lat:-4.10,lon:-81.05,kind:"beach",major:true,tags:["beach","surf","party"],days:5,dorm:12,
 tag:"Peru's party beach. Warm water, surf, pool hostels.",best:"Sunny year-round; Sep–Nov is quiet season with good surf.",
 blurb:"The only warm-water beach town in Peru worth the 18-hour night bus from Lima (or fly to Talara and taxi an hour). Surf lessons in the morning, pool parties all afternoon. Vichayito and Los Órganos next door are the calm alternatives.",
 hi:["Beginner surf at the main beach, longboards for $5/h","Sunset at Loki's pool bar","Los Órganos: turtles at the pier, Sep–Nov humpback whales","Mud baths and hot springs at Poza de Barro"],
 hostels:[
  {n:"Loki del Mar",v:"party",area:"Beachfront",price:"$$",f:["pool","bar","beach"],t:"On the beach, pool, bar with a schedule. The reason most people come."},
  {n:"Selina Máncora",v:"social",area:"Beachfront",price:"$$",f:["surf","pool","cowork","beach"],t:"Beachfront, surf school, slightly older crowd than Loki."},
  {n:"Kokopelli Máncora",v:"social",area:"Beachfront",price:"$$",f:["pool","bar","beach"],t:"Pool, sunset deck, cheaper than Loki with a similar crowd."},
  {n:"Marcilia Beach Bungalows",v:"chill",area:"Los Órganos (15 min)",price:"$$$",f:["beach","garden","quiet"],gem:true,t:"Bamboo bungalows on an empty beach one town south. Turtles at the pier, no parties."},
  {n:"The Point Máncora",v:"party",area:"South end",price:"$",f:["hammocks","bar","beach"],t:"Budget party option, hammocks, beach volleyball."}]},
{id:"huanchaco",name:"Huanchaco (Trujillo)",cc:"PE",lat:-8.08,lon:-79.12,kind:"beach",tags:["surf","ruins","chill"],days:2,dorm:10,
 tag:"Reed boats, Chan Chan ruins, a sleepy surf stopover.",best:"Any time; water is cold, wetsuit season.",
 blurb:"A natural break between Máncora and Huaraz. Surf town with the caballito de totora reed boats, plus the adobe city of Chan Chan and the Huaca de la Luna 20 minutes away.",
 hi:["Chan Chan, the biggest adobe city in the world","Huaca de la Luna murals","Sunset with the reed boats on the pier","Surf: gentle long left-hander"],
 hostels:[
  {n:"Frogs Chillhouse Hostel",v:"surf",area:"Beach road",price:"$",f:["surf","hammocks","kitchen"],t:"Surf rental, hammocks, cheap. Very laid-back."},
  {n:"Naylamp Hostel",v:"chill",area:"North end",price:"$",f:["garden","quiet","beach"],gem:true,t:"Oceanfront garden, camping, quiet nights, family-run since forever."}]},
{id:"huaraz",name:"Huaraz",cc:"PE",lat:-9.53,lon:-77.53,kind:"mountain",major:true,tags:["trekking","mountains"],days:4,dorm:11,hood:"huarazcentre",
 tag:"Cordillera Blanca. Laguna 69, Santa Cruz trek, 6,000 m peaks.",best:"May–Sep dry; Sep–Oct still fine, showers start in Nov.",
 blurb:"Trekking capital of Peru, 8 hours from Lima. Acclimatise one day, then Laguna 69 (day hike) or the 4-day Santa Cruz trek. Huayhuash (8–10 days) if you're serious.",
 hi:["Laguna 69 day hike (4,600 m, turquoise)","Santa Cruz trek, 4 days, no guide needed","Laguna Parón and Pastoruri glacier","Acclimatise with the Wilcacocha hike"],
 hostels:[
  {n:"Selina Huaraz",v:"social",area:"Centre",price:"$$",f:["bar","tours","cowork"],t:"Trek-organising desk, bar, the biggest crowd in town."},
  {n:"Krusty Hostel",v:"social",area:"Centre",price:"$",f:["kitchen","tours"],t:"Cheap, social kitchen, everyone is planning the same treks."},
  {n:"The Lazy Dog Inn",v:"eco",area:"Cordillera Blanca, 30 min out",price:"$$$",f:["dinner","view","quiet","garden"],gem:true,t:"Canadian-run eco-lodge at 3,600 m with acclimatisation hikes from the door. Worth two nights."},
  {n:"Alpes Huaraz",v:"chill",area:"Centre",price:"$",f:["breakfast","view","quiet"],t:"Family-run, mountain views, quiet nights before early starts."}]},
{id:"chachapoyas",name:"Chachapoyas",cc:"PE",lat:-6.23,lon:-77.87,kind:"ruins",tags:["ruins","off-beat","waterfalls"],days:3,dorm:10,
 tag:"Kuélap fortress and Gocta waterfall, few tourists.",best:"May–Oct dry; cloud forest is misty anyway.",
 blurb:"Cloud-forest ruins older than Machu Picchu (Kuélap) and one of the world's tallest waterfalls (Gocta). A detour from the coast (10 h from Chiclayo). Skip if time is tight.",
 hi:["Kuélap by cable car","Gocta waterfall hike (771 m)","Karajía sarcophagi in the cliffs","Leymebamba mummy museum"],
 hostels:[
  {n:"Chachapoyas Backpackers",v:"chill",area:"Centre",price:"$",f:["kitchen","tours"],t:"Small, helpful with tour bookings."},
  {n:"Gocta Natura Reserve",v:"eco",area:"Cocachimba, near Gocta",price:"$$$",f:["view","quiet","dinner"],gem:true,t:"Cabins facing the waterfall. Splurge for one night."}]},
{id:"paracas",name:"Paracas",cc:"PE",lat:-13.83,lon:-76.25,kind:"beach",tags:["wildlife","desert"],days:1,dorm:12,
 tag:"Ballestas Islands boat trip, desert-meets-ocean reserve.",best:"Year-round; windy afternoons.",
 blurb:"One night is enough: morning boat to the Ballestas (sea lions, penguins), afternoon bike or tour through the red-sand Paracas reserve. On the way south from Lima to Huacachina.",
 hi:["Ballestas Islands boat, 8 am","Bike the reserve: Playa Roja, La Catedral","Sunset pisco on the pier"],
 hostels:[
  {n:"Kokopelli Paracas",v:"party",area:"Beach",price:"$$",f:["pool","bar","beach"],t:"Pool, beach, bar. Everyone from Lima's Kokopelli ends up here."},
  {n:"Atenas Backpacker Hospedaje",v:"chill",area:"Near pier",price:"$",f:["kitchen","quiet"],t:"Quiet, family-run, near the pier."}]},
{id:"huacachina",name:"Huacachina",cc:"PE",lat:-14.09,lon:-75.76,kind:"desert",major:true,tags:["desert","party","dunes"],days:2,dorm:13,
 tag:"Desert oasis. Dune buggies, sandboarding, pool parties.",best:"Year-round; sunset tour is the one.",
 blurb:"Tiny lagoon village in the dunes outside Ica. The sunset buggy-and-sandboard tour is the reason to come; the rest is pool time and pisco tasting. Night bus onwards to Arequipa.",
 hi:["Sunset dune buggy + sandboarding","Pisco bodega tour in Ica","Climb the big dune for sunrise"],
 hostels:[
  {n:"Wild Rover Huacachina",v:"party",area:"Lagoon",price:"$$",f:["pool","bar"],t:"Irish bar, pool, loud. Peak backpacker party spot."},
  {n:"Banana's Adventure Hostel",v:"social",area:"Lagoon",price:"$$",f:["pool","breakfast","tours"],t:"Buggy tour included in the rate, pool, good breakfast."},
  {n:"Desert Nights Ecocamp",v:"chill",area:"Dune edge",price:"$",f:["quiet","view"],gem:true,t:"Tents on the dune edge, stars, calmer crowd."}]},
{id:"arequipa",name:"Arequipa",cc:"PE",lat:-16.41,lon:-71.54,kind:"city",major:true,tags:["city","canyon","food"],days:3,dorm:12,hood:"arequipacentre",
 tag:"White volcanic city, Colca Canyon condors.",best:"Sunny year-round, cold nights.",
 blurb:"The prettiest city in Peru: white sillar stone, a volcano backdrop, excellent food (rocoto relleno, picanterías). Do the 2-day Colca Canyon trek from here, then night bus to Cusco.",
 hi:["Santa Catalina monastery, a city inside the city","Colca Canyon 2-day trek, condors at Cruz del Cóndor","Picantería lunch (La Nueva Palomino)","Sunset from Yanahuara viewpoint"],
 hostels:[
  {n:"Wild Rover Arequipa",v:"party",area:"Centre",price:"$$",f:["pool","bar"],t:"Pool, bar, same formula as Cusco."},
  {n:"Bothy Hostel Arequipa",v:"social",area:"Centre",price:"$$",f:["rooftop","bar","tours"],t:"Rooftop, well organised, great Colca desk."},
  {n:"Casa de Ávila",v:"chill",area:"Centre",price:"$$",f:["garden","breakfast","quiet"],gem:true,t:"Big garden, Spanish classes, cooking nights. Calm and lovely."},
  {n:"Selina Arequipa",v:"boutique",area:"Centre",price:"$$",f:["cowork","bar"],t:"Colonial building, calmer, coworking."}]},
{id:"cusco",name:"Cusco",cc:"PE",lat:-13.52,lon:-71.97,kind:"city",major:true,tags:["ruins","city","party","trekking"],days:5,dorm:12,hood:"cuscoplaza",
 tag:"Inca capital at 3,400 m. Sacred Valley, Rainbow Mountain, nightlife.",best:"Dry season ends in Oct; Nov–Dec afternoon showers, fewer crowds.",
 blurb:"Give it a proper stay: Sacred Valley day trip, Rainbow Mountain, Humantay lake, and the hardest-partying hostel scene on the continent. Book Machu Picchu tickets before you arrive. Salkantay (5 days) is the budget Inca Trail.",
 hi:["Sacred Valley: Pisac, Ollantaytambo, Moray","Rainbow Mountain at 5,000 m","Salkantay trek to Machu Picchu","San Blas cafés and the San Pedro market","Loki / Wild Rover nights"],
 hostels:[
  {n:"Wild Rover Cusco",v:"party",area:"Centre",price:"$$",f:["bar","rooftop","view"],t:"The biggest party hostel in South America. Bar events nightly."},
  {n:"Loki Cusco",v:"party",area:"Above San Blas",price:"$$",f:["bar","view"],t:"Hilltop colonial mansion, pub-style bar, legendary and loud."},
  {n:"Pariwana Cusco",v:"social",area:"Centre",price:"$$",f:["bar","breakfast"],t:"Big courtyard, activities, calmer than Loki/Wild Rover."},
  {n:"Intro Hostel Cusco",v:"social",area:"San Blas",price:"$$",f:["garden","kitchen"],gem:true,hood:"sanblas",t:"Colonial courtyard, garden, social without the chaos. Best of both."},
  {n:"Ecopackers",v:"chill",area:"Centre",price:"$",f:["garden","quiet"],t:"Big garden, calmer, cheap."},
  {n:"Selina Plaza de Armas",v:"boutique",area:"Plaza",price:"$$$",f:["cowork","rooftop"],t:"On the main square, private-room friendly."}]},
{id:"machu",name:"Machu Picchu",cc:"PE",lat:-13.16,lon:-72.54,kind:"ruins",major:true,tags:["ruins","trekking"],days:2,dorm:14,hood:"aguascalientes",
 tag:"The one. Train via Ollantaytambo or a 4–5 day trek in.",best:"Circuit tickets sell out weeks ahead in Sep–Oct.",
 blurb:"Sleep in Aguas Calientes the night before to be on the first bus up. Cheapest route: colectivo to Hidroeléctrica and a 3 h walk along the rails; fastest: train from Ollantaytambo. Buy the entry ticket first, then plan around it.",
 hi:["Circuit 2 for the classic view","Huayna Picchu or Machu Picchu Mountain add-on","Hidroeléctrica walk along the tracks","Hot springs in Aguas Calientes after"],
 hostels:[
  {n:"Supertramp Hostel",v:"social",area:"Aguas Calientes",price:"$$",f:["hammocks","bar"],t:"Hammocks, bar, everyone up at 5 am."},
  {n:"Nativus Hostel",v:"chill",area:"Aguas Calientes",price:"$$",f:["breakfast","quiet"],gem:true,t:"Clean, warm, good breakfast for the early start."}]},
{id:"titicaca",name:"Lake Titicaca",cc:"PE",lat:-15.84,lon:-69.34,kind:"lake",major:true,tags:["lake","culture"],days:2,dorm:10,
 tag:"Highest big lake in the world. Uros islands, Isla del Sol.",best:"Bright and cold; Nov–Dec afternoon storms.",
 blurb:"From Puno: floating Uros islands and a homestay on Amantaní. Or cross to Copacabana (Bolivia) and hike Isla del Sol north to south. Only worth it if you continue to Bolivia or have days to spare.",
 hi:["Amantaní homestay, one night","Isla del Sol north-to-south hike (Bolivia)","Sillustani burial towers"],
 hostels:[
  {n:"Inka's Rest Hostel (Puno)",v:"chill",area:"Puno centre",price:"$",f:["breakfast","quiet"],t:"Simple, warm, the standard Puno backpacker stop."},
  {n:"Hostal Las Olas (Copacabana, BO)",v:"boutique",area:"Copacabana hill",price:"$$$",f:["view","garden","quiet"],gem:true,t:"Quirky lakeside cabins with hammocks and a view. Worth the splurge."}]},
{id:"iquitos",name:"Iquitos (Amazon)",cc:"PE",lat:-3.75,lon:-73.25,kind:"jungle",major:true,tags:["jungle","wildlife","river"],days:4,dorm:11,
 tag:"Largest city unreachable by road. Jungle lodges, pink dolphins.",best:"Sep–Nov low water: beaches, more walking trails.",
 blurb:"Fly from Lima (no roads in). Belén floating market, then a 3-day jungle lodge trip on the Amazon. Cheaper and wilder than the Cusco-side jungle. From here you can also boat down to Leticia and into Brazil.",
 hi:["Belén market by canoe at dawn","3-day lodge: pink dolphins, piranha fishing, night walks","Pilpintuwasi butterfly farm","Slow boat to Leticia / Brazil"],
 hostels:[
  {n:"Green Track Hostel",v:"social",area:"Centre",price:"$",f:["rooftop","bar","tours"],t:"Rooftop bar, organises jungle trips."},
  {n:"Casa Nuestra",v:"chill",area:"Centre",price:"$$",f:["garden","breakfast","quiet"],gem:true,t:"Small B&B-style house, calm, good for pre-lodge nights."}]},
// ===================== ECUADOR =====================
{id:"vilcabamba",name:"Vilcabamba",cc:"EC",lat:-4.26,lon:-79.22,kind:"mountain",tags:["hiking","chill","off-beat"],days:3,dorm:10,
 tag:"Valley of longevity. Slow days, hikes, the best-run lodge in Ecuador.",best:"Spring-like all year.",
 blurb:"First stop if you cross from Máncora via the Piura–Loja bus. A hippie-ish valley village with hikes into Podocarpus park and one legendary hostel on the hill. Easy to stay a week.",
 hi:["Mandango mountain hike","Podocarpus national park","Izhcayluma's pool and yoga deck","Horse rides to the cloud forest"],
 hostels:[
  {n:"Hostería Izhcayluma",v:"chill",area:"Hill above town",price:"$$",f:["pool","view","dinner","garden","hottub"],gem:true,t:"German-run lodge with pool, yoga, trail maps and a Bavarian menu. Backpacker legend for a reason."},
  {n:"Rendez-Vous Hostal",v:"chill",area:"Centre",price:"$",f:["garden","breakfast"],t:"Adobe rooms around a garden, French-run."}]},
{id:"cuenca",name:"Cuenca",cc:"EC",lat:-2.90,lon:-79.00,kind:"city",tags:["city","culture"],days:2,dorm:10,
 tag:"Colonial UNESCO city, Cajas national park.",best:"Cool and rainy; carry a jacket.",
 blurb:"Ecuador's most liveable city: blue cathedral domes, river walks, cheap good food. Cajas páramo hike day trip. Optional between Vilcabamba/Montañita and Baños.",
 hi:["Cajas national park hike","Tomebamba riverside walk","Panama-hat factory tour (they're from here)"],
 hostels:[
  {n:"Selina Cuenca",v:"social",area:"Centre",price:"$$",f:["cowork","bar"],t:"Colonial house, coworking, bar."},
  {n:"Alternative Hostel",v:"chill",area:"Riverside",price:"$",f:["kitchen","garden"],gem:true,t:"Small, artsy, by the river."}]},
{id:"montanita",name:"Montañita",cc:"EC",lat:-1.83,lon:-80.75,kind:"beach",major:true,tags:["beach","surf","party"],days:3,dorm:10,
 tag:"Ecuador's answer to Máncora. Surf, cocktails from carts.",best:"Jun–Oct whales at Puerto López; Dec–Apr sunny season.",
 blurb:"Surf and party village on the Ruta del Spondylus, 8 hours north of Máncora via the Tumbes border. Weekends are wild, weekdays are surf and hammock. Isla de la Plata (\"poor man's Galápagos\") day trip from Puerto López.",
 hi:["Surf at the point (La Punta)","Cocktail alley at night","Isla de la Plata: blue-footed boobies","Los Frailes beach in Machalilla park"],
 hostels:[
  {n:"Iguana Backpacker Hostel",v:"party",area:"Centre",price:"$",f:["bar"],t:"Centre of town, everyone goes out together."},
  {n:"Balsa Surf Camp",v:"surf",area:"La Punta",price:"$$$",f:["surf","garden","quiet"],gem:true,t:"Bamboo cabins by the point break, surf coaching, no party noise."},
  {n:"Casa del Sol",v:"surf",area:"La Punta",price:"$$",f:["surf","breakfast"],t:"Surf camp at the point, yoga, calmer."},
  {n:"Selina Montañita",v:"social",area:"Beachfront",price:"$$",f:["cowork","bar","beach"],t:"Beachfront, mixed crowd, coworking."}]},
{id:"banos",name:"Baños",cc:"EC",lat:-1.40,lon:-78.42,kind:"mountain",major:true,tags:["adventure","waterfalls"],days:3,dorm:9,hood:"banoscentre",
 tag:"Adventure town under a volcano. Swing at the End of the World.",best:"Any time; showers most afternoons.",
 blurb:"The cheapest adrenaline in South America: canyoning, bridge jumps, the waterfall bike route to Pailón del Diablo, the Casa del Árbol swing, thermal baths at night.",
 hi:["Ruta de las Cascadas by bike, Pailón del Diablo","Casa del Árbol swing over the valley","Canyoning for $30","Night thermal baths at La Virgen"],
 hostels:[
  {n:"Community Hostel Baños",v:"social",area:"Centre",price:"$$",f:["dinner","tours","bar"],t:"Family dinners every night, group activities. Best way to meet people."},
  {n:"Erupción Hostel",v:"social",area:"Centre",price:"$",f:["bar","kitchen"],t:"Cheap, central, bar downstairs."},
  {n:"Hostal La Casa Verde",v:"eco",area:"Riverside, 15 min out",price:"$$",f:["garden","quiet","breakfast"],gem:true,t:"Eco-guesthouse by the river, hammocks, silence."}]},
{id:"tena",name:"Tena (Amazon)",cc:"EC",lat:-0.99,lon:-77.81,kind:"jungle",tags:["jungle","rafting","river"],days:3,dorm:10,
 tag:"Ecuador's easy Amazon. Rafting, lodges, cacao.",best:"Rain year-round; rivers highest Mar–Jul.",
 blurb:"Three hours from Baños. Class III rafting on the Jatunyacu, jungle lodges around Misahuallí, Kichwa community visits. The cheapest way to see the Amazon on this trip.",
 hi:["Jatunyacu rafting day","Misahuallí: monkeys on the plaza, river tubing","Cacao farm and chocolate making","Jumandy caves"],
 hostels:[
  {n:"Hostal Pakay",v:"eco",area:"Riverside outskirts",price:"$",f:["garden","hammocks","quiet"],gem:true,verify:true,t:"Cabins in a fruit garden by the river."},
  {n:"Brisa del Río",v:"chill",area:"Centre",price:"$",f:["kitchen"],verify:true,t:"Simple, central, helps book rafting."}]},
{id:"quilotoa",name:"Quilotoa Loop",cc:"EC",lat:-0.86,lon:-78.90,kind:"mountain",major:true,tags:["hiking","mountains","villages"],days:3,dorm:12,
 tag:"Three-day village-to-village hike to a turquoise crater lake.",best:"Jun–Sep driest; Oct–Dec mixed, mornings clear.",
 blurb:"Bus from Latacunga to Sigchos, then walk Isinliví → Chugchilán → Quilotoa over three days, sleeping in family hostels that feed you. The best cheap trek in Ecuador and the hostels are the highlight.",
 hi:["Isinliví to Chugchilán day, canyon and cheese farm","Quilotoa crater rim walk","Llullu Llama's hot tub after day one","Saquisilí Thursday market"],
 hostels:[
  {n:"Llullu Llama (Isinliví)",v:"chill",area:"Isinliví",price:"$$",f:["hottub","dinner","view","garden"],gem:true,t:"Mountain lodge with wood-fired hot tub, three-course dinner and llamas. Everyone's favourite night of the loop."},
  {n:"Hostal Cloud Forest (Chugchilán)",v:"social",area:"Chugchilán",price:"$",f:["dinner","breakfast"],t:"Family-run, dinner and breakfast included, warm."},
  {n:"Hostal Mama Hilda (Chugchilán)",v:"chill",area:"Chugchilán",price:"$$",f:["dinner","garden"],t:"Cosy, fireplace, good food."}]},
{id:"cotopaxi",name:"Cotopaxi",cc:"EC",lat:-0.68,lon:-78.44,kind:"mountain",major:true,tags:["volcano","hiking","horses"],days:2,dorm:20,
 tag:"5,897 m volcano, all-inclusive lodges at its feet.",best:"Clearest mornings Jun–Sep and Dec.",
 blurb:"One or two nights at a lodge inside the park: hike to the refuge at 4,800 m, ride horses across the páramo, hot tub with the volcano in view. Combine with the Quilotoa loop.",
 hi:["Hike to the José Rivas refuge (4,864 m)","Horse riding on the páramo","Laguna Limpiopungo","Mountain bike down from the car park"],
 hostels:[
  {n:"Secret Garden Cotopaxi",v:"social",area:"Park edge",price:"$$$",f:["dinner","hottub","view","tours"],t:"All meals, hot tub, hikes and the volcano out the window. Backpacker classic; book ahead."},
  {n:"Chilcabamba Lodge",v:"boutique",area:"Park edge",price:"$$$",f:["view","dinner","quiet"],gem:true,t:"Quieter, cabins, the same volcano view."}]},
{id:"quito",name:"Quito",cc:"EC",lat:-0.18,lon:-78.47,kind:"city",major:true,tags:["city","volcanoes"],days:3,dorm:10,hood:"quitooldtown",
 tag:"Old-town capital at 2,850 m, Cotopaxi on the doorstep.",best:"Mornings clear, afternoon rain; cool.",
 blurb:"The best-preserved colonial centre on the continent, the TelefériQo up to 4,000 m, and Cotopaxi/Quilotoa day trips. Fly to Colombia from here or take the bus via Ipiales and the Las Lajas church.",
 hi:["Old town: La Compañía, San Francisco, La Ronda at night","TelefériQo + Rucu Pichincha hike","Mitad del Mundo (the real equator line at Intiñan)","La Floresta for food and bars"],
 hostels:[
  {n:"Community Hostel Quito",v:"social",area:"Old town",price:"$$",f:["dinner","tours","rooftop"],t:"Shared dinners, walking tours, the social hub of Quito."},
  {n:"Secret Garden Quito",v:"social",area:"Old town",price:"$$",f:["rooftop","bar","view"],t:"Rooftop bar with volcano views; sister lodge at Cotopaxi."},
  {n:"Masaya Quito",v:"boutique",area:"Old town",price:"$$",f:["garden","breakfast","quiet"],gem:true,t:"Restored historic house, calmer, lovely courtyard."},
  {n:"Selina Quito",v:"social",area:"La Floresta",price:"$$",f:["cowork","bar"],t:"La Floresta, bar, coworking, near the nightlife."}]},
{id:"mindo",name:"Mindo",cc:"EC",lat:-0.05,lon:-78.78,kind:"jungle",tags:["cloud-forest","birds","chill"],days:2,dorm:10,
 tag:"Cloud-forest village. Hummingbirds, chocolate, tubing.",best:"Rainy all year; that's the point.",
 blurb:"Two hours from Quito. Birding at dawn (400+ species), butterfly farm, chocolate tour, tubing down the river, zip lines through the canopy. A green pause between city days.",
 hi:["Hummingbird gardens at dawn","Waterfall sanctuary via the tarabita cable car","Tubing the Río Mindo","Chocolate tour at El Quetzal"],
 hostels:[
  {n:"La Casa de Cecilia",v:"chill",area:"Riverside",price:"$",f:["garden","kitchen","quiet"],gem:true,t:"Wooden cabins over the river, hummingbirds at breakfast, dirt cheap."},
  {n:"Dragonfly Inn",v:"boutique",area:"Centre",price:"$$$",f:["breakfast","view","garden"],t:"Nice rooms with river balconies, good restaurant."}]},
{id:"otavalo",name:"Otavalo",cc:"EC",lat:0.23,lon:-78.26,kind:"culture",tags:["market","culture","lakes"],days:2,dorm:10,
 tag:"Saturday market, crater lakes, indigenous Andes.",best:"Be there Friday night for Saturday's market.",
 blurb:"The biggest indigenous market in the Andes (Saturday), Cuicocha crater lake hike, Peguche waterfall. Last stop before the Colombian border if you go overland.",
 hi:["Saturday market (animal market at dawn)","Cuicocha crater lake loop, 4 h","Peguche waterfall walk","Cotacachi leather town"],
 hostels:[
  {n:"La Luna",v:"chill",area:"Hills, 4 km out",price:"$",f:["view","garden","dinner","quiet"],gem:true,t:"Farmhouse hostel above the valley, fireplace, views. Taxi in and out."},
  {n:"Flying Donkey Hostel",v:"social",area:"Centre",price:"$",f:["kitchen","rooftop"],verify:true,t:"Central, cheap, social kitchen."}]},
{id:"galapagos",name:"Galápagos",cc:"EC",lat:-0.74,lon:-90.32,kind:"island",major:true,tags:["wildlife","island","splurge","diving"],days:6,dorm:25,
 tag:"Big-budget detour. Sea lions, tortoises, snorkelling with turtles.",best:"Sep–Nov cool water, best marine life; Dec warmer.",
 blurb:"Fly from Quito or Guayaquil (~$450 return + $200 park fee). Land-based island hopping (Santa Cruz, Isabela, San Cristóbal) is the backpacker way and still incredible. Budget $100+/day.",
 hi:["Snorkel Los Túneles (Isabela)","Tortuga Bay and the tortoise reserve (Santa Cruz)","Kicker Rock dive/snorkel (San Cristóbal)","Sea lions on every bench"],
 hostels:[
  {n:"Puerto Ayora & Puerto Villamil guesthouses",v:"chill",area:"Santa Cruz / Isabela",price:"$$$",f:["breakfast"],verify:true,t:"No hostel chains; small hostales on Hostelworld, they fill up."}]},
// ===================== COLOMBIA =====================
{id:"cali",name:"Cali",cc:"CO",lat:3.45,lon:-76.53,kind:"city",tags:["salsa","nightlife"],days:2,dorm:10,
 tag:"Salsa capital. Come for the dancing, not the sights.",best:"Hot year-round; Feria de Cali is late Dec.",
 blurb:"Two nights: a salsa class at the hostel, then Tin Tin Deo or La Topa Tolondra. Natural stop if you come overland from Ecuador; skippable if you fly into Bogotá.",
 hi:["Salsa night at La Topa Tolondra","San Antonio hill at sunset","Cristo Rey and the Cerro de las Tres Cruces hike"],
 hostels:[
  {n:"Viajero Cali",v:"social",area:"San Antonio",price:"$$",f:["pool","bar","tours"],t:"Free salsa classes, pool, San Antonio district."},
  {n:"La Sucursal Hostel",v:"chill",area:"San Antonio",price:"$",f:["kitchen","garden"],gem:true,verify:true,t:"Small, local, salsa teachers next door."}]},
{id:"salento",name:"Salento (coffee region)",cc:"CO",lat:4.64,lon:-75.57,kind:"mountain",major:true,tags:["coffee","hiking"],days:3,dorm:11,hood:"salentocentre",
 tag:"Wax palms of Cocora valley, coffee farms, tejo nights.",best:"Dec–Feb driest; Oct–Nov wettest, still green and fine.",
 blurb:"Cocora valley hike (5 h loop), coffee finca tour, tejo (throwing rocks at gunpowder). Filandia and Jardín are the quieter alternatives if Salento feels too touristy.",
 hi:["Cocora valley loop, wax palms","Coffee tour at Finca El Ocaso","Tejo at Los Amigos","Jardín day trip (Antioquia side)"],
 hostels:[
  {n:"Viajero Salento",v:"social",area:"Hill edge",price:"$$",f:["view","bar","tours"],t:"Best view in town, bar, group hikes."},
  {n:"Hostal Tralala",v:"chill",area:"Centre",price:"$$",f:["garden","kitchen","quiet"],gem:true,t:"Dutch-run, small, immaculate, a garden to read in."},
  {n:"La Serrana Eco Farm",v:"eco",area:"15 min walk out",price:"$$",f:["hammocks","view","dinner","garden"],t:"Farm hostel, hammocks over the valley."},
  {n:"Coffee Tree Boutique Hostel",v:"boutique",area:"Edge of town",price:"$$$",f:["breakfast","view","quiet"],t:"Calm, fireplace, big breakfast."}]},
{id:"bogota",name:"Bogotá",cc:"CO",lat:4.71,lon:-74.07,kind:"city",major:true,tags:["city","food","nightlife"],days:3,dorm:11,hood:"candelaria",
 tag:"Gritty, high capital. Monserrate, street art, Andrés Carne de Res.",best:"Cool and drizzly at 2,600 m; bring a layer.",
 blurb:"Most people give it two nights, base in La Candelaria or Chapinero. Graffiti tour, Monserrate at sunset, the Gold Museum, one night at Andrés Carne de Res in Chía. Flight hub for the whole continent.",
 hi:["Bogotá graffiti tour","Monserrate at sunset (cable car)","Gold Museum","Andrés Carne de Res, the maddest restaurant in Colombia","Sunday ciclovía"],
 hostels:[
  {n:"Selina La Candelaria",v:"social",area:"La Candelaria",price:"$$",f:["bar","rooftop","cowork"],t:"Big, central, bar and rooftop."},
  {n:"Masaya Bogotá",v:"social",area:"La Candelaria",price:"$$",f:["tours","garden"],t:"Colonial house, movie room, walking tours."},
  {n:"Explora Hostels",v:"social",area:"La Candelaria",price:"$",f:["kitchen","bar"],gem:true,t:"Friendly, cheap, less corporate than the chains."},
  {n:"Cranky Croc Hostel",v:"social",area:"La Candelaria",price:"$",f:["kitchen","bar"],t:"Long-running classic, friendly staff."}]},
{id:"sangil",name:"San Gil",cc:"CO",lat:6.55,lon:-73.13,kind:"mountain",tags:["adventure","rafting"],days:2,dorm:10,
 tag:"Rafting, paragliding over Chicamocha canyon, Barichara.",best:"Dry Dec–Mar; rivers bigger in Oct–Nov.",
 blurb:"Colombia's adventure town between Bogotá and the coast: class IV rafting, paragliding, caving, and the postcard village of Barichara 40 minutes away. Off the fly-in route, natural if you bus north.",
 hi:["Río Suárez rafting (class IV)","Paragliding over Chicamocha","Barichara and the Camino Real walk to Guane"],
 hostels:[
  {n:"Macondo Hostel",v:"social",area:"Centre",price:"$",f:["hottub","tours","bar"],t:"Books all the adventure, jacuzzi, chilled bar."},
  {n:"Sam's VIP Hostel",v:"social",area:"Main plaza",price:"$",f:["pool","rooftop"],t:"Rooftop pool on the main plaza."}]},
{id:"medellin",name:"Medellín",cc:"CO",lat:6.24,lon:-75.58,kind:"city",major:true,tags:["city","nightlife","digital-nomad"],days:5,dorm:13,hood:"poblado",
 tag:"City of eternal spring. Comuna 13, metrocable, Poblado nightlife.",best:"Spring-like all year.",
 blurb:"The city backpackers get stuck in. Poblado for nightlife, Laureles for a local feel. Comuna 13 graffiti tour, cable car to Parque Arví, Guatapé day trip. Easy to lose a week here.",
 hi:["Comuna 13 tour","Metrocable to Parque Arví","Laureles: La 70 bars, Estadio","Poblado nightlife: Provenza","Guatapé day trip"],
 hostels:[
  {n:"Los Patios Hostel Boutique",v:"social",area:"Poblado (Manila)",price:"$$",f:["rooftop","cowork","bar","pool"],t:"Rooftop bar, coworking, the most polished big hostel in Colombia."},
  {n:"Rango Hostel Boutique",v:"social",area:"Poblado",price:"$$",f:["pool","rooftop","bar"],t:"Pool, rooftop, weekend parties."},
  {n:"The Wandering Paisa",v:"chill",area:"Laureles",price:"$",f:["kitchen","bar"],gem:true,t:"Laureles, language-exchange nights, local vibe, far from the gringo strip."},
  {n:"Black Sheep Hostel",v:"chill",area:"Poblado (Patio Bonito)",price:"$",f:["kitchen","garden"],gem:true,t:"Old-school, quiet street, run by a Kiwi for 20 years. Good sleep."},
  {n:"Masaya Medellín",v:"social",area:"Poblado",price:"$$",f:["dinner","garden"],t:"Calmer social crowd, dinners."},
  {n:"Purple Monkey Hostel",v:"party",area:"Poblado",price:"$$",f:["bar"],t:"No sleep."}]},
{id:"guatape",name:"Guatapé",cc:"CO",lat:6.23,lon:-75.16,kind:"lake",tags:["lake","day-trip"],days:1,dorm:11,
 tag:"El Peñol rock, 740 steps, lake town in colour.",best:"Weekdays; weekends are packed with paisas.",
 blurb:"Classic day trip from Medellín (2 h bus), but a night is better: sunset from El Peñol, a lake boat, the painted zócalos. Lake View Hostel is the reason to stay.",
 hi:["El Peñol 740 steps at sunset","Boat on the reservoir","Zócalo streets, Calle del Recuerdo"],
 hostels:[
  {n:"Lake View Hostel",v:"social",area:"Lakeside",price:"$$",f:["rooftop","view","tours","bar"],t:"Rooftop over the lake, Thai restaurant, group boat trips."},
  {n:"Mi Casa Guatapé",v:"chill",area:"Centre",price:"$",f:["kitchen","quiet"],t:"Family-run, near the plaza."}]},
{id:"cartagena",name:"Cartagena",cc:"CO",lat:10.42,lon:-75.55,kind:"city",major:true,tags:["city","beach","party","colonial"],days:4,dorm:14,hood:"getsemani",
 tag:"Walled Caribbean city. Getsemaní nights, Rosario islands.",best:"Hot always; Dec–Apr driest; Oct–Nov showers.",
 blurb:"Hot, colourful, expensive by Colombian standards. Stay in Getsemaní. Sunset on the walls, Café Havana, a Rosario Islands day trip or a night on Isla Grande. Cheap flights from Medellín.",
 hi:["Sunset on the city walls with a beer","Plaza de la Trinidad, Getsemaní, every night","Rosario Islands boat / Isla Grande overnight","Café Havana salsa","Castillo San Felipe"],
 hostels:[
  {n:"Viajero Cartagena",v:"social",area:"Old town",price:"$$",f:["pool","bar","tours"],t:"Big pool in the old town, events every night."},
  {n:"Media Luna Hostel",v:"party",area:"Getsemaní",price:"$$",f:["pool","bar"],t:"Pool, its Wednesday party is famous."},
  {n:"Casa Zahri Boutique Hostel",v:"boutique",area:"Getsemaní",price:"$$$",f:["pool","garden","breakfast"],gem:true,t:"Small pool in a restored house, quiet at night, still in Getsemaní."},
  {n:"República Hostel Cartagena",v:"social",area:"Old town",price:"$$",f:["pool","bar"],t:"Old-town pool, bar, dorm-heavy."},
  {n:"Mamallena Cartagena",v:"chill",area:"Getsemaní",price:"$",f:["kitchen","tours"],t:"Cheap and relaxed, books the Panama sailing."}]},
{id:"tayrona",name:"Santa Marta & Tayrona",cc:"CO",lat:11.31,lon:-74.00,kind:"beach",major:true,tags:["beach","jungle","hiking"],days:3,dorm:12,hood:"santamarta",
 tag:"Jungle-meets-Caribbean park. Hammocks at Cabo San Juan.",best:"Park closes 3× a year (Feb, Jun, Oct 19–Nov 2 approx.) — check dates.",
 blurb:"Santa Marta is the base (gritty city, great hostels). Tayrona: hike in, sleep in a hammock at Cabo San Juan, hike out. Also the launch point for the 4-day Lost City (Ciudad Perdida) trek.",
 hi:["Tayrona: Cabo San Juan hammock night","Lost City trek, 4 days","Taganga sunset (and diving certs)","Costeño Beach bonfire"],
 hostels:[
  {n:"The Dreamer Hostel Santa Marta",v:"social",area:"Santa Marta",price:"$$",f:["pool","bar"],t:"Pool, bar, the standard pre-Tayrona stop."},
  {n:"Masaya Santa Marta",v:"social",area:"Historic centre",price:"$$",f:["pool","rooftop"],t:"Rooftop pool in the centre."},
  {n:"Drop Bear Hostel",v:"party",area:"Santa Marta",price:"$",f:["pool","bar"],gem:true,t:"Ex-cartel mansion with a huge pool and a tour of the house's history. Loud, fun."},
  {n:"Viajero Tayrona Hostel & Ecohabs",v:"social",area:"Los Naranjos beach",price:"$$",f:["beach","pool","bar"],t:"On the beach next to the park entrance."},
  {n:"Costeño Beach Surf Camp",v:"surf",area:"Costeño beach",price:"$$",f:["beach","surf","hammocks"],t:"Beach camp east of the park, surf and bonfires."}]},
{id:"minca",name:"Minca",cc:"CO",lat:11.14,lon:-74.12,kind:"mountain",tags:["jungle","waterfalls","chill"],days:2,dorm:11,
 tag:"Sierra Nevada village. Waterfalls, coffee, hammock hostels.",best:"Cooler than the coast; rain Oct–Nov.",
 blurb:"45 minutes above Santa Marta: cooler air, Pozo Azul and Marinka waterfalls, cacao and coffee farms. The hilltop hostels with the giant hammocks are the draw.",
 hi:["Casa Elemento's giant hammock","Marinka waterfall","La Victoria coffee farm","Cerro Kennedy sunrise"],
 hostels:[
  {n:"Casa Elemento",v:"party",area:"Mountain, mototaxi up",price:"$$",f:["hammocks","view","bar"],t:"The world's biggest hammock. Loud at night."},
  {n:"Casa Loma Minca",v:"chill",area:"Hill above village",price:"$",f:["view","dinner","hammocks"],gem:true,t:"Hilltop sunsets, yoga, family dinner, 10-minute climb from town."},
  {n:"Mundo Nuevo Eco Lodge",v:"eco",area:"Remote, 4x4",price:"$$",f:["quiet","garden","dinner"],t:"Farm stay, remote, quiet."}]},
{id:"palomino",name:"Palomino",cc:"CO",lat:11.25,lon:-73.57,kind:"beach",tags:["beach","chill","river"],days:2,dorm:12,
 tag:"Tubing down the river into the sea. Slow beach days.",best:"Rough sea; swim in the river mouth.",
 blurb:"The end of the Caribbean coast for most people: tube from the mountains down to the beach, beach bonfires, not much else. Pool hostels on the beach road.",
 hi:["River tubing to the sea","Sunset walk to the river mouth","Kogi village visit with a guide"],
 hostels:[
  {n:"The Dreamer Hostel Palomino",v:"social",area:"Beach",price:"$$",f:["pool","beach","bar"],t:"Pool, palm garden, straight onto the beach."},
  {n:"Tiki Hut Hostel",v:"party",area:"Beach road",price:"$",f:["pool","bar"],t:"Pool parties, cheaper, central."},
  {n:"Sol de Palomino",v:"chill",area:"Beach",price:"$$",f:["beach","garden","quiet"],gem:true,verify:true,t:"Cabins under palms, quiet end of the beach."}]},
{id:"leticia",name:"Leticia (Amazon border)",cc:"CO",lat:-4.21,lon:-69.94,kind:"jungle",major:true,tags:["jungle","river","off-beat"],days:3,dorm:10,
 tag:"Three-country Amazon corner. Boats onward to Manaus.",best:"Low water Sep–Nov: beaches on the river.",
 blurb:"Fly from Bogotá (no roads). Walk across to Tabatinga (Brazil) for the slow boat to Manaus: 3–4 days in a hammock on deck, the cheapest and most memorable way into Brazil. Speedboat does it in ~36 h.",
 hi:["Sunset parrots at Parque Santander","Puerto Nariño and Lake Tarapoto dolphins","Buy a hammock for the boat","Slow boat Tabatinga → Manaus"],
 hostels:[
  {n:"Omshanty Jungle Lodge",v:"eco",area:"Jungle, 10 min out",price:"$",f:["garden","quiet","hammocks"],gem:true,t:"Cabins in the jungle, hammocks, night sounds."},
  {n:"Mahatu Guesthouse",v:"chill",area:"Town",price:"$",f:["garden","hammocks","tours"],t:"Garden, hammocks, helps with boat tickets."}]},
// ===================== GUIANAS =====================
{id:"georgetown",name:"Georgetown",cc:"GY",lat:6.80,lon:-58.16,kind:"city",major:true,tags:["city","culture","rum","off-beat"],days:2,dorm:20,
 tag:"Wooden colonial capital, Stabroek market, rum. Nobody goes; that's the point.",best:"Dry Sep–Nov; wet season peaks May–Jul.",
 blurb:"English-speaking, Caribbean-flavoured, chaotic. Stabroek market, the tallest wooden cathedral in the world, the seawall at sunset. Base for the Kaieteur flight and gateway to Suriname by ferry.",
 hi:["Stabroek market and the seawall at sunset","St George's wooden cathedral","Kaieteur Falls fly-in day trip","El Dorado rum distillery","Shell Beach turtles (Mar–Aug)"],
 hostels:[
  {n:"Rima Guesthouse",v:"chill",area:"Centre (Middle St)",price:"$$",f:["kitchen","quiet"],gem:true,verify:true,t:"The long-running budget guesthouse everyone ends up in. Book by email."},
  {n:"Sleepin International Hotel",v:"chill",area:"Centre",price:"$$$",f:["pool","breakfast"],verify:true,t:"Budget hotel with pool, safe, central."}]},
{id:"kaieteur",name:"Kaieteur Falls",cc:"GY",lat:5.18,lon:-59.48,kind:"nature",major:true,tags:["waterfalls","nature","flight"],days:1,dorm:0,
 tag:"226 m single-drop waterfall in the jungle, five people at the edge, no railings.",best:"Wet season (May–Aug, Dec–Jan) is loudest; dry season still huge.",
 blurb:"A 12-seater plane from Ogle airport, an hour over unbroken forest, then you stand at the lip of a waterfall five times higher than Niagara with nobody else there. ~$200–250 as a day trip; overland (5 days) for the hardcore.",
 hi:["The rim walk: Johnson's View, Boy Scout View","Golden frogs in the giant bromeliads","Cock-of-the-rock birds","Orinduik Falls add-on (swimmable)"],
 hostels:[
  {n:"Day trip from Georgetown",v:"chill",area:"Ogle airport",price:"$$$",f:["tours"],t:"No stay needed. Book with Air Services or Trans Guyana a few days ahead; weather cancels flights."}]},
{id:"rupununi",name:"Rupununi savannah",cc:"GY",lat:3.88,lon:-59.10,kind:"nature",tags:["wildlife","savannah","community","off-beat"],days:3,dorm:30,
 tag:"Giant otters, jaguars, cowboys, Amerindian eco-lodges.",best:"Dry Sep–Mar for roads and wildlife.",
 blurb:"Between Boa Vista (Brazil) and Georgetown: savannah, the Iwokrama forest and community-run lodges. Not cheap, not fast, unforgettable. Bus Boa Vista → Lethem, then the Georgetown minibus overnight.",
 hi:["Surama village and Iwokrama canopy walkway","Giant river otters on the Rupununi river","Karanambu ranch: giant anteaters","Lethem rodeo at Easter"],
 hostels:[
  {n:"Surama Eco-Lodge",v:"eco",area:"Surama village",price:"$$$",f:["dinner","tours","quiet"],gem:true,t:"Community-owned Makushi lodge. Meals, guides, canopy walkway. ~$100/day all-in."},
  {n:"Caiman House (Yupukari)",v:"eco",area:"Yupukari",price:"$$$",f:["dinner","tours"],gem:true,t:"Field station where you tag black caimans at night with researchers."},
  {n:"Rewa Eco-Lodge",v:"eco",area:"Rewa river",price:"$$$",f:["dinner","tours","quiet"],t:"Remote river lodge, arapaima and otters."}]},
{id:"paramaribo",name:"Paramaribo",cc:"SR",lat:5.85,lon:-55.20,kind:"city",major:true,tags:["city","culture","food","off-beat"],days:3,dorm:18,
 tag:"Dutch-Caribbean wooden city. Roti, a mosque next to a synagogue, dolphins at sunset.",best:"Dry Aug–Nov, Feb–Mar.",
 blurb:"UNESCO-listed wooden centre, Dutch spoken, the best food in the Guianas (Javanese, Hindustani, Creole). Cycle the Commewijne plantations, spot dolphins where the rivers meet, then head up the Suriname river to Maroon villages.",
 hi:["Waterkant and Fort Zeelandia at dusk","Blauwgrond Javanese warungs","Commewijne bike + dolphin boat","Brownsberg or Suriname river trip","Sunday bird-song contests on Onafhankelijkheidsplein"],
 hostels:[
  {n:"Zus & Zo Guesthouse",v:"social",area:"Centre",price:"$$",f:["bar","garden","tours"],gem:true,t:"Café-bar-guesthouse and the backpacker meeting point of Paramaribo. Books river trips."},
  {n:"Guesthouse Twenty4",v:"chill",area:"Centre",price:"$$",f:["kitchen","garden","quiet"],t:"Simple wooden house, calm, central."},
  {n:"Un Pied-à-Terre",v:"chill",area:"Centre",price:"$$",f:["kitchen","garden"],verify:true,t:"Budget guesthouse with a garden."}]},
{id:"uppersuriname",name:"Upper Suriname River",cc:"SR",lat:4.35,lon:-55.45,kind:"jungle",tags:["jungle","river","culture"],days:3,dorm:60,
 tag:"Dugout canoes, Maroon villages, rapids, jungle lodges on river islands.",best:"Dry Sep–Nov: beaches on the river, low rapids.",
 blurb:"Bus to Atjoni, then hours upriver by korjaal to Saramaccan Maroon villages whose ancestors escaped the plantations. Lodges are all-inclusive packages (3–4 days, ~$300) sold in Paramaribo.",
 hi:["Korjaal boat through the rapids","Maroon village visit (Pikin Slee museum)","Swimming at the island beaches","Jungle walk with a Saramaccan guide"],
 hostels:[
  {n:"Danpaati River Lodge",v:"eco",area:"River island",price:"$$$",f:["dinner","tours","beach"],t:"Island lodge, all meals, village visits. The standard package."},
  {n:"Awarradam Jungle Lodge",v:"eco",area:"Gran Rio",price:"$$$",f:["dinner","tours","quiet"],gem:true,t:"Further upriver, hammock verandas, fly in or boat."},
  {n:"Knini Paati",v:"eco",area:"River island",price:"$$",f:["dinner","hammocks"],verify:true,t:"Simpler and cheaper island camp."}]},
{id:"cayenne",name:"Cayenne & Îles du Salut",cc:"GF",lat:4.94,lon:-52.33,kind:"city",major:true,tags:["city","islands","history","euro"],days:2,dorm:35,
 tag:"France in the jungle. Devil's Island, Creole market, euro prices.",best:"Dry Aug–Nov; Feb–Mar carnival.",
 blurb:"You're in the EU: euros, baguettes, no visa, and prices to match. Cayenne's market and Place des Palmistes, then the catamaran from Kourou to the Îles du Salut (Papillon's penal colony) with a night on Île Royale if you can.",
 hi:["Îles du Salut day trip or overnight (Île Royale)","Cayenne market: Hmong and Creole food","Fort Cépérou at sunset","Cacao beach turtles (Apr–Jul)"],
 hostels:[
  {n:"Guesthouses / Airbnb in Cayenne",v:"chill",area:"Centre",price:"$$$",f:["kitchen"],verify:true,t:"No hostels. Chambres d'hôtes and Airbnb from ~€50. Budget accordingly."},
  {n:"Auberge des Îles du Salut",v:"boutique",area:"Île Royale",price:"$$$",f:["dinner","view","quiet"],gem:true,t:"Sleep in the old prison officers' quarters on the island. Hammock spaces are cheaper."}]},
{id:"kourou",name:"Kourou space centre",cc:"GF",lat:5.16,lon:-52.65,kind:"space",major:true,tags:["space","science","off-beat"],days:1,dorm:35,
 tag:"Europe's spaceport. Free guided tours of the Ariane and Vega launch pads, rocket launches from the beach.",best:"Check the CNES launch calendar; a launch night is the jackpot.",
 blurb:"The Centre Spatial Guyanais runs free 3-hour bus tours (book weeks ahead by email, ID required, 8+ years). The space museum is next door. If a launch is scheduled, viewing sites open on the coast and the whole town comes out.",
 hi:["CSG guided tour: Ariane 6 and Vega pads","Musée de l'Espace","Launch viewing from Kourou beach or the observation sites","Catamaran to the Îles du Salut leaves from here"],
 hostels:[
  {n:"Guesthouses in Kourou or day trip from Cayenne",v:"chill",area:"Kourou",price:"$$$",f:[],verify:true,t:"No hostels; guesthouses from ~€60, or do it as a day trip (1 h from Cayenne)."}]},
// ===================== BRAZIL =====================
{id:"manaus",name:"Manaus",cc:"BR",lat:-3.12,lon:-60.02,kind:"jungle",major:true,tags:["jungle","river","city"],days:3,dorm:12,
 tag:"Opera house in the jungle. Meeting of the Waters, lodge trips.",best:"Low water Sep–Nov: river beaches, more trails.",
 blurb:"Where the Amazon boat from Leticia lands. Meeting of the Waters, the Teatro Amazonas, then a 3-day jungle lodge. From here: fly to São Luís, bus north to Boa Vista and Guyana, or take the 4-day boat down to Belém.",
 hi:["Meeting of the Waters boat","Teatro Amazonas (cheap concerts)","3-day lodge on the Rio Negro / Juma","Boat to Belém or bus to Boa Vista"],
 hostels:[
  {n:"Hostel Manaus",v:"social",area:"Historic centre",price:"$",f:["tours","kitchen","bar"],t:"Organises jungle tours, the meeting point for boat arrivals."},
  {n:"Local Hostel Manaus",v:"social",area:"Near opera house",price:"$$",f:["bar","kitchen"],t:"Newer, near the opera house, bar."}]},
{id:"boavista",name:"Boa Vista (transit)",cc:"BR",lat:2.82,lon:-60.67,kind:"city",tags:["transit"],days:1,dorm:12,
 tag:"The hub between Manaus and Guyana. One night, then Lethem.",best:"Any.",
 blurb:"Twelve hours north of Manaus by bus. Nothing to see beyond the river promenade, but it's the gateway: 2 hours to the Guyana border at Lethem, or south again to Manaus. Stamp out of Brazil here if you're leaving via Lethem.",
 hi:["Orla Taumanan at sunset","Bus/colectivo to Bonfim → Lethem"],
 hostels:[
  {n:"Hotels near the rodoviária",v:"chill",area:"Centre",price:"$",f:[],verify:true,t:"Few hostels; cheap hotels around the bus station."}]},
{id:"belem",name:"Belém",cc:"BR",lat:-1.46,lon:-48.50,kind:"city",major:true,tags:["city","food","river"],days:2,dorm:12,
 tag:"Amazon river mouth. Ver-o-Peso market, açaí bowls, Círio de Nazaré in October.",best:"Second Sunday of October: Círio, 2 million people. Otherwise any.",
 blurb:"Where the Guianas overland route (Oiapoque → Macapá → boat) re-enters Brazil, and where the Amazon boat from Manaus ends. The Ver-o-Peso market is the best in Brazil; eat tacacá and real açaí. Bus on to São Luís.",
 hi:["Ver-o-Peso market at dawn","Estação das Docas at night","Ilha de Combu açaí and cacao","Mangal das Garças","Círio de Nazaré (11 Oct 2026)"],
 hostels:[
  {n:"Amazônia Hostel Belém",v:"social",area:"Cidade Velha",price:"$",f:["kitchen","bar"],verify:true,t:"Historic house in the old city."},
  {n:"Hostel Ilha Bela",v:"chill",area:"Centre",price:"$",f:["kitchen"],verify:true,t:"Cheap and central."}]},
{id:"saoluis",name:"São Luís",cc:"BR",lat:-2.53,lon:-44.30,kind:"city",major:true,tags:["city","culture","reggae"],days:2,dorm:13,hood:"praiagrande",
 tag:"Portuguese-tiled old town, reggae capital of Brazil.",best:"Dry Jul–Dec.",
 blurb:"Gateway to Lençóis Maranhenses and Alcântara. The UNESCO centre is crumbling and gorgeous; Thursday-to-Saturday reggae nights are a real scene. Fly in from Bogotá (via Fortaleza or São Paulo) or bus from Belém.",
 hi:["Azulejo streets of Praia Grande","Reggae night at Bar do Nelson / Roots","Bumba-meu-boi rehearsals (any time of year)","Boat to Alcântara"],
 hostels:[
  {n:"Solar das Pedras Hostel",v:"chill",area:"Praia Grande (old town)",price:"$",f:["kitchen","garden"],gem:true,t:"Restored colonial house right in the historic centre."},
  {n:"Casa Frankie Hostel",v:"social",area:"Centre",price:"$",f:["kitchen"],verify:true,t:"Small, friendly, near the centre."}]},
{id:"alcantara",name:"Alcântara (space centre)",cc:"BR",lat:-2.41,lon:-44.41,kind:"space",major:true,tags:["space","ruins","day-trip"],days:1,dorm:14,
 tag:"Colonial ghost town next to Brazil's rocket launch base.",best:"Morning boat, tide-dependent; check times the day before.",
 blurb:"Boat from São Luís (1–1.5 h). A ruined 18th-century town with a pillory square and scarlet ibis at dusk, and the Centro de Lançamento de Alcântara behind it. The launch centre is an air-force base: visits are by prior arrangement only and often refused, so treat it as a view-from-outside stop unless you write weeks ahead.",
 hi:["Praça da Matriz ruins and pillory","Scarlet ibis (guarás) at sunset","Centro de Lançamento de Alcântara (from outside; request a visit early)"],
 hostels:[
  {n:"Pousadas in the old town",v:"chill",area:"Praça da Matriz",price:"$$",f:["breakfast","quiet"],verify:true,t:"No hostels; small pousadas, or do it as a day trip from São Luís."}]},
{id:"lencois",name:"Lençóis Maranhenses",cc:"BR",lat:-2.55,lon:-43.05,kind:"desert",major:true,tags:["dunes","lagoons","nature"],days:3,dorm:14,
 tag:"White dune sea with rainwater lagoons. Grandes and Pequenos Lençóis.",best:"Lagoons fullest May–Sep, still good in Oct, shrinking by Nov–Dec. Go early in the trip if it matters.",
 blurb:"Barreirinhas is the tour base for the Grandes Lençóis (Lagoa Azul, Lagoa Bonita by 4x4). Atins, at the river mouth, is the quieter base for sunrise walks straight into the dunes. The Pequenos Lençóis lie east towards Caburé.",
 hi:["Lagoa Bonita at sunset","Atins: walk into the dunes at sunrise","Pequenos Lençóis by boat down the Preguiças river","Kitesurf at Atins"],
 hostels:[
  {n:"Barreirinhas hostels (Hostelworld)",v:"social",area:"Barreirinhas",price:"$$",f:["pool","tours"],verify:true,t:"A handful of small hostels plus many pousadas; book a night ahead in high season."},
  {n:"Atins pousadas",v:"chill",area:"Atins",price:"$$",f:["quiet","beach"],gem:true,verify:true,t:"Sand-street village, kite-surf crowd, no chains. Worth two nights."}]},
{id:"jeri",name:"Jericoacoara",cc:"BR",lat:-2.80,lon:-40.51,kind:"beach",major:true,tags:["beach","kite","party","sunset"],days:4,dorm:16,
 tag:"Sand-street beach village. Sunset dune, capoeira, caipirinhas.",best:"Wind Jul–Jan (kite season), sunny.",
 blurb:"Reached by 4x4 across the beach from Lençóis (the Rota das Emoções, 2 days) or by bus/transfer from Fortaleza (6 h). Kite-surfing, Lagoa do Paraíso hammocks in the water, sunset on the dune every night. Pricier than the rest of the Northeast.",
 hi:["Sunset on the Duna do Pôr do Sol","Lagoa do Paraíso hammocks in the water","Pedra Furada walk","Kite lesson at Preá"],
 hostels:[
  {n:"Jeri hostels near Rua Principal",v:"social",area:"Village",price:"$$",f:["bar","hammocks"],verify:true,t:"Several small social hostels a block from the beach; no big chains. Check Hostelworld a few days ahead."},
  {n:"Pousadas in Preá",v:"chill",area:"Preá (10 km)",price:"$$",f:["beach","quiet"],gem:true,verify:true,t:"Kite beach next door, quieter and cheaper than Jeri itself."}]},
{id:"fortaleza",name:"Fortaleza",cc:"BR",lat:-3.73,lon:-38.52,kind:"city",tags:["city","transit","beach"],days:1,dorm:12,
 tag:"Big beach city, mostly a transport hub.",best:"Any.",
 blurb:"Useful airport and bus station between Jericoacoara and the rest of the coast. One night on Praia de Iracema if you want a big-city Saturday; otherwise straight through.",
 hi:["Praia de Iracema nightlife","Mercado Central for hammocks","Beach Park water park (if you must)"],
 hostels:[
  {n:"Refúgio Hostel Fortaleza",v:"social",area:"Meireles",price:"$",f:["pool","kitchen"],verify:true,t:"Meireles, near the beach, pool."}]},
{id:"pipa",name:"Praia da Pipa",cc:"BR",lat:-6.23,lon:-35.05,kind:"beach",major:true,tags:["beach","surf","dolphins"],days:3,dorm:14,
 tag:"Cliff-backed beaches, dolphins at Baía dos Golfinhos.",best:"Sep–Feb sunny and dry.",
 blurb:"The best all-round beach town in the Northeast: surfable waves, dolphins from the shore, cheap caipirinhas, dune buggies. 1.5 h south of Natal.",
 hi:["Baía dos Golfinhos at low tide","Praia do Amor surf","Chapadão cliffs at sunset","Buggy to Tibau do Sul lagoon"],
 hostels:[
  {n:"Pipa Hostel",v:"social",area:"Centre",price:"$$",f:["pool","bar"],verify:true,t:"Central, pool, bar."},
  {n:"Sugar Cane Hostel",v:"chill",area:"Quiet street",price:"$",f:["pool","garden"],gem:true,verify:true,t:"Garden, pool, calm."}]},
{id:"olinda",name:"Olinda & Recife",cc:"BR",lat:-8.01,lon:-34.86,kind:"city",tags:["city","culture","music"],days:2,dorm:13,
 tag:"Hilltop colonial Olinda, forró and frevo music.",best:"Dry Sep–Feb.",
 blurb:"Olinda is a pastel-coloured hill town of churches and ateliers with a big music scene; Recife next door has the old centre and Boa Viagem beach (sharks, no swimming). Fly or 13-hour bus to Salvador.",
 hi:["Alto da Sé sunset with tapioca","Forró night in Olinda","Recife Antigo Sunday street market","Porto de Galinhas day trip"],
 hostels:[
  {n:"Hostels in Olinda's historic centre",v:"chill",area:"Olinda",price:"$",f:["kitchen","garden"],verify:true,t:"Small hostels and pousadas in the old town; stay in Olinda, not Boa Viagem."},
  {n:"Piratas da Praia (Recife)",v:"social",area:"Boa Viagem",price:"$",f:["kitchen","bar"],verify:true,t:"Boa Viagem, social, cheap."}]},
{id:"salvador",name:"Salvador",cc:"BR",lat:-12.97,lon:-38.51,kind:"city",major:true,tags:["city","music","culture","beach"],days:4,dorm:14,hood:"pelourinho",
 tag:"Afro-Brazilian heart. Pelourinho drums, capoeira, Barra beach.",best:"Dry Sep–Mar; pre-Carnival rehearsals from Dec.",
 blurb:"Tuesday night drums in Pelourinho, Olodum rehearsals, moqueca, the Barra lighthouse sunset. Stay in Pelourinho for the culture or Barra for the beach. December starts the pre-Carnival warm-up.",
 hi:["Tuesday night in Pelourinho","Olodum rehearsal","Farol da Barra sunset","Moqueca at a Bahian table","Elevador Lacerda to the Mercado Modelo"],
 hostels:[
  {n:"Laranjeiras Hostel",v:"social",area:"Pelourinho",price:"$$",f:["bar","kitchen"],t:"Colonial house, the classic."},
  {n:"Hostel Galeria 13",v:"party",area:"Pelourinho",price:"$",f:["pool","bar"],t:"Pool in an old house, loud."},
  {n:"Bahia Prime Hostel",v:"social",area:"Barra",price:"$$",f:["beach","kitchen"],hood:"barra",t:"Near the beach and lighthouse."},
  {n:"Hostel Cobiçado Salvador",v:"chill",area:"Barra",price:"$",f:["kitchen","quiet"],gem:true,verify:true,hood:"barra",t:"Quiet Barra street, two blocks from the beach."}]},
{id:"chapada",name:"Chapada Diamantina",cc:"BR",lat:-12.56,lon:-41.39,kind:"mountain",major:true,tags:["hiking","waterfalls","caves"],days:3,dorm:13,
 tag:"Table mountains, blue caves, Fumaça waterfall.",best:"Dry Apr–Oct; Nov–Dec showers, waterfalls fuller.",
 blurb:"6 hours inland from Salvador to the town of Lençóis (Bahia). Morro do Pai Inácio sunset, Poço Azul cave swim, 3-day Vale do Pati trek. Brazil's best hiking outside the south.",
 hi:["Morro do Pai Inácio sunset","Poço Azul and Poço Encantado cave swims","Vale do Pati 3-day trek","Cachoeira da Fumaça from the top"],
 hostels:[
  {n:"Hostel Chapada",v:"social",area:"Lençóis (BA)",price:"$",f:["garden","tours","kitchen"],verify:true,t:"Organises treks, garden."},
  {n:"Pousada Vila Serrano",v:"boutique",area:"Lençóis (BA)",price:"$$$",f:["garden","breakfast","quiet"],gem:true,t:"Cabins in a garden, hammocks, the nicest sleep in town."}]},
{id:"morro",name:"Morro de São Paulo",cc:"BR",lat:-13.38,lon:-38.91,kind:"island",tags:["island","beach","party"],days:3,dorm:15,
 tag:"Car-free island. Numbered beaches, sunset zipline.",best:"Sep–Mar.",
 blurb:"2.5-hour catamaran from Salvador. Segunda Praia for the party, Quarta Praia for the calm. Boipeba island (further) is the quiet version.",
 hi:["Sunset from the fort + zipline into the sea","Quarta Praia natural pools at low tide","Boipeba day trip","Segunda Praia nights"],
 hostels:[
  {n:"Hostels on Segunda Praia",v:"party",area:"Segunda Praia",price:"$$",f:["beach","bar"],verify:true,t:"Party hostels sit on the second beach; quieter ones up the hill."},
  {n:"Pousadas in Boipeba",v:"chill",area:"Boipeba island",price:"$$",f:["beach","quiet"],gem:true,verify:true,t:"No cars, no parties, empty beaches."}]},
{id:"rio",name:"Rio de Janeiro",cc:"BR",lat:-22.91,lon:-43.17,kind:"city",major:true,tags:["city","beach","party","nye"],days:5,dorm:18,hood:"copacabana",
 tag:"New Year's Eve on Copacabana: 2 million people in white.",best:"Réveillon prices double from ~27 Dec. Book now.",
 blurb:"Locked as the final stop. Arrive a few days early: Christ the Redeemer, Sugarloaf, Pedra do Telégrafo hike, Lapa on a Friday, a Flamengo game at the Maracanã. Wear white, bring a bottle, and stay on the beach until the fireworks.",
 hi:["Réveillon on Copacabana, midnight fireworks","Sugarloaf at sunset","Christ the Redeemer early morning","Lapa Friday night, Pedra do Sal Monday samba","Pedra do Telégrafo hike","Maracanã match"],
 hostels:[
  {n:"Selina Copacabana",v:"social",area:"Copacabana",price:"$$$",f:["bar","cowork","beach"],t:"Two blocks from the fireworks. Books out first."},
  {n:"Discovery Hostel",v:"social",area:"Glória",price:"$$",f:["bar","tours","kitchen"],hood:"lapa",t:"Near Lapa. The best-run social hostel in Rio."},
  {n:"Rio Hostel Santa Teresa",v:"chill",area:"Santa Teresa",price:"$$",f:["pool","view","bar"],gem:true,hood:"santateresa",t:"Pool with a view over the bay in the bohemian hill district. Tram to Lapa."},
  {n:"Books Hostel",v:"party",area:"Lapa",price:"$$",f:["bar"],hood:"lapa",t:"Pre-parties every night."},
  {n:"Mango Tree Hostel Ipanema",v:"chill",area:"Ipanema",price:"$$$",f:["garden","beach","quiet"],hood:"ipanema",t:"Garden, calmer, one block from the beach."},
  {n:"Che Lagarto Ipanema",v:"party",area:"Ipanema",price:"$$$",f:["bar","beach"],hood:"ipanema",t:"Chain party hostel."},
  {n:"CabanaCopa Hostel",v:"social",area:"Copacabana hill",price:"$$",f:["pool","garden"],t:"Pool, jungle garden, up the hill."}]},
{id:"ilhagrande",name:"Ilha Grande",cc:"BR",lat:-23.14,lon:-44.23,kind:"island",major:true,tags:["island","beach","hiking"],days:3,dorm:15,hood:"abraao",
 tag:"Car-free jungle island. Lopes Mendes beach.",best:"Dec is warm and busy; go before Christmas.",
 blurb:"3 hours from Rio (bus + boat). Hike or boat to Lopes Mendes, snorkel the Blue Lagoon, no roads. The before-Rio option for the last days of December.",
 hi:["Lopes Mendes beach (hike or boat)","Lagoa Azul snorkel boat","Pico do Papagaio sunrise hike","Abraão at night"],
 hostels:[
  {n:"Che Lagarto Ilha Grande",v:"party",area:"Abraão beach",price:"$$",f:["beach","bar"],t:"On the beach, bar."},
  {n:"Biergarten Hostel",v:"social",area:"Abraão",price:"$$",f:["brewery","garden","bar"],gem:true,t:"Garden, own brewery, good crowd."}]},
{id:"paraty",name:"Paraty",cc:"BR",lat:-23.22,lon:-44.72,kind:"city",tags:["colonial","beach","boats"],days:2,dorm:14,
 tag:"Cobbled colonial port, schooner trips, cachaça.",best:"Any; high tide floods the old streets on purpose.",
 blurb:"Between Ilha Grande and São Paulo: whitewashed colonial town, boat day around the bay, Trindade beaches. Pairs with Ilha Grande for a Costa Verde week.",
 hi:["Schooner day around the bay","Trindade beaches and natural pool","Cachaça distillery tasting","Old town at high tide"],
 hostels:[
  {n:"Geko Hostel Paraty",v:"social",area:"Pontal beach",price:"$$",f:["beach","bar","tours"],t:"Beach bar, boat trips, social."},
  {n:"Che Lagarto Paraty",v:"party",area:"Centre",price:"$$",f:["bar"],t:"Chain, central."}]},
{id:"floripa",name:"Florianópolis",cc:"BR",lat:-27.60,lon:-48.55,kind:"island",major:true,tags:["beach","surf","party"],days:4,dorm:15,hood:"lagoa",
 tag:"Island of 42 beaches. Surf, Lagoa nightlife. After-NYE option.",best:"Dec–Feb summer.",
 blurb:"If the trip continues into January: surf at Joaquina, Lagoa da Conceição nightlife, Campeche island. Brazilians' favourite summer spot.",
 hi:["Joaquina surf and dunes","Lagoa da Conceição nights","Ilha do Campeche boat","Lagoinha do Leste hike"],
 hostels:[
  {n:"Tucano House Summer Hostel",v:"social",area:"Lagoa",price:"$$",f:["pool","surf","tours"],t:"Pool, surf trips."},
  {n:"Submarino Hostel",v:"party",area:"Lagoa",price:"$$",f:["bar"],t:"Bar, party crowd."}]},
{id:"iguazu",name:"Iguazu Falls",cc:"BR",lat:-25.69,lon:-54.44,kind:"nature",major:true,tags:["waterfalls","nature"],days:2,dorm:13,
 tag:"275 waterfalls on the Brazil–Argentina border.",best:"Any; biggest flow Dec–Feb.",
 blurb:"Fly from Rio (2 h). Brazilian side for the panorama in the morning, Argentine side for the catwalks the next day. Post-NYE detour or a mid-trip flight loop.",
 hi:["Brazilian side panorama","Argentine side: Devil's Throat catwalk","Boat under the falls","Itaipu dam"],
 hostels:[
  {n:"Tetris Container Hostel",v:"social",area:"Foz do Iguaçu",price:"$$",f:["pool","bar"],t:"Shipping-container hostel with pool."},
  {n:"Concept Design Hostel",v:"social",area:"Foz do Iguaçu",price:"$$",f:["pool","bar"],t:"Pool, near the bus station."}]},
// ===================== BOLIVIA =====================
{id:"lapaz",name:"La Paz",cc:"BO",lat:-16.50,lon:-68.15,kind:"city",major:true,tags:["city","adventure"],days:3,dorm:9,
 tag:"3,650 m. Death Road bike, cable cars, cholita wrestling.",best:"Dry May–Oct; Nov–Dec rains start.",
 blurb:"Optional loop from Titicaca. Death Road mountain-bike day, Mi Teleférico over the city, Valle de la Luna. Cheapest country on the route.",
 hi:["Death Road mountain bike","Mi Teleférico full loop","Cholita wrestling (Sunday)","Witches' market"],
 hostels:[
  {n:"Wild Rover La Paz",v:"party",area:"Centre",price:"$",f:["bar"],t:"Irish bar, the party stop of Bolivia."},
  {n:"The Adventure Brew Hostel",v:"social",area:"Near bus station",price:"$",f:["brewery","rooftop","bar"],gem:true,t:"Own microbrewery, rooftop, free beer at check-in."},
  {n:"Loki La Paz",v:"party",area:"Centre",price:"$",f:["bar"],t:"Same formula, big bar."}]},
{id:"uyuni",name:"Salar de Uyuni",cc:"BO",lat:-20.46,lon:-66.83,kind:"desert",major:true,tags:["salt-flat","nature","photos"],days:3,dorm:9,
 tag:"World's largest salt flat. 3-day 4x4 with coloured lagoons.",best:"Dry season = hexagons; Dec–Mar = mirror effect (starts late Dec).",
 blurb:"Night bus from La Paz, then the 3-day jeep tour (salt flat, red and green lagoons, geysers). Adds roughly a week to the trip including La Paz; only if you drop something elsewhere.",
 hi:["Sunrise on the salt flat","Laguna Colorada flamingos","Sol de Mañana geysers at 5,000 m","Train cemetery"],
 hostels:[
  {n:"Piedra Blanca Backpackers Hostel",v:"chill",area:"Uyuni town",price:"$",f:["breakfast","tours"],t:"Warm showers, tour desk."},
  {n:"Salt hotels on tour",v:"chill",area:"On the tour",price:"$",f:["dinner"],t:"Included in the 3-day jeep tour."}]},
];
