// Checklist items. stop: "*" (everyone), "*CC" (country), or a stop id. when: "before" (before departure / weeks ahead) or "there".
const CHECKS=[
 {stop:"*",when:"before",text:"Passport valid 6+ months beyond December; two photocopies + phone photos."},
 {stop:"*",when:"before",text:"Travel insurance that covers 4,000 m+ trekking and motorbike taxis."},
 {stop:"*",when:"before",text:"Yellow fever vaccination certificate (required to enter Guyana, French Guiana and Suriname from Brazil/Colombia; recommended for all Amazon lodges)."},
 {stop:"*",when:"before",text:"Two different bank cards (one Visa, one Mastercard) plus US$300–500 in crisp $50/$100 bills."},
 {stop:"*",when:"before",text:"Hostelworld / Booking accounts set up; offline maps (Maps.me or Google offline) downloaded for the first countries."},
 {stop:"*",when:"before",text:"Book the first two nights in Lima and the Rio New Year's Eve hostel (they sell out months ahead)."},
 {stop:"*",when:"before",text:"Spanish basics app (and a little Portuguese for Brazil)."},
 {stop:"*PE",when:"before",text:"Cruz del Sur / Oltursa night-bus accounts; Peru Hop only if you want the hop-on route."},
 {stop:"machu",when:"before",text:"Machu Picchu entry ticket (circuit 1–3) bought on the official site 3–4 weeks ahead, then PeruRail/Inca Rail or the Hidroeléctrica colectivo."},
 {stop:"cusco",when:"there",text:"Rainbow Mountain / Salkantay booked through the hostel; acclimatise 2 days before."},
 {stop:"huaraz",when:"there",text:"One acclimatisation day before Laguna 69; altitude pills (soroche) from any pharmacy."},
 {stop:"galapagos",when:"before",text:"Flights Quito/Guayaquil → Baltra, $20 transit card at the airport, $200 park fee in cash on arrival."},
 {stop:"*EC",when:"there",text:"Small US dollar bills ($1, $5) for buses and markets; nobody changes a $100."},
 {stop:"*CO",when:"there",text:"Colombian SIM (Claro) at any corner shop; Bancolombia ATMs for the largest withdrawals."},
 {stop:"tayrona",when:"before",text:"Check the park's closure dates (mid Oct–early Nov); book the Lost City trek 1–2 weeks ahead."},
 {stop:"sanandres",when:"before",text:"Tourist card (~$30) bought at the departure gate; Providencia flights/catamaran booked ahead."},
 {stop:"leticia",when:"there",text:"Buy a hammock, rope and a mosquito net in Leticia market for the Manaus boat; Brazilian exit/entry stamps at the Polícia Federal in Tabatinga."},
 {stop:"manaus",when:"there",text:"Exit stamp before the Boa Vista bus if you continue to Guyana."},
 {stop:"*GY",when:"before",text:"Yellow fever certificate in hand; print the Guyana entry form; Trans Guyana / Air Services Kaieteur flight booked a few days ahead."},
 {stop:"*SR",when:"before",text:"Suriname tourist card / e-visa bought online BEFORE arrival (check current rules); euros in cash."},
 {stop:"kourou",when:"before",text:"CSG space-centre tour requested by email weeks ahead (free, ID needed); check the launch calendar."},
 {stop:"*GF",when:"there",text:"Euro cash; Oiapoque exit stamp for Brazil, Brazilian entry stamp at the Polícia Federal in Oiapoque."},
 {stop:"*BR",when:"before",text:"Domestic flights (Azul, Gol, LATAM) booked 3+ weeks ahead; Pix won't work for foreigners, cards do."},
 {stop:"lencois",when:"there",text:"4x4 transfer Barreirinhas → Atins → Jericoacoara (Rota das Emoções) booked a day ahead."},
 {stop:"noronha",when:"before",text:"Environmental tax (~$18/day) pre-paid online; park entry fee; flights from Recife/Natal."},
 {stop:"rio",when:"before",text:"New Year's Eve hostel booked (4–5 night minimum); white clothes for the beach."},
 {stop:"*BO",when:"there",text:"US dollars cash for the parallel rate; Uyuni 3-day jeep tour booked in La Paz or Uyuni; altitude pills."},
 {stop:"uyuni",when:"there",text:"Sunglasses, sunscreen, warm layers (−10 °C nights); tour operator with good reviews (Red Planet, Quechua Connection)."},
 {stop:"*AR",when:"before",text:"Crisp US$100 bills for the blue rate / Western Union; Aerolíneas or Flybondi flights booked ahead."},
 {stop:"torres",when:"before",text:"Refugios / campsites for the W trek booked months ahead (Vertice + Las Torres sites); gear rental in Puerto Natales."},
 {stop:"chalten",when:"there",text:"Check the wind forecast; no permits needed; buy food in El Calafate first (Chaltén is pricey)."},
 {stop:"bariloche",when:"before",text:"Ruta 40 bus to El Chaltén runs Mon/Wed/Fri only (Oct–Apr); book ahead."},
 {stop:"*CL",when:"there",text:"Chilean ATM fees are high (~$8): withdraw big amounts at BancoEstado."},
 {stop:"atacama",when:"there",text:"Tours (Tatio, Valle de la Luna, stars) booked the day before; 2,400 m, hydrate."},
 {stop:"cuyabeno",when:"before",text:"4-day lodge package booked from Quito; rubber boots usually provided, bring a headlamp."},
 {stop:"yasuni",when:"before",text:"Lodge package (Sani, Napo, Shiripuno) booked weeks ahead; flight or night bus to Coca."},
 {stop:"pantanal",when:"before",text:"Lodge package from Campo Grande or Cuiabá booked ahead; Sep–Oct for jaguars."},
 {stop:"mamiraua",when:"before",text:"Uakari Floating Lodge booked months ahead; boat/flight to Tefé."},
];
// Packing rules: derived from the route
const PACK_RULES=[
 {test:s=>s.tags.includes("trekking")||s.tags.includes("hiking")||s.kind==="mountain",items:["Broken-in hiking shoes","Rain shell","Warm layer (fleece/down)","Refillable bottle + purification tabs","Headlamp"]},
 {test:s=>["uyuni","lapaz","titicaca","quilotoa","cotopaxi","cusco","huaraz","potosi"].includes(s.id),items:["Warm hat + gloves","Thermal base layer","Sunscreen SPF50 + sunglasses (altitude)"]},
 {test:s=>s.kind==="beach"||s.kind==="island",items:["Reef-safe sunscreen","Quick-dry towel","Sandals","Dry bag"]},
 {test:s=>s.tags.includes("surf")||s.tags.includes("kite"),items:["Rash guard"]},
 {test:s=>s.kind==="jungle"||s.tags.includes("jungle"),items:["DEET repellent","Long light trousers + sleeves","Mosquito net (Amazon boats)","Hammock (slow boats)"]},
 {test:s=>["leticia","manaus","alterdochao","mamiraua","belem","iquitos"].includes(s.id),items:["Hammock + rope for the river boats"]},
 {test:s=>s.tags.includes("party")||s.tags.includes("nightlife"),items:["One going-out outfit","Earplugs (dorms)"]},
 {test:s=>["torres","chalten","calafate","ushuaia","carretera","bariloche","puertovaras"].includes(s.id),items:["Windproof jacket","Trekking poles (rentable)","Gaiters optional"]},
 {test:s=>s.tags.includes("diving")||s.tags.includes("snorkelling")||["galapagos","noronha","sanandres","providencia"].includes(s.id),items:["Mask + snorkel (rental is poor)"]},
 {test:s=>s.id==="rio",items:["White outfit for Réveillon"]},
];
