// Remote / off-the-beaten-track stops. Same schema as STOPS. Images: img/{id}.jpg, imgt/, imgm/, img2/{id}_1|2.jpg (credits in remote_credits.json)
const STOPS_REMOTE=[
// ===================== COLOMBIA =====================
{id:"puertonarino",name:"Puerto Nariño & Amacayacu",cc:"CO",lat:-3.77,lon:-70.38,kind:"jungle",major:false,tags:["jungle","wildlife","river","indigenous"],days:3,dorm:15,
 tag:"Car-free Amazon village, pink dolphins in Lago Tarapoto, the calm alternative to Leticia's tour mills.",best:"Sep–Nov low water: beaches, easier hikes, fewer mosquitoes; Dec onwards the rivers rise and the forest floods.",
 blurb:"Two hours by fast boat upriver from Leticia (the app stop), Puerto Nariño is a Ticuna-Cocama village with no cars, tidy paths and a river-facing malecón. You canoe into Lago Tarapoto at dawn for pink and grey dolphins, sleep in a maloca-style lodge and walk into Amacayacu's forest with a local guide instead of a 30-person tour boat. It is cheaper, quieter and more indigenous-run than anything on the Leticia side.",
 hi:["Dawn canoe on Lago Tarapoto for botos (pink dolphins) and caimans at night","Climb the mirador tower for the sunset over the Loretoyacu","Guided walk in Amacayacu / San Martín de Amacayacu with a Ticuna guide","Fundación Natütama's community museum on manatees and river life"],
 hostels:[{n:"Hotel Maloka Napü",v:"chill",area:"Village centre",price:"$",f:["breakfast","tours","quiet"],gem:true,t:"Wooden rooms and hammocks under a big maloca roof; the owners set up dolphin trips at local prices.",verify:true},
  {n:"Cabañas Alto del Águila",v:"eco",area:"Riverbank, 10 min by boat",price:"$",f:["quiet","tours","hammocks"],gem:true,t:"Rustic cabins run by a local naturalist, monkeys in the trees and no electricity after 10 pm.",verify:true}]},
{id:"canocristales",name:"Caño Cristales (La Macarena)",cc:"CO",lat:2.18,lon:-73.79,kind:"nature",major:false,tags:["nature","hiking","river","swimming"],days:3,dorm:20,
 tag:"The 'river of five colours': red Macarenia weed on white sandstone, only open a few months a year.",best:"Season runs mid-Jun to late Nov only; Sep–Oct peak colour. Closed Dec–May (dry, no plants) – time it or skip it.",
 blurb:"Fly from Bogotá (the app stop) to the small town of La Macarena with Satena, then every day is a boat + 4x4 + hike into the Sierra de la Macarena with a mandatory local guide. The pools and waterfalls (Los Ocho, Manto de la Virgen, Los Cuarzos) are swimmable with no sunscreen allowed, and the numbers are capped, so it never feels crowded. Book a package including the flight; walk-in is nearly impossible.",
 hi:["Los Ocho pothole pools and the red carpet of Macarenia clavigera","Swim below the Manto de la Virgen waterfall","Sunset on the Guayabero river with local boatmen","Optional day to Caño Cristalitos or the Raudal de Angosturas rock art"],
 hostels:[{n:"Hotel La Fuente",v:"chill",area:"La Macarena town",price:"$$",f:["breakfast","tours","quiet"],gem:false,t:"Simple, clean, family-run and used by most package operators; ask for a fan room on the upper floor.",verify:true},
  {n:"Hotel Punto Verde",v:"chill",area:"La Macarena town",price:"$$",f:["breakfast","garden"],gem:false,t:"Garden rooms a few blocks from the airstrip; basic but reliable during the season.",verify:true}]},
{id:"guaviare",name:"San José del Guaviare",cc:"CO",lat:2.57,lon:-72.64,kind:"nature",major:false,tags:["nature","rock art","hiking","swimming"],days:3,dorm:12,
 tag:"12,000-year-old rock paintings, red-rock 'stone city' and natural pools, in an ex-FARC zone now open and cheap.",best:"Sep–Nov wet but green and the rivers full; Dec–Mar dry, dusty and hot but every track passable.",
 blurb:"An 8–9 hour bus from Bogotá (the app stop) or a Satena flight drops you at the edge of the Amazon, where the Serranía de la Lindosa holds kilometres of ochre rock art (Cerro Azul, Nuevo Tolima) that only opened to visitors after the 2016 peace deal. Days are a mix of 4x4 rides to Ciudad de Piedra's rock labyrinth, swims in Tranquilandia's crystal creek and Playa Güío's flooded forest with dolphins. It is the Caño Cristales experience at a third of the price and without the seasonal lottery.",
 hi:["Cerro Azul rock-art panels (guide required, half-day hike)","Ciudad de Piedra and the Puerta de Orión natural arch","Tranquilandia: swim in a mini Caño Cristales","Kayak among pink dolphins at Playa Güío at sunset"],
 hostels:[{n:"Hotel Casa Mia",v:"chill",area:"Town centre",price:"$",f:["breakfast","quiet"],gem:false,t:"Comfortable town hotel; local agencies pick you up here for the day trips.",verify:true},
  {n:"Playa Güío Ecoturismo",v:"eco",area:"Playa Güío, 15 min from town",price:"$",f:["hammocks","tours","quiet"],gem:true,t:"Community-run cabins and hammocks on the flooded forest lake; sleep where the dolphins are.",verify:true}]},
{id:"mitu",name:"Mitú (Vaupés)",cc:"CO",lat:1.25,lon:-70.23,kind:"jungle",major:false,tags:["jungle","indigenous","river","birding"],days:4,dorm:18,
 tag:"Fly-in only Amazon capital, black-water rivers, maloca stays with Cubeo and Tukano communities. Nobody goes.",best:"Sep–Nov drier with beaches on the Vaupés; Dec–Jan still warm, rain year-round – bring a poncho.",
 blurb:"There are no roads: it's a 1.5 h Satena flight from Bogotá (the app stop). Mitú sits on the Vaupés river surrounded by inselbergs, waterfalls and indigenous communities that host visitors in malocas through local guides (arrange in town or via the Vaupés tourism office). You will be one of a handful of foreigners; days are spent climbing Cerro Guacamaya, bathing in Caño Sangre and travelling by canoe to communities like Mituseño. Better wildlife-per-dollar than Leticia and far more cultural depth.",
 hi:["Climb Cerro Guacamaya for the view over endless forest","Canoe to a maloca community (Mituseño, Puerto Vaupés) for the night","Caño Sangre and Ceima Cachivera rapids for a swim","Birding – Vaupés is one of Colombia's least-explored hotspots"],
 hostels:[{n:"Hotel Real Mitú",v:"chill",area:"Town centre",price:"$",f:["quiet"],gem:false,t:"Basic town hotel near the malecón; expect cold showers and helpful staff who know the community guides.",verify:true}]},
// ===================== PERU =====================
{id:"manu",name:"Manu National Park",cc:"PE",lat:-11.98,lon:-71.45,kind:"jungle",major:false,tags:["jungle","wildlife","river","birding"],days:5,dorm:120,
 tag:"The most biodiverse park on Earth, reached over the Andes from Cusco; giant otters, macaw clay licks, cloud forest.",best:"Sep–Nov end of dry season: clay licks active, roads open; Dec–Jan rains start, still doable but muddier.",
 blurb:"From Cusco (the app stop) a 4x4 climbs past Paucartambo and drops through the cloud forest (cock-of-the-rock leks) to Atalaya, where a boat takes you down the Alto Madre de Dios and up the Manu river. Only licensed operators enter the reserved zone; budget tours (Bonanza, Pantiacolla) do 4–5 days from ~US$500 with camping or simple lodges, the Manu Wildlife Center is the plush end. Compared to Tambopata it is bigger, wilder and you will see giant otters at Cocha Salvador.",
 hi:["Cocha Salvador oxbow lake: giant otters from a catamaran","Macaw and parrot clay lick at dawn (Blanquillo)","Cloud-forest section: Andean cock-of-the-rock lek at sunrise","Night walks and canopy tower at a lodge"],
 hostels:[{n:"Amazonia Lodge",v:"eco",area:"Atalaya, cloud-forest edge",price:"$$$",f:["breakfast","dinner","tours","quiet"],gem:true,t:"Old tea hacienda turned birding lodge at the foot of the Andes; ~600 bird species on the property.",verify:true},
  {n:"Manu Wildlife Center",v:"eco",area:"Madre de Dios river, near Blanquillo",price:"$$$",f:["breakfast","dinner","tours"],gem:false,t:"Comfortable bungalows and the best-run clay-lick access; only as part of a package.",verify:true}]},
{id:"oxapampa",name:"Oxapampa & Pozuzo",cc:"PE",lat:-10.57,lon:-75.40,kind:"mountain",major:false,tags:["mountain","culture","hiking","food"],days:3,dorm:12,
 tag:"Tyrolean chalets, strudel and cloud forest at 1,800 m: an Austro-German colony from 1859, still speaking dialect in Pozuzo.",best:"Sep–Nov mostly dry and cool, ideal for Yanachaga hikes; Dec–Jan rainy season begins, road to Pozuzo can wash out.",
 blurb:"A 10 h night bus from Lima (the app stop) via La Merced leaves you in Oxapampa's wooden-chalet plaza, home of Peru's best coffee and cheese, and gateway to Yanachaga-Chemillén National Park's waterfalls and cloud forest. A rough 3 h road continues to Pozuzo, the original 1859 settlement where the church, the cemetery and the older families are still Tyrolean. It is a cheap, weird and beautiful detour that almost no foreigner takes.",
 hi:["Hike to El Tigre and Río Tigre waterfalls in Yanachaga-Chemillén","Pozuzo: Schafferer museum, colonists' cemetery and a Tyrolean dinner","Coffee farm visit in the Villa Rica valley on the way in","Oxapampa's Selvámonos festival vibe (late June) – or just the plaza at dusk"],
 hostels:[{n:"Hospedaje Bötger",v:"chill",area:"Oxapampa centre",price:"$",f:["breakfast","garden","quiet"],gem:true,t:"Wooden family guesthouse of Austro-German descendants; home-made jam at breakfast.",verify:true},
  {n:"Hospedaje Frau Maria Egg",v:"chill",area:"Pozuzo",price:"$",f:["breakfast","dinner","quiet"],gem:true,t:"The classic Pozuzo stay – Tyrolean-Peruvian family, big dinners, farm out back.",verify:true}]},
// ===================== BRAZIL =====================
{id:"marajo",name:"Ilha de Marajó (Soure)",cc:"BR",lat:-0.72,lon:-48.52,kind:"island",major:false,tags:["island","beach","wildlife","culture"],days:3,dorm:15,
 tag:"A Switzerland-sized river island with more buffalo than people, freshwater beaches and police on buffalo-back.",best:"Sep–Nov dry: beaches wide, roads passable, buffalo everywhere; Dec–Jan rains return and the fields flood.",
 blurb:"From Belém (the app stop) it is a 3 h ferry to Camará then a van to Soure, the island's sleepy capital where water buffalo pull carts and the police ride them. Rent a bike for Praia do Pesqueiro and Barra Velha, visit a buffalo fazenda for cheese and a ride, and eat filé de búfalo with fried fish at a beach barraca. It is one of the strangest, most relaxed places in Brazil and costs nothing.",
 hi:["Buffalo fazenda visit (São Jerônimo or Bom Jesus): ride, cheese, birds","Praia do Pesqueiro at low tide – kilometres of sand and mangroves","Marajoara pottery workshops in Soure and Cachoeira do Arari museum","Sunset at the Soure lighthouse and mangrove boardwalk"],
 hostels:[{n:"Pousada O Canto do Francês",v:"chill",area:"Soure",price:"$$",f:["breakfast","garden","pool","tours"],gem:true,t:"French-run pousada with a pool and the best breakfast on the island; arranges fazenda visits.",verify:true},
  {n:"Hotel Casarão da Amazônia",v:"boutique",area:"Soure, Praça da Matriz",price:"$$",f:["breakfast","pool","garden"],gem:false,t:"Restored 1920s mansion, a bit worn but atmospheric.",verify:true}]},
{id:"jalapao",name:"Jalapão (Mateiros)",cc:"BR",lat:-10.55,lon:-46.42,kind:"desert",major:false,tags:["desert","nature","swimming","4x4"],days:4,dorm:25,
 tag:"Orange dunes, table mountains and fervedouros – springs so strong you float. Brazil's cerrado at its wildest.",best:"Sep–Oct end of dry season: dusty, hot, all tracks open; Nov–Jan rains, greener but the sand roads get slow.",
 blurb:"Reached by 4x4 from Palmas or, in the app's flow, a long day from Chapada dos Veadeiros (the app stop) through the cerrado, Jalapão is a state park the size of a small country with almost no asphalt. Days go between the Serra do Espírito Santo dunes at sunset, a string of turquoise fervedouros where the spring pressure makes you bob like a cork, and the Cachoeira da Velha on the Rio Novo. Mateiros is the hub; bring cash and expect no mobile signal.",
 hi:["Float in the Fervedouro do Ceiça and Bela Vista springs (timed entry)","Sunset from the dunes with the Serra do Espírito Santo behind","Cachoeira da Velha and the Prainha rapids on the Rio Novo","Capim dourado (golden grass) craft village of Mumbuca"],
 hostels:[{n:"Korubo Safari Camp",v:"eco",area:"Rio Novo, near the dunes",price:"$$$",f:["breakfast","dinner","tours","quiet"],gem:true,t:"Tented safari-style camp on the river; pricey but the only place to sleep inside the wild part of the park.",verify:true}]},
{id:"chapadaguimaraes",name:"Chapada dos Guimarães",cc:"BR",lat:-15.46,lon:-55.75,kind:"nature",major:false,tags:["nature","hiking","waterfalls","viewpoint"],days:2,dorm:15,
 tag:"Red sandstone cliffs and the Véu de Noiva waterfall an hour from Cuiabá – the perfect bookend to the Pantanal.",best:"Sep–Oct dry and hot with clear skies but smoke from cerrado fires possible; Nov–Jan rains fill the waterfalls.",
 blurb:"An hour's bus from Cuiabá, i.e. right next to the Pantanal (the app stop), the town of Chapada sits on the edge of a plateau of red cliffs, macaws and dozens of waterfalls in the national park. You can do the Véu de Noiva and Mirante do Centro Geodésico by public bus, then hire a guide for the Cidade de Pedra canyon and the Circuito das Cachoeiras. Cooler than the Pantanal and the best cheap add-on to it.",
 hi:["Véu de Noiva: 86 m waterfall off the cliff, viewpoint walk","Mirante do Centro Geodésico – the geographic centre of South America","Circuito das Cachoeiras: seven swimmable falls in one hike","Cidade de Pedra canyon at sunset with red-and-green macaws"],
 hostels:[{n:"Pousada Solar do Inglês",v:"boutique",area:"Town centre",price:"$$",f:["breakfast","garden","pool","quiet"],gem:true,t:"Old family house with a lovely garden; the owners know every trail and guide.",verify:true},
  {n:"Pousada Penhasco",v:"chill",area:"Cliff edge, 3 km from town",price:"$$$",f:["pool","breakfast","view"],gem:false,t:"Big resort-style place on the cliff; worth it only for the view rooms.",verify:true}]},
{id:"serracapivara",name:"Serra da Capivara",cc:"BR",lat:-9.01,lon:-42.70,kind:"culture",major:false,tags:["rock art","nature","hiking","desert"],days:3,dorm:15,
 tag:"UNESCO park with 1,000+ rock-art sites, the Pedra Furada arch and a world-class museum in the middle of the sertão. Empty.",best:"Sep–Nov hottest and driest (35 °C+), start hikes at dawn; Dec–Jan first rains green the caatinga.",
 blurb:"It is a slog – bus to Teresina then 8 h to São Raimundo Nonato, or an occasional flight – from Jericoacoara (the app stop), but you arrive at the densest concentration of prehistoric rock art in the Americas, with boardwalks to painted shelters, canyons of red rock and the Museu do Homem Americano and Museu da Natureza. A guide and car are mandatory in the park (cheap if you share). Almost no foreigners make it, which is the point.",
 hi:["Boqueirão da Pedra Furada: the arch and the oldest disputed human site in the Americas","Baixão das Andorinhas canyon at sunset – thousands of swifts","Museu da Natureza and Museu do Homem Americano","Serra Branca circuit: dozens of painted shelters in one day"],
 hostels:[{n:"Hotel Serra da Capivara",v:"chill",area:"São Raimundo Nonato",price:"$$",f:["breakfast","pool","tours"],gem:false,t:"The standard base with a pool; can arrange a guide-plus-car for the park.",verify:true},
  {n:"Pousada Zabelê",v:"chill",area:"São Raimundo Nonato",price:"$",f:["breakfast","quiet","garden"],gem:true,t:"Simple, friendly and cheaper; named after the park's endemic bird.",verify:true}]},
{id:"fordlandia",name:"Fordlândia & the Tapajós",cc:"BR",lat:-3.83,lon:-55.50,kind:"culture",major:false,tags:["culture","river","history","jungle"],days:3,dorm:15,
 tag:"Henry Ford's abandoned 1928 rubber town on the Tapajós: water tower, hospital ruins, a slow boat and nobody else.",best:"Sep–Nov low river: white-sand beaches along the Tapajós, hot; Dec–Jan rising water and afternoon storms.",
 blurb:"From Alter do Chão / Santarém (the app stop) a slow boat takes 8–10 h up the emerald Tapajós to Fordlândia, where Ford's failed American town survives as rusting sawmills, a water tower, art-deco houses and a village that grew into the ruins. Wander the hospital and the manager's row, swim off the beach, then continue by boat or return the same way via the Flona do Tapajós forest reserve. It is industrial archaeology deep in the Amazon, for the price of a hammock ticket.",
 hi:["Ford water tower, sawmill and the ruined hospital (bring a torch)","Vila Americana: the managers' houses and the dance hall","Tapajós beaches at low water and a sunset from the pier","Flona do Tapajós communities (Jamaraquá, Maguari) on the way back"],
 hostels:[{n:"Pousada Americana",v:"chill",area:"Fordlândia village",price:"$",f:["breakfast","quiet"],gem:true,t:"The one guesthouse in town, run by a local family in an old Ford-era house; book by phone or just show up.",verify:true}]},
{id:"novoairao",name:"Novo Airão & Jaú",cc:"BR",lat:-2.63,lon:-60.94,kind:"jungle",major:false,tags:["jungle","wildlife","river","dolphins"],days:3,dorm:15,
 tag:"Rio Negro town where pink dolphins swim to the pier; gateway to Anavilhanas islands and the wild Jaú national park.",best:"Sep–Nov low water: beaches on the Rio Negro, forest hikes possible; Dec–Jan water rising, more boat access.",
 blurb:"A 3 h bus or car over the Rio Negro bridge from Manaus (the app stop) lands you in Novo Airão, a laid-back town on the black-water Rio Negro facing the Anavilhanas archipelago. You can feed wild botos at the floating platform, take a boat into the 400-island labyrinth and, with more time and money, do a multi-day trip into Jaú national park's rapids and untouched forest. Cheaper than any Manaus jungle lodge and the dolphins are real.",
 hi:["Boto encounter at the floating platform (regulated, no touching)","Boat day in Anavilhanas: islands, beaches and igapó forest","Multi-day expedition into Parque Nacional do Jaú (Cachoeira do Jaú)","Waimiri-Atroari and local craft workshops in town"],
 hostels:[{n:"Pousada Bela Vista",v:"chill",area:"Novo Airão, riverside",price:"$",f:["breakfast","hammocks","tours","view"],gem:true,t:"Cheap riverside pousada with hammocks facing the sunset; organises Anavilhanas boats.",verify:true},
  {n:"Mirante do Gavião Amazon Lodge",v:"boutique",area:"Rio Negro bank, edge of town",price:"$$$",f:["breakfast","dinner","pool","tours","view"],gem:false,t:"Design lodge with stilted wooden suites over the river; splurge for one night.",verify:true}]},
// ===================== ECUADOR =====================
{id:"kapawi",name:"Kapawi (Achuar territory)",cc:"EC",lat:-2.53,lon:-76.86,kind:"jungle",major:false,tags:["jungle","indigenous","wildlife","river"],days:4,dorm:200,
 tag:"Achuar-owned ecolodge on the Pastaza, reachable only by bush plane. Dream-guided walks, no roads, no other tourists.",best:"Sep–Nov slightly drier, rivers lower; Dec–Jan wetter with flights occasionally delayed – rain is year-round anyway.",
 blurb:"From Baños (the app stop) a bus drops to Shell airstrip near Puyo, and a small plane flies 1 h over unbroken forest to Kapawi, a lodge owned and run by the Achuar nation. It is expensive (4-day packages from about US$1,200 all-in with flights) but every dollar stays with the community, and the days – dugout paddling, ayahuasca-free dream interpretation at dawn, visiting an Achuar home, night caiman spotting – are nothing like the Napo lodges near Coca. This is the deep Ecuadorian Amazon; Cuyabeno and Yasuní are the accessible versions.",
 hi:["Fly in over the Pastaza: unbroken canopy to the horizon","Visit an Achuar household: guayusa at 4 am and the dream circle","Dugout canoe on blackwater lagoons for hoatzins and caimans","Trail walks with Achuar guides on medicinal plants and hunting"],
 hostels:[{n:"Kapawi Ecolodge",v:"eco",area:"Río Capahuari / Pastaza, Achuar territory",price:"$$$",f:["breakfast","dinner","tours","quiet"],gem:true,t:"Community-owned, solar-powered, one of the few genuinely indigenous-run lodges in the Amazon; packages only.",verify:true}]},
// ===================== BOLIVIA =====================
{id:"trinidadbeni",name:"Trinidad & the Beni (Ibare)",cc:"BO",lat:-14.83,lon:-64.90,kind:"nature",major:false,tags:["wildlife","river","culture","nature"],days:3,dorm:12,
 tag:"Llanos de Moxos savanna, pre-Columbian earthworks, river dolphins in the Ibare and Jesuit-mission music. Bolivia without tourists.",best:"Sep–Oct dry and hot, wildlife concentrated at water; Nov–Jan rains begin and by Jan the savanna floods.",
 blurb:"A 1 h flight from La Paz (the app stop) or a short hop from Rurrenabaque puts you in Trinidad, a motorbike-mad cattle town on the edge of the Llanos de Moxos. Boat trips on the Ibare and Mamoré find Bolivian river dolphins (a species found nowhere else), the Chuchini refuge sits on a pre-Columbian mound with caimans and monkeys, and San Ignacio de Moxos, 90 km away, keeps baroque mission music alive. It is Rurrenabaque's pampas without the party boats.",
 hi:["Boat on the Río Ibare for bufeos (Bolivian river dolphins) and caimans","Chuchini Wildlife Refuge: lagoon, archaeological mound and howler monkeys","Laguna Suárez sunset by motorbike from town","Day trip to San Ignacio de Moxos: mission church and the Ensamble de Moxos"],
 hostels:[{n:"Chuchini Ecolodge",v:"eco",area:"Chuchini refuge, 14 km from Trinidad",price:"$$",f:["breakfast","dinner","tours","quiet"],gem:true,t:"Rooms inside the wildlife refuge; caimans in the lagoon, monkeys on the roof, family-run for decades.",verify:true},
  {n:"Hotel Campanario",v:"chill",area:"Trinidad centre",price:"$$",f:["breakfast","pool"],gem:false,t:"Mid-range town hotel with a pool; fine for arranging river trips.",verify:true}]}
];
// Monthly climate Sep,Oct,Nov,Dec,Jan
const CLIM_REMOTE={
puertonarino:{hi:[32,32,31,31,30],lo:[22,22,22,22,22],rain:[200,250,280,300,320],n:"Hot and humid all year; Sep–Nov lowest water, rains build from Dec."},
canocristales:{hi:[31,31,30,30,32],lo:[22,22,22,21,21],rain:[250,240,180,80,40],n:"River is only visitable mid-Jun to late Nov; from Dec it's dry and closed."},
guaviare:{hi:[31,31,30,31,33],lo:[22,22,22,21,21],rain:[260,230,170,60,30],n:"Wet Sep–Nov (green, full rivers), dry and hot from Dec."},
mitu:{hi:[31,31,31,31,31],lo:[22,22,22,22,22],rain:[220,240,230,200,180],n:"Equatorial: rain every month, Sep–Nov marginally drier with river beaches."},
manu:{hi:[31,32,31,31,31],lo:[19,20,21,21,21],rain:[120,170,220,260,300],n:"Lowland figures; Sep–Nov is the tail of the dry season, rains from Dec."},
oxapampa:{hi:[24,24,24,23,23],lo:[12,13,13,13,13],rain:[90,140,160,200,240],n:"Cool cloud-forest climate at 1,800 m; Dec–Jan wet, Pozuzo road can close."},
marajo:{hi:[32,32,32,32,31],lo:[23,23,23,23,23],rain:[40,30,40,90,300],n:"Sep–Nov bone dry, the island floods Jan–May."},
jalapao:{hi:[34,33,32,31,31],lo:[20,22,22,22,22],rain:[30,120,190,220,250],n:"Sep–Oct dry and hot, rains from Nov make sand tracks slower."},
chapadaguimaraes:{hi:[31,31,30,29,29],lo:[18,20,20,20,20],rain:[50,120,180,240,260],n:"Dry Sep–Oct (fire smoke possible), waterfalls fullest Dec–Jan."},
serracapivara:{hi:[35,36,36,35,34],lo:[21,22,23,23,22],rain:[5,15,50,90,120],n:"Semi-arid sertão: Sep–Nov very hot and dry, first rains Dec."},
fordlandia:{hi:[33,33,33,32,31],lo:[23,23,23,23,23],rain:[40,60,90,180,260],n:"Low water and beaches Sep–Nov, rains and rising river from Dec."},
novoairao:{hi:[33,33,32,31,31],lo:[23,24,24,24,23],rain:[90,110,160,230,270],n:"Rio Negro lowest Oct–Nov, rising from Dec."},
kapawi:{hi:[30,30,30,30,30],lo:[21,21,21,21,21],rain:[280,300,280,260,250],n:"Wet all year; no real dry season, expect daily showers."},
trinidadbeni:{hi:[32,33,33,32,31],lo:[20,21,22,22,22],rain:[70,120,160,200,260],n:"Dry Sep–Oct, rains from Nov; the Llanos flood Jan–Mar. Surazo cold fronts possible."}
};
// Elevation (m)
const ALT_REMOTE={puertonarino:100,canocristales:250,guaviare:175,mitu:200,manu:350,oxapampa:1800,marajo:5,jalapao:500,chapadaguimaraes:800,serracapivara:400,fordlandia:30,novoairao:30,kapawi:240,trinidadbeni:155};
// Legs to/from gateway app stops. m: bus|boat|flight|4x4|car, h hours, u USD, d days consumed
const LEGS_REMOTE={
"leticia>puertonarino":{m:"boat",h:2,u:15,d:0,n:"Fast boat from Leticia's Muelle, 2 h up the Amazon; 2–3 departures daily, book the day before."},
"puertonarino>leticia":{m:"boat",h:2,u:15,d:0,n:"Fast boat back to Leticia, mornings."},
"bogota>canocristales":{m:"flight",h:1.3,u:120,d:0,n:"Satena or charter Bogotá–La Macarena; usually bundled in the tour package."},
"canocristales>bogota":{m:"flight",h:1.3,u:120,d:0,n:"Return flight to Bogotá (or Villavicencio)."},
"bogota>guaviare":{m:"bus",h:9,u:25,d:0,n:"Flota La Macarena night bus from Bogotá's Salitre terminal via Villavicencio; Satena flies too (1 h, ~$90)."},
"guaviare>bogota":{m:"bus",h:9,u:25,d:0,n:"Night bus back to Bogotá."},
"bogota>mitu":{m:"flight",h:1.5,u:130,d:0,n:"Satena from Bogotá, a few flights a week – no road exists."},
"mitu>bogota":{m:"flight",h:1.5,u:130,d:0,n:"Satena back to Bogotá."},
"cusco>manu":{m:"4x4",h:10,u:60,d:1,n:"Tour vehicle over the Paucartambo pass into the cloud forest, then boat from Atalaya; only with an operator (packages ~$500+ for 4–5 days)."},
"manu>cusco":{m:"4x4",h:10,u:60,d:1,n:"Boat to Atalaya/Colorado and vehicle back over the Andes; some tours fly out of Boca Manu."},
"lima>oxapampa":{m:"bus",h:10,u:25,d:0,n:"Night bus (Expreso Lobato / Junín) Lima–Oxapampa via La Merced."},
"oxapampa>lima":{m:"bus",h:10,u:25,d:0,n:"Night bus back to Lima."},
"belem>marajo":{m:"boat",h:3,u:12,d:0,n:"Ferry Belém–Camará (3 h) then shared van or bus to Soure (1 h); mornings."},
"marajo>belem":{m:"boat",h:3,u:12,d:0,n:"Van to Camará, ferry back to Belém."},
"veadeiros>jalapao":{m:"4x4",h:10,u:60,d:1,n:"Long day through the cerrado: bus to Palmas then 4x4/transfer to Mateiros; most people join a 4x4 tour from Palmas."},
"jalapao>veadeiros":{m:"4x4",h:10,u:60,d:1,n:"4x4 to Palmas, then bus south to Alto Paraíso."},
"pantanal>chapadaguimaraes":{m:"bus",h:1.2,u:5,d:0,n:"Hourly bus from Cuiabá's rodoviária up the escarpment."},
"chapadaguimaraes>pantanal":{m:"bus",h:1.2,u:5,d:0,n:"Bus down to Cuiabá."},
"jeri>serracapivara":{m:"bus",h:14,u:50,d:1,n:"Bus/transfer to Fortaleza or Teresina, then 8 h bus to São Raimundo Nonato; occasional flights to the park's own airport."},
"serracapivara>jeri":{m:"bus",h:14,u:50,d:1,n:"Bus via Teresina back to the coast."},
"alterdochao>fordlandia":{m:"boat",h:9,u:20,d:1,n:"Slow boat from Santarém up the Tapajós (hammock deck), 8–10 h; a few departures a week."},
"fordlandia>alterdochao":{m:"boat",h:9,u:20,d:1,n:"Slow boat back down to Santarém."},
"manaus>novoairao":{m:"bus",h:3,u:10,d:0,n:"Bus or shared car over the Rio Negro bridge, 180 km."},
"novoairao>manaus":{m:"bus",h:3,u:10,d:0,n:"Bus back to Manaus."},
"banos>kapawi":{m:"flight",h:2.5,u:250,d:0,n:"Bus to Shell (near Puyo, 1.5 h), then a 1 h charter flight; airfare is part of the lodge package."},
"kapawi>banos":{m:"flight",h:2.5,u:250,d:0,n:"Charter flight to Shell, bus to Baños."},
"lapaz>trinidadbeni":{m:"flight",h:1,u:80,d:0,n:"BoA / EcoJet daily from La Paz; also short flights from Rurrenabaque some days."},
"trinidadbeni>lapaz":{m:"flight",h:1,u:80,d:0,n:"Flight back to La Paz (or on to Santa Cruz)."}
};
