const COUNTRY = {PE:"Peru",EC:"Ecuador",CO:"Colombia",GY:"Guyana",SR:"Suriname",GF:"French Guiana",BR:"Brazil",BO:"Bolivia"};
const GEO_CC = {"Peru":"PE","Ecuador":"EC","Colombia":"CO","Guyana":"GY","Suriname":"SR","French Guiana":"GF","Brazil":"BR","Bolivia":"BO"};
const CC_ORDER = ["PE","EC","CO","GY","SR","GF","BR","BO"];

const COUNTRIES = {
 PE:{img:"machu",currency:"Sol (PEN), ~4.0 per €",cash:"ATMs everywhere (BCP, Scotiabank charge ~$5). Cards fine in cities, cash on the coast and in the mountains.",budget:"$35–45 / day",visa:"Visa-free, 90 days on arrival. Keep the immigration card.",safety:"Petty theft in Lima and on night buses (bag on your lap). Otherwise relaxed.",
   must:["Machu Picchu + Sacred Valley","Cordillera Blanca trek from Huaraz","Máncora surf and pool days","Amazon lodge from Iquitos"],
   note:"Peru Hop buses are pricier than Cruz del Sur but stop at the sights between Lima and Cusco."},
 EC:{img:"quilotoa",currency:"US dollar",cash:"Dollar cash is king; carry small bills. ATMs in every town.",budget:"$30–40 / day, Galápagos $100+",visa:"Visa-free, 90 days.",safety:"Guayaquil and Esmeraldas coast have real problems; avoid Guayaquil beyond the bus terminal. Highlands and Quito old town fine by day, taxi at night.",
   must:["Quilotoa loop and Cotopaxi","Baños adventure days","Montañita or Vilcabamba to slow down","Galápagos if the budget allows"],
   note:"Buses are absurdly cheap ($1–2 per hour). The Piura–Loja international bus from Peru avoids the coast entirely."},
 CO:{img:"cartagena",currency:"Peso (COP), ~4,300 per €",cash:"ATMs cap withdrawals; Bancolombia and Davivienda are the reliable ones. Cards accepted in cities.",budget:"$35–45 / day, Cartagena more",visa:"Visa-free, 90 days.",safety:"Big-city rules: no phone out on the street at night, don't accept drinks from strangers (scopolamine). Countryside and coast are relaxed.",
   must:["Medellín for a week","Cartagena + Tayrona + Minca","Salento coffee valley","Leticia and the Amazon boat if you head to Brazil that way"],
   note:"Domestic flights (Viva, LATAM, Avianca) are often cheaper than the 13-hour buses. Book 2–3 weeks out."},
 GY:{img:"kaieteur",currency:"Guyanese dollar (GYD), ~215 per US$",cash:"Cash economy. Bring US dollars to change; ATMs in Georgetown only (Scotiabank, Republic Bank).",budget:"$50–70 / day; lodges $100+",visa:"Visa-free, 90 days for EU passports.",safety:"Georgetown after dark: taxis only, ask the guesthouse. Interior is safe and friendly. English-speaking.",
   must:["Kaieteur Falls flight","Rupununi savannah and Iwokrama","Stabroek market and the seawall","Ferry to Suriname via Moleson Creek"],
   note:"Overland from Brazil: Boa Vista → Lethem (bus + walk across the bridge), then the overnight minibus to Georgetown on a rough road, 12–16 h. Or fly Lethem–Georgetown."},
 SR:{img:"paramaribo",currency:"Surinamese dollar (SRD), floating; euros widely accepted",cash:"Bring euros in cash. ATMs unreliable for foreign cards; change at official cambios.",budget:"$40–60 / day; river lodges $100/day all-in",visa:"Tourist card / e-visa required for Germans (buy online before arrival, ~€40–55; check current rules).",safety:"Paramaribo is calm; normal city care at night. Interior trips are guided.",
   must:["Paramaribo wooden centre and the food","Upper Suriname river Maroon villages","Commewijne bike + dolphins","Brownsberg nature park"],
   note:"Ferry from Guyana (Moleson Creek → South Drain) once a day, morning. Paramaribo → Albina bus, then pirogue to Saint-Laurent for French Guiana."},
 GF:{img:"kourou",currency:"Euro",cash:"EU rules: cards everywhere, ATMs fine. Prices like France, sometimes higher.",budget:"€70–100 / day (no hostels)",visa:"None for EU citizens; it's France.",safety:"Safe; Cayenne outskirts and Saint-Laurent at night need care. Mosquitoes and heat are the real issue.",
   must:["Kourou space centre tour + launch if timed","Îles du Salut (Papillon's prison)","Cayenne market","Turtle nesting at Awala-Yalimapo (Apr–Jul)"],
   note:"Exit to Brazil: Saint-Georges → Oiapoque bridge/boat, then a 10–12 h bus to Macapá and a boat or flight to Belém. Budget two full days."},
 BR:{img:"lencois",currency:"Real (BRL), ~6 per €",cash:"Pix is everywhere (needs a Brazilian account); cards work almost anywhere. ATMs: Banco do Brasil, Bradesco; many close at 10 pm.",budget:"$40–55 / day; Rio at New Year $80+",visa:"Visa-free, 90 days for Germans.",safety:"Rio and Salvador: nothing valuable on the beach, no walking through unlit areas, Uber at night. The Northeast small towns are relaxed.",
   must:["Lençóis Maranhenses + Alcântara","Jericoacoara sunsets","Salvador's Pelourinho on a Tuesday","Rio for Réveillon"],
   note:"Distances are huge: 12-hour buses are normal. Azul / Gol / LATAM domestic flights are cheap if booked 3+ weeks ahead. Some Portuguese helps a lot; Spanish only half works."},
 BO:{img:"uyuni",currency:"Boliviano (BOB), ~7.5 per €; dollar cash gets a much better street rate",cash:"Bring US dollars: the official ATM rate is far worse than the parallel rate. ATMs work but pay out at the bad rate.",budget:"$20–30 / day",visa:"Visa-free, 90 days.",safety:"Altitude is the main risk (La Paz 3,650 m). Fake police and taxi scams in La Paz: use radio taxis.",
   must:["Salar de Uyuni 3-day jeep","Death Road bike","Isla del Sol","La Paz cable cars"],
   note:"Only worth it if you drop something else: Bolivia costs about a week and sits off the Colombia–Brazil line."}
};

// Explicit legs (either direction). m: bus|flight|boat|train|4x4|ferry. h = door-to-door hours, u = rough USD, d = extra calendar days lost.
const LEGS = {
 "lima>mancora":{m:"bus",h:18,u:45,d:0,n:"Cruz del Sur / Oltursa night bus. Or fly to Talara (1.5 h) + 1 h taxi."},
 "lima>huaraz":{m:"bus",h:8,u:20,d:0,n:"Night bus, arrive at dawn."},
 "mancora>huanchaco":{m:"bus",h:9,u:25,d:0,n:"Via Trujillo."},
 "huanchaco>huaraz":{m:"bus",h:8,u:20,d:0,n:"Night bus Trujillo → Huaraz."},
 "mancora>huaraz":{m:"bus",h:20,u:45,d:1,n:"Change in Trujillo; count a lost day."},
 "mancora>chachapoyas":{m:"bus",h:14,u:35,d:1,n:"Via Chiclayo."},
 "chachapoyas>huaraz":{m:"bus",h:20,u:45,d:1,n:"Back to Chiclayo/Trujillo, then Huaraz."},
 "lima>paracas":{m:"bus",h:4,u:12,d:0,n:"Cruz del Sur or Peru Hop."},
 "paracas>huacachina":{m:"bus",h:1.5,u:8,d:0,n:"Bus to Ica + 10 min taxi."},
 "lima>huacachina":{m:"bus",h:5,u:15,d:0,n:""},
 "huacachina>arequipa":{m:"bus",h:12,u:30,d:0,n:"Night bus from Ica."},
 "arequipa>cusco":{m:"bus",h:10,u:28,d:0,n:"Night bus; or fly 1 h."},
 "cusco>machu":{m:"train",h:4,u:90,d:0,n:"Ollantaytambo train, or colectivo + Hidroeléctrica walk (~$25, 8 h)."},
 "cusco>titicaca":{m:"bus",h:7,u:22,d:0,n:"Day bus to Puno; the tourist bus stops at ruins."},
 "titicaca>lapaz":{m:"bus",h:6,u:15,d:0,n:"Via the Copacabana border."},
 "lapaz>uyuni":{m:"bus",h:10,u:25,d:0,n:"Night bus."},
 "arequipa>titicaca":{m:"bus",h:6,u:18,d:0,n:""},
 "lima>cusco":{m:"flight",h:1.5,u:70,d:0,n:"LATAM / Sky, frequent."},
 "lima>iquitos":{m:"flight",h:2,u:85,d:0,n:"No road access."},
 "iquitos>lima":{m:"flight",h:2,u:85,d:0,n:""},
 "lima>arequipa":{m:"flight",h:1.5,u:60,d:0,n:"Or 16 h bus."},
 "iquitos>leticia":{m:"boat",h:12,u:80,d:0,n:"Speedboat down the Amazon to Santa Rosa / Leticia, early departures."},
 "iquitos>manaus":{m:"boat",h:110,u:180,d:5,n:"Speedboat to Leticia, then the slow boat."},
 // Peru → Ecuador
 "mancora>montanita":{m:"bus",h:8,u:22,d:0,n:"Tumbes border, change in Guayaquil."},
 "mancora>vilcabamba":{m:"bus",h:10,u:20,d:0,n:"Piura → Loja international bus (skips the coast), then 1.5 h to Vilcabamba."},
 "mancora>cuenca":{m:"bus",h:9,u:22,d:0,n:"Tumbes → Machala → Cuenca."},
 "vilcabamba>cuenca":{m:"bus",h:5,u:10,d:0,n:"Via Loja."},
 "vilcabamba>banos":{m:"bus",h:11,u:18,d:0,n:"Via Cuenca and Riobamba."},
 "montanita>cuenca":{m:"bus",h:6,u:14,d:0,n:"Via Guayaquil."},
 "montanita>banos":{m:"bus",h:9,u:18,d:0,n:"Via Guayaquil."},
 "montanita>quito":{m:"bus",h:10,u:18,d:0,n:"Night bus via Guayaquil or Manta."},
 "cuenca>banos":{m:"bus",h:6,u:12,d:0,n:""},
 "banos>tena":{m:"bus",h:3,u:5,d:0,n:"Via Puyo, jungle road."},
 "tena>quito":{m:"bus",h:5,u:8,d:0,n:""},
 "banos>quilotoa":{m:"bus",h:3,u:6,d:0,n:"Bus to Latacunga, then Sigchos/Isinliví."},
 "quilotoa>cotopaxi":{m:"bus",h:2.5,u:10,d:0,n:"Latacunga, then lodge pickup."},
 "quilotoa>quito":{m:"bus",h:3.5,u:6,d:0,n:"Via Latacunga."},
 "cotopaxi>quito":{m:"bus",h:1.5,u:5,d:0,n:"Lodge shuttle or bus from Machachi."},
 "banos>quito":{m:"bus",h:3.5,u:6,d:0,n:""},
 "quito>mindo":{m:"bus",h:2.5,u:4,d:0,n:"From Ofelia terminal."},
 "mindo>otavalo":{m:"bus",h:4,u:8,d:0,n:"Via Quito."},
 "quito>otavalo":{m:"bus",h:2.5,u:4,d:0,n:"From Carcelén terminal."},
 "quito>galapagos":{m:"flight",h:2.5,u:450,d:0,n:"Return ticket ~$450 + $200 park fee + $20 transit card."},
 // Ecuador → Colombia
 "otavalo>cali":{m:"bus",h:14,u:30,d:0,n:"Tulcán, walk the Ipiales border, bus to Cali. Las Lajas church on the way."},
 "quito>cali":{m:"bus",h:16,u:35,d:1,n:"Bus to Tulcán, walk the Ipiales border, bus to Cali."},
 "quito>bogota":{m:"flight",h:1.5,u:120,d:0,n:"Avianca / LATAM."},
 "quito>medellin":{m:"flight",h:1.5,u:130,d:0,n:""},
 "otavalo>bogota":{m:"flight",h:5,u:125,d:0,n:"Back to Quito airport, fly."},
 // Colombia
 "cali>salento":{m:"bus",h:4,u:10,d:0,n:"Via Armenia."},
 "salento>medellin":{m:"bus",h:7,u:16,d:0,n:"Via Pereira."},
 "bogota>salento":{m:"bus",h:8,u:18,d:0,n:"Via Armenia; or fly to Pereira 1 h."},
 "bogota>medellin":{m:"flight",h:1,u:50,d:0,n:"Or 9 h bus."},
 "bogota>sangil":{m:"bus",h:7,u:15,d:0,n:""},
 "sangil>medellin":{m:"bus",h:9,u:20,d:0,n:""},
 "sangil>cartagena":{m:"bus",h:13,u:30,d:0,n:"Night bus."},
 "medellin>guatape":{m:"bus",h:2,u:5,d:0,n:"From the north terminal."},
 "guatape>cartagena":{m:"flight",h:5,u:60,d:0,n:"Back to Medellín, fly."},
 "medellin>cartagena":{m:"flight",h:1,u:55,d:0,n:"Viva / LATAM; the bus is 13 h."},
 "cartagena>tayrona":{m:"bus",h:4.5,u:12,d:0,n:"Marsol / Berlinas door-to-door to Santa Marta."},
 "tayrona>minca":{m:"bus",h:1,u:4,d:0,n:"Colectivo from the Santa Marta market."},
 "minca>palomino":{m:"bus",h:2.5,u:6,d:0,n:"Down to Santa Marta, bus east."},
 "tayrona>palomino":{m:"bus",h:1.5,u:5,d:0,n:""},
 "bogota>leticia":{m:"flight",h:2,u:110,d:0,n:"Only by air."},
 "medellin>leticia":{m:"flight",h:4,u:150,d:0,n:"Via Bogotá."},
 "cartagena>leticia":{m:"flight",h:5,u:170,d:0,n:"Via Bogotá."},
 "leticia>manaus":{m:"boat",h:84,u:110,d:4,n:"Slow boat from Tabatinga, hammock on deck, ~3.5 days. Speedboat ~36 h, $180."},
 // Colombia → Brazil / Guianas by air
 "cartagena>saoluis":{m:"flight",h:14,u:380,d:1,n:"Via Bogotá + São Paulo or Fortaleza."},
 "bogota>saoluis":{m:"flight",h:12,u:350,d:1,n:"Via Fortaleza or São Paulo; sometimes an overnight layover."},
 "palomino>saoluis":{m:"flight",h:16,u:390,d:1,n:"Bus to Santa Marta, fly via Bogotá."},
 "tayrona>saoluis":{m:"flight",h:15,u:385,d:1,n:"Fly from Santa Marta via Bogotá."},
 "cartagena>fortaleza":{m:"flight",h:11,u:330,d:1,n:"Via Bogotá."},
 "bogota>fortaleza":{m:"flight",h:9,u:300,d:0,n:"Via São Paulo or a seasonal direct."},
 "cartagena>rio":{m:"flight",h:10,u:320,d:0,n:"Via Bogotá."},
 "bogota>rio":{m:"flight",h:7,u:290,d:0,n:"Avianca / LATAM."},
 "medellin>rio":{m:"flight",h:9,u:310,d:0,n:"Via Bogotá."},
 "bogota>georgetown":{m:"flight",h:9,u:450,d:0,n:"Copa via Panama City."},
 "cartagena>georgetown":{m:"flight",h:8,u:430,d:0,n:"Copa via Panama City."},
 "bogota>paramaribo":{m:"flight",h:10,u:500,d:0,n:"Via Panama or Curaçao."},
 // Peru → Colombia by air
 "lima>bogota":{m:"flight",h:3,u:150,d:0,n:"Direct, frequent."},
 "cusco>bogota":{m:"flight",h:7,u:230,d:0,n:"Via Lima."},
 "cusco>medellin":{m:"flight",h:8,u:250,d:0,n:"Via Lima."},
 "cusco>quito":{m:"flight",h:6,u:220,d:0,n:"Via Lima."},
 "lima>quito":{m:"flight",h:2.5,u:140,d:0,n:""},
 "lima>medellin":{m:"flight",h:3.5,u:170,d:0,n:""},
 "cusco>lima":{m:"flight",h:1.5,u:70,d:0,n:""},
 "cusco>rio":{m:"flight",h:12,u:380,d:0,n:"Via Lima and São Paulo."},
 "machu>quito":{m:"flight",h:9,u:230,d:0,n:"Train to Cusco, fly via Lima."},
 "machu>bogota":{m:"flight",h:10,u:240,d:0,n:"Train to Cusco, fly via Lima."},
 // Brazil north + Guianas overland
 "manaus>boavista":{m:"bus",h:12,u:35,d:0,n:"Night bus, Eucatur."},
 "boavista>rupununi":{m:"bus",h:5,u:20,d:0,n:"Bus to Bonfim, walk the bridge to Lethem, lodge transfer."},
 "boavista>georgetown":{m:"bus",h:16,u:50,d:1,n:"Lethem, then the overnight minibus on the dirt road."},
 "rupununi>georgetown":{m:"bus",h:12,u:40,d:0,n:"Overnight minibus from Lethem/Annai; or fly from Lethem 1.5 h ~$150."},
 "georgetown>kaieteur":{m:"flight",h:1,u:230,d:0,n:"Day trip from Ogle, 12-seater."},
 "kaieteur>georgetown":{m:"flight",h:1,u:0,d:0,n:"Return flight is in the day-trip price."},
 "georgetown>paramaribo":{m:"ferry",h:10,u:35,d:0,n:"Minibus to Moleson Creek, the 11 am ferry to South Drain, minibus to Paramaribo."},
 "paramaribo>uppersuriname":{m:"boat",h:6,u:60,d:0,n:"Bus to Atjoni + korjaal upriver; usually part of a lodge package."},
 "uppersuriname>paramaribo":{m:"boat",h:6,u:0,d:0,n:"Included in the package."},
 "paramaribo>cayenne":{m:"bus",h:8,u:60,d:0,n:"Bus to Albina, pirogue across to Saint-Laurent, shared taxi to Cayenne (€40)."},
 "cayenne>kourou":{m:"bus",h:1.5,u:8,d:0,n:"Regional bus or shared taxi."},
 "kourou>belem":{m:"bus",h:60,u:150,d:2,n:"Saint-Georges → Oiapoque, 12 h bus to Macapá, boat (24 h) or flight to Belém. Budget three days."},
 "cayenne>belem":{m:"bus",h:60,u:150,d:2,n:"Via Oiapoque and Macapá; or fly ~$350 (Surinam Airways / Azul, check schedules)."},
 "manaus>belem":{m:"boat",h:100,u:120,d:4,n:"4–5 days downriver in a hammock. Or fly 2 h ~$120."},
 "manaus>saoluis":{m:"flight",h:6,u:200,d:0,n:"Via Belém or Brasília."},
 "belem>saoluis":{m:"bus",h:12,u:40,d:0,n:"Night bus."},
 "saoluis>alcantara":{m:"boat",h:1.5,u:6,d:0,n:"Morning boat from the Terminal Hidroviário, tide-dependent."},
 "saoluis>lencois":{m:"bus",h:4.5,u:15,d:0,n:"To Barreirinhas; Atins another 1.5 h by boat/4x4."},
 "alcantara>lencois":{m:"bus",h:6,u:20,d:0,n:"Boat back to São Luís, then bus."},
 "lencois>jeri":{m:"4x4",h:14,u:150,d:1,n:"Rota das Emoções: 4x4 along the beach via Parnaíba/Camocim, usually 2 days."},
 "jeri>fortaleza":{m:"bus",h:6,u:25,d:0,n:"Bus to Jijoca + 4x4, or a direct transfer."},
 "lencois>fortaleza":{m:"bus",h:10,u:35,d:0,n:"Night bus from Barreirinhas via São Luís."},
 "fortaleza>pipa":{m:"bus",h:9,u:35,d:0,n:"Bus to Natal + 1.5 h."},
 "jeri>pipa":{m:"bus",h:15,u:55,d:1,n:"Via Fortaleza and Natal."},
 "pipa>olinda":{m:"bus",h:5,u:20,d:0,n:"Natal → Recife, then 30 min to Olinda."},
 "olinda>salvador":{m:"flight",h:1.5,u:80,d:0,n:"Or a 13 h night bus, $45."},
 "pipa>salvador":{m:"flight",h:3,u:110,d:0,n:"From Natal."},
 "fortaleza>salvador":{m:"flight",h:2,u:90,d:0,n:""},
 "salvador>morro":{m:"boat",h:2.5,u:25,d:0,n:"Catamaran from the Mercado Modelo pier."},
 "salvador>chapada":{m:"bus",h:6,u:22,d:0,n:"To Lençóis (Bahia)."},
 "chapada>morro":{m:"bus",h:9,u:45,d:0,n:"Back via Salvador."},
 "salvador>rio":{m:"flight",h:2,u:95,d:0,n:""},
 "morro>rio":{m:"flight",h:6,u:120,d:0,n:"Catamaran back to Salvador, then fly."},
 "chapada>rio":{m:"flight",h:9,u:120,d:0,n:"Bus to Salvador, then fly."},
 "rio>ilhagrande":{m:"boat",h:4,u:25,d:0,n:"Bus to Conceição de Jacareí + fast boat."},
 "ilhagrande>paraty":{m:"boat",h:3,u:22,d:0,n:"Boat + bus via Angra."},
 "rio>paraty":{m:"bus",h:4.5,u:22,d:0,n:"Costa Verde bus."},
 "salvador>ilhagrande":{m:"flight",h:7,u:120,d:0,n:"Fly to Rio, then bus + boat."},
 "morro>ilhagrande":{m:"flight",h:10,u:145,d:0,n:"Boat, flight, bus, boat: a full day."},
 "rio>floripa":{m:"flight",h:1.5,u:70,d:0,n:""},
 "rio>iguazu":{m:"flight",h:2,u:85,d:0,n:""},
 "floripa>iguazu":{m:"bus",h:16,u:50,d:0,n:"Night bus."},
 "uyuni>saoluis":{m:"flight",h:20,u:450,d:1,n:"Uyuni → La Paz flight, then via São Paulo. Long."},
 "lapaz>rio":{m:"flight",h:8,u:300,d:0,n:"Via São Paulo."},
 "uyuni>rio":{m:"flight",h:12,u:330,d:0,n:"Uyuni → La Paz → São Paulo → Rio."},
 "lapaz>saoluis":{m:"flight",h:14,u:420,d:1,n:"Via São Paulo."},
 "huacachina>nazca":{m:"bus",h:2,u:8,d:0,n:"Bus from Ica."},
 "nazca>arequipa":{m:"bus",h:10,u:28,d:0,n:"Night bus."},
 "lima>nazca":{m:"bus",h:7,u:20,d:0,n:""},
 "cusco>tambopata":{m:"bus",h:10,u:22,d:0,n:"Night bus to Puerto Maldonado; or fly 1 h ~$60."},
 "tambopata>lapaz":{m:"bus",h:14,u:30,d:0,n:"Via the Peru–Bolivia border at Puerto Heath, rough; or fly via Lima."},
 "montanita>puertolopez":{m:"bus",h:0.7,u:2,d:0,n:"Local bus."},
 "puertolopez>cuenca":{m:"bus",h:7,u:15,d:0,n:"Via Guayaquil."},
 "puertolopez>banos":{m:"bus",h:10,u:18,d:0,n:"Via Guayaquil."},
 "quito>cuyabeno":{m:"bus",h:9,u:14,d:0,n:"Night bus to Lago Agrio; lodge transport included from there."},
 "cuyabeno>quito":{m:"bus",h:9,u:14,d:0,n:"Night bus back from Lago Agrio."},
 "cuyabeno>otavalo":{m:"bus",h:10,u:16,d:0,n:"Via Quito."},
 "cartagena>sanandres":{m:"flight",h:1.5,u:90,d:0,n:"Direct flights; tourist card ~$30 at the gate."},
 "medellin>sanandres":{m:"flight",h:1.5,u:90,d:0,n:""},
 "sanandres>cartagena":{m:"flight",h:1.5,u:90,d:0,n:""},
 "bogota>villadeleyva":{m:"bus",h:3.5,u:9,d:0,n:"From Bogotá's north terminal."},
 "villadeleyva>sangil":{m:"bus",h:4,u:10,d:0,n:"Via Tunja."},
 "medellin>jardin":{m:"bus",h:3.5,u:8,d:0,n:"From the south terminal."},
 "jardin>salento":{m:"bus",h:5,u:12,d:0,n:"Via Riosucio and Pereira, scenic."},
 "jardin>cali":{m:"bus",h:7,u:16,d:0,n:"Via Pereira."},
 "bogota>tatacoa":{m:"bus",h:6,u:14,d:0,n:"To Neiva, then Villavieja."},
 "tatacoa>cali":{m:"bus",h:7,u:15,d:0,n:"Via Neiva."},
 "tatacoa>salento":{m:"bus",h:7,u:15,d:0,n:"Via Neiva and Ibagué."},
 "palomino>cabodelavela":{m:"4x4",h:5,u:20,d:0,n:"Bus to Riohacha, colectivo to Uribia, 4x4 to Cabo."},
 "tayrona>cabodelavela":{m:"4x4",h:6,u:22,d:0,n:"Santa Marta → Riohacha → Uribia → Cabo."},
 "cabodelavela>tayrona":{m:"4x4",h:6,u:22,d:0,n:""},
 "cabodelavela>saoluis":{m:"flight",h:18,u:400,d:1,n:"Back to Santa Marta, fly via Bogotá."},
 "medellin>nuqui":{m:"flight",h:1,u:150,d:0,n:"Satena small plane from Olaya Herrera airport."},
 "nuqui>medellin":{m:"flight",h:1,u:150,d:0,n:""},
 "georgetown>iwokrama":{m:"bus",h:8,u:35,d:0,n:"Georgetown–Lethem minibus drops at the lodge road."},
 "iwokrama>rupununi":{m:"bus",h:3,u:15,d:0,n:"Same road south."},
 "rupununi>iwokrama":{m:"bus",h:3,u:15,d:0,n:""},
 "boavista>iwokrama":{m:"bus",h:8,u:30,d:0,n:"Via Lethem."},
 "paramaribo>brownsberg":{m:"bus",h:3,u:25,d:0,n:"STINASU transfer or bus to Brownsweg + 4x4."},
 "brownsberg>uppersuriname":{m:"bus",h:4,u:30,d:0,n:"Back to the Atjoni road."},
 "brownsberg>cayenne":{m:"bus",h:10,u:70,d:0,n:"Via Paramaribo and Albina."},
 "paramaribo>saintlaurent":{m:"bus",h:4,u:25,d:0,n:"Bus to Albina, pirogue across the Maroni."},
 "saintlaurent>kourou":{m:"bus",h:3,u:30,d:0,n:"Shared taxi along the coast road."},
 "saintlaurent>cayenne":{m:"bus",h:4,u:40,d:0,n:"Shared taxi (€40)."},
 "titicaca>sucre":{m:"bus",h:14,u:30,d:0,n:"Via La Paz, night bus."},
 "lapaz>sucre":{m:"bus",h:12,u:25,d:0,n:"Night bus; or fly 45 min ~$60."},
 "sucre>potosi":{m:"bus",h:3,u:6,d:0,n:""},
 "potosi>uyuni":{m:"bus",h:4,u:8,d:0,n:""},
 "sucre>uyuni":{m:"bus",h:8,u:15,d:0,n:"Via Potosí."},
 "lapaz>rurrenabaque":{m:"flight",h:1,u:100,d:0,n:"Amaszonas, 40 min. The bus takes 18 h."},
 "rurrenabaque>lapaz":{m:"flight",h:1,u:100,d:0,n:""},
 "sucre>samaipata":{m:"bus",h:12,u:25,d:0,n:"Via Santa Cruz, night bus."},
 "samaipata>saoluis":{m:"flight",h:14,u:420,d:1,n:"Santa Cruz → São Paulo → São Luís."},
 "samaipata>rio":{m:"flight",h:8,u:320,d:0,n:"Santa Cruz → São Paulo → Rio."},
 "uyuni>samaipata":{m:"bus",h:16,u:30,d:1,n:"Via Sucre and Santa Cruz."},
 "manaus>alterdochao":{m:"boat",h:36,u:70,d:1,n:"Slow boat to Santarém (1.5 days) or fly 1 h ~$120."},
 "alterdochao>belem":{m:"boat",h:48,u:90,d:2,n:"Boat Santarém → Belém, 2 days; or fly 1.5 h ~$130."},
 "belem>alterdochao":{m:"flight",h:1.5,u:130,d:0,n:"Fly to Santarém."},
 "olinda>noronha":{m:"flight",h:1.5,u:250,d:0,n:"From Recife; return ticket ~$250 + island taxes."},
 "noronha>olinda":{m:"flight",h:1.5,u:0,d:0,n:"Return leg of the ticket."},
 "pipa>noronha":{m:"flight",h:2,u:250,d:0,n:"From Natal."},
 "noronha>salvador":{m:"flight",h:4,u:180,d:0,n:"Via Recife."},
 "salvador>trancoso":{m:"flight",h:3,u:110,d:0,n:"Fly to Porto Seguro, ferry + bus; or 12 h night bus $50."},
 "morro>trancoso":{m:"bus",h:12,u:55,d:0,n:"Boat to Valença, bus south."},
 "trancoso>rio":{m:"flight",h:3,u:120,d:0,n:"From Porto Seguro."},
 "trancoso>ilhagrande":{m:"flight",h:7,u:140,d:0,n:"Fly to Rio, bus + boat."},
 "rio>ouropreto":{m:"bus",h:7,u:30,d:0,n:"Night bus via Belo Horizonte; or fly to BH 1 h."},
 "ouropreto>rio":{m:"bus",h:7,u:30,d:0,n:""},
 "ouropreto>saopaulo":{m:"bus",h:10,u:35,d:0,n:"Night bus."},
 "rio>saopaulo":{m:"bus",h:6,u:25,d:0,n:"Every hour; or fly 1 h."},
 "paraty>saopaulo":{m:"bus",h:5,u:22,d:0,n:""},
 "saopaulo>floripa":{m:"flight",h:1,u:60,d:0,n:"Or 12 h bus."},
 "saopaulo>iguazu":{m:"flight",h:1.5,u:70,d:0,n:"Or 16 h bus."},
 "saopaulo>bonito":{m:"flight",h:5,u:120,d:0,n:"Fly to Campo Grande, 4–5 h bus."},
 "bonito>pantanal":{m:"bus",h:4,u:25,d:0,n:"Lodge transfer via Miranda / Buraco das Piranhas."},
 "pantanal>bonito":{m:"bus",h:4,u:25,d:0,n:""},
 "pantanal>iguazu":{m:"bus",h:14,u:50,d:0,n:"Night bus from Campo Grande."},
 "pantanal>saopaulo":{m:"flight",h:3,u:110,d:0,n:"From Campo Grande."},
 "pantanal>rio":{m:"flight",h:4,u:150,d:0,n:"From Campo Grande via São Paulo."},
 "bonito>iguazu":{m:"bus",h:15,u:55,d:0,n:"Via Campo Grande / Dourados."},
 "samaipata>pantanal":{m:"bus",h:20,u:60,d:1,n:"Santa Cruz → Puerto Quijarro train, cross to Corumbá."},
 "veadeiros>rio":{m:"flight",h:5,u:130,d:0,n:"Bus to Brasília, fly."},
 "salvador>veadeiros":{m:"flight",h:7,u:160,d:0,n:"Fly to Brasília, 4 h bus."},
 "veadeiros>saopaulo":{m:"flight",h:5,u:120,d:0,n:"Via Brasília."},
 "manaus>mamiraua":{m:"flight",h:1.5,u:120,d:0,n:"Azul flight to Tefé, or the 2-day slow boat ($40)."},
 "leticia>mamiraua":{m:"boat",h:48,u:70,d:2,n:"The Manaus slow boat stops at Tefé; get off there."},
 "mamiraua>manaus":{m:"flight",h:1.5,u:120,d:0,n:"Or the 1-day fast boat."},
 "manaus>anavilhanas":{m:"bus",h:3,u:10,d:0,n:"Bus or shared van to Novo Airão."},
 "anavilhanas>manaus":{m:"bus",h:3,u:10,d:0,n:""},
 "anavilhanas>boavista":{m:"bus",h:14,u:40,d:0,n:"Back to Manaus, night bus north."},
 "iquitos>pacaya":{m:"bus",h:2,u:6,d:0,n:"Colectivo to Nauta, guide boat from there."},
 "pacaya>iquitos":{m:"bus",h:2,u:6,d:0,n:""},
 "pacaya>leticia":{m:"boat",h:14,u:85,d:0,n:"Back to Iquitos, speedboat down the Amazon."},
 "quito>yasuni":{m:"bus",h:9,u:12,d:0,n:"Night bus to Coca, lodge canoe next morning; or fly 40 min ~$90."},
 "yasuni>quito":{m:"bus",h:9,u:12,d:0,n:""},
 "cuyabeno>yasuni":{m:"bus",h:5,u:10,d:0,n:"Lago Agrio → Coca bus."},
 "tena>yasuni":{m:"bus",h:4,u:8,d:0,n:"Tena → Coca."},
 "tambopata>xapuri":{m:"bus",h:8,u:25,d:0,n:"Puerto Maldonado → Iñapari border → Assis Brasil → Xapuri."},
 "xapuri>rurrenabaque":{m:"bus",h:20,u:50,d:1,n:"Via Rio Branco, Brasiléia and Cobija into Bolivia; rough."},
 "xapuri>manaus":{m:"flight",h:4,u:150,d:0,n:"From Rio Branco."},
};

const PRESETS = [
 {name:"Route-optimised v6.8",tagline:"Recommended. One continuous line: Peru coast into the Andes (Colca, Cusco, Machu Picchu, Tambopata, Titicaca both sides), La Paz, the salt flats into the Atacama, one flight back to northern Peru, overland through Ecuador and Colombia, fly to the Amazon, then west to east along the river to the coast, Pantanal, Rio.",
  stops:[["lima",2],["paracas",1],["huacachina",2],["nazca",1],["arequipa",5],["cusco",2],["machu",2],["cusco",1],["tambopata",3],["cusco",1],["titicaca",4],["lapaz",3],["uyuni",1],["atacama",4],["chachapoyas",3],["mancora",7],["cuenca",2],["banos",2],["quilotoa",3],["quito",2],["cuyabeno",4],["bogota",3],["salento",3],["medellin",4],["cartagena",3],["tayrona",3],["cabodelavela",3],["novoairao",3],["fordlandia",3],["jeri",3],["pantanal",3]]},
 {name:"Gringo Trail North",tagline:"Peru top to bottom, fly to Colombia, fly to the Brazilian Northeast, coast down to Rio via Ilha Grande.",
  stops:[["lima",2],["mancora",5],["huaraz",5],["lima",1],["paracas",1],["huacachina",2],["arequipa",4],["cusco",5],["machu",2],["titicaca",2],["cusco",1],["bogota",3],["salento",3],["medellin",6],["guatape",1],["cartagena",5],["tayrona",5],["minca",2],["palomino",3],["saoluis",2],["alcantara",1],["lencois",4],["jeri",6],["fortaleza",1],["pipa",5],["olinda",2],["salvador",6],["chapada",3],["morro",3],["ilhagrande",4],["paraty",3]]},
 {name:"Andes Overland",tagline:"Máncora into Ecuador by the Loja bus: Vilcabamba, Quilotoa, Cotopaxi, Quito, then Colombia by land. One flight to Brazil.",
  stops:[["lima",2],["huaraz",4],["lima",1],["paracas",1],["huacachina",2],["arequipa",4],["cusco",4],["machu",2],["lima",1],["mancora",4],["vilcabamba",3],["cuenca",2],["banos",4],["quilotoa",3],["cotopaxi",2],["quito",3],["otavalo",2],["cali",2],["salento",3],["medellin",5],["guatape",1],["cartagena",5],["tayrona",5],["palomino",3],["saoluis",2],["alcantara",1],["lencois",4],["jeri",5],["pipa",4],["salvador",5],["morro",3],["ilhagrande",4]]},
 {name:"Amazon & Guianas",tagline:"The big loop: Leticia hammock boat to Manaus, bus north to Guyana, ferry to Suriname, French Guiana's spaceport, overland back into Brazil at Belém.",
  stops:[["lima",2],["mancora",4],["huaraz",4],["lima",1],["huacachina",2],["arequipa",3],["cusco",5],["machu",2],["bogota",2],["medellin",5],["guatape",1],["cartagena",5],["tayrona",5],["bogota",1],["leticia",3],["manaus",3],["boavista",1],["rupununi",3],["georgetown",2],["kaieteur",1],["georgetown",1],["paramaribo",3],["uppersuriname",3],["cayenne",2],["kourou",1],["belem",2],["saoluis",2],["alcantara",1],["lencois",4],["jeri",5],["fortaleza",1],["salvador",5],["morro",3]]},
 {name:"Slow & Beachy",tagline:"Fewer stops, longer stays. Surf towns, pool hostels, the Northeast beaches, Costa Verde before Rio.",
  stops:[["lima",2],["mancora",8],["cusco",7],["machu",2],["arequipa",4],["medellin",8],["cartagena",7],["tayrona",6],["minca",3],["palomino",5],["saoluis",2],["alcantara",1],["lencois",4],["jeri",9],["pipa",7],["salvador",7],["morro",5],["ilhagrande",6],["paraty",4]]},
 {name:"Bolivia Detour",tagline:"Iquitos, Titicaca, La Paz and the salt flats, then fly straight to São Luís. Colombia is dropped.",
  stops:[["lima",2],["iquitos",4],["lima",1],["mancora",6],["huaraz",6],["lima",1],["paracas",1],["huacachina",2],["arequipa",5],["cusco",7],["machu",2],["titicaca",3],["lapaz",6],["uyuni",4],["lapaz",1],["saoluis",2],["alcantara",1],["lencois",5],["jeri",7],["fortaleza",1],["pipa",5],["olinda",4],["salvador",7],["chapada",4],["morro",5],["ilhagrande",5],["paraty",3]]},
];
