// Southern Cone: Chile, Argentina, Paraguay (v6)
const STOPS_SOUTH=[
// ---- Chile ----
{id:"santiago",name:"Santiago",cc:"CL",lat:-33.45,lon:-70.67,kind:"city",major:true,tags:["city","food","wine","mountains"],days:3,dorm:18,
 tag:"Andes backdrop, Barrio Italia, Cajón del Maipo hot springs. The hub for the whole south.",best:"Spring Sep–Nov is clear and mild; Dec hot.",
 blurb:"Not the prettiest capital but the easiest: Cerro San Cristóbal, Bellavista and Lastarria bars, Maipo valley wineries an hour away, snow on the Andes until November. Flights everywhere from here; Valparaíso is 90 minutes by bus.",
 hi:["Cerro San Cristóbal at sunset","Cajón del Maipo and the Colina hot springs","Maipo valley winery by bike","Mercado Central seafood lunch"],
 hostels:[{n:"La Chimba Hostel",v:"party",area:"Bellavista",price:"$$",f:["bar","rooftop","kitchen"],t:"Big, social, bar nights, in the nightlife barrio."},{n:"Hostal Forestal",v:"social",area:"Lastarria",price:"$$",f:["kitchen","garden"],t:"Old house by Parque Forestal, calm crowd, best location."},{n:"Hostal Providencia",v:"chill",area:"Providencia",price:"$$",f:["kitchen","garden","quiet"],verify:true,t:"Garden, near the metro."}]},
{id:"valparaiso",name:"Valparaíso",cc:"CL",lat:-33.05,lon:-71.62,kind:"city",major:true,tags:["city","art","colonial","coast"],days:2,dorm:16,
 tag:"Hillside port of street art, funiculars and Neruda's house.",best:"Any; foggy mornings, clear afternoons.",
 blurb:"Cerros Alegre and Concepción are the ones to stay on: murals on every wall, 1900s funiculars, wine bars in painted mansions. Viña del Mar next door for the beach. Ninety minutes from Santiago.",
 hi:["Cerro Alegre street-art walk","Ascensor El Peral funicular","La Sebastiana (Neruda's house)","Sunset at Paseo 21 de Mayo"],
 hostels:[{n:"Casa Volante Hostal",v:"social",area:"Cerro Alegre",price:"$$",f:["kitchen","view","bar"],t:"Painted house on the hill, terrace, social."},{n:"La Joya Hostel",v:"party",area:"Cerro Alegre",price:"$$",f:["bar","rooftop"],t:"Rooftop bar, big, party crowd."},{n:"Hostal Casa Verde Limón",v:"chill",area:"Cerro Concepción",price:"$",f:["kitchen","garden"],verify:true,t:"Small, colourful, quiet."}]},
{id:"atacama",name:"San Pedro de Atacama",cc:"CL",lat:-22.91,lon:-68.20,kind:"desert",major:true,tags:["desert","stars","geysers","nature"],days:4,dorm:20,
 tag:"Driest desert on earth: geysers at dawn, salt lagoons, the best night sky you'll ever see.",best:"Sep–Nov clear and mild; nights below zero.",
 blurb:"Adobe village at 2,400 m that the Uyuni jeep tours end in. Tatio geysers at sunrise, Valle de la Luna at sunset, floating in the Cejar lagoon, flamingos, and a star tour with real telescopes. Expensive by Chilean standards.",
 hi:["El Tatio geysers at dawn (4,300 m)","Valle de la Luna sunset by bike","Laguna Cejar float","Astronomy tour with telescopes","Piedras Rojas and the altiplano lagoons"],
 hostels:[{n:"Hostal Rural",v:"chill",area:"Village",price:"$$",f:["kitchen","garden","quiet"],t:"Adobe rooms around a garden, calm."},{n:"Backpackers San Pedro",v:"social",area:"Village",price:"$$",f:["kitchen","bar"],t:"Social, tours from the desk."},{n:"Hostal Sonchek",v:"chill",area:"Village",price:"$$",f:["kitchen","garden"],verify:true,t:"Garden hammocks, near the church."}]},
{id:"pucon",name:"Pucón",cc:"CL",lat:-39.28,lon:-71.98,kind:"mountain",major:true,tags:["volcano","adventure","lakes"],days:3,dorm:18,
 tag:"Climb an active volcano in the morning, hot springs at night.",best:"Nov–Mar for the volcano climb; Sep–Oct snowy and quieter.",
 blurb:"Chile's adventure town on Lake Villarrica: the day-climb of the smoking Villarrica volcano (crampons, guided), Huerquehue park hikes, rafting on the Trancura, dozens of hot springs in the forest.",
 hi:["Villarrica volcano summit","Termas Geométricas hot springs","Huerquehue park lakes hike","Lake beach at sunset"],
 hostels:[{n:"Chili Kiwi Hostel",v:"social",area:"Lakefront",price:"$$",f:["view","bar","tours","hammocks"],gem:true,t:"Hobbit holes and tree houses on the lake; the best-run hostel in Chile."},{n:"Hostal École",v:"chill",area:"Centre",price:"$$",f:["garden","breakfast"],t:"Wooden house, vegetarian café, calm."}]},
{id:"puertovaras",name:"Puerto Varas & Chiloé",cc:"CL",lat:-41.32,lon:-72.98,kind:"lake",tags:["lakes","volcano","islands","culture"],days:3,dorm:17,
 tag:"German lake town under two volcanoes, gateway to Chiloé's stilt houses.",best:"Nov–Mar; Sep–Oct wet.",
 blurb:"Osorno volcano across the lake, Petrohué falls, kayaking. Two hours on to Chiloé island: palafito stilt houses in Castro, wooden churches, penguins at Puñihuil. The Andean lakes crossing to Bariloche starts here.",
 hi:["Osorno volcano and Petrohué falls","Castro palafitos (Chiloé)","Puñihuil penguins","Lakes crossing to Bariloche"],
 hostels:[{n:"Casa Margouya",v:"social",area:"Centre",price:"$$",f:["kitchen","bar"],t:"French-Chilean, social, colourful."},{n:"Palafito Hostel (Castro, Chiloé)",v:"boutique",area:"Castro",price:"$$$",f:["view","breakfast","quiet"],gem:true,t:"Sleep in a stilt house over the water."}]},
{id:"carretera",name:"Carretera Austral",cc:"CL",lat:-45.57,lon:-72.07,kind:"nature",major:true,tags:["road-trip","hiking","off-beat","rivers"],days:5,dorm:18,
 tag:"1,200 km of gravel through fjords, glaciers and the Marble Caves. Hitchhiking country.",best:"Dec–Mar; before that, ferries and buses are thin.",
 blurb:"Chile's wildest road, from Puerto Montt to Villa O'Higgins: Futaleufú rafting, Queulat hanging glacier, Coyhaique, the Marble Caves at Puerto Río Tranquilo, Cerro Castillo trek. Slow, sparse buses, mostly hitchhiking. Needs a week minimum.",
 hi:["Marble Caves at Puerto Río Tranquilo","Queulat hanging glacier","Futaleufú rafting","Cerro Castillo trek"],
 hostels:[{n:"Patagonia House (Coyhaique)",v:"chill",area:"Coyhaique",price:"$$",f:["garden","kitchen","quiet"],verify:true,t:"Cabins in a garden, the base for the middle section."},{n:"Hospedajes along the road",v:"chill",area:"Villages",price:"$$",f:["kitchen"],t:"Family guesthouses in every village; camping everywhere."}]},
{id:"torres",name:"Torres del Paine",cc:"CL",lat:-51.0,lon:-73.0,kind:"mountain",major:true,tags:["trekking","mountains","glaciers"],days:5,dorm:22,
 tag:"The W trek: granite towers, glaciers and wind. Base in Puerto Natales.",best:"Nov–Mar; Oct is possible but cold and shuttles are limited. Book refugios months ahead.",
 blurb:"Four to five days on the W (or eight on the O), sleeping in refugios or campsites that must be booked in advance. Puerto Natales is the base with the best hostels in Patagonia and gear rental. Torres at sunrise is the money shot.",
 hi:["Base of the Towers at sunrise","Grey glacier from the W","French valley","Puerto Natales gear talk at Erratic Rock"],
 hostels:[{n:"Erratic Rock (Puerto Natales)",v:"social",area:"Puerto Natales",price:"$$",f:["kitchen","tours","breakfast"],gem:true,t:"Daily free trek briefing at 3 pm, gear rental, the hikers' hub."},{n:"Yagan House",v:"chill",area:"Puerto Natales",price:"$$",f:["kitchen","garden","quiet"],verify:true,t:"Wooden house, warm, calm."},{n:"Refugios and campsites in the park",v:"eco",area:"Inside the park",price:"$$$",f:["dinner"],t:"Vertice and Las Torres refugios; book on their sites months ahead."}]},
// ---- Argentina ----
{id:"buenosaires",name:"Buenos Aires",cc:"AR",lat:-34.60,lon:-58.38,kind:"city",major:true,tags:["city","nightlife","food","tango"],days:4,dorm:16,
 tag:"Steak, tango, 4 am nightlife and the most beautiful city on the continent.",best:"Spring Sep–Nov; Dec hot and humid.",
 blurb:"Give it four days minimum: Palermo bars, San Telmo Sunday market, a Boca game at the Bombonera, milongas in old halls, parrillas that open at 10 pm. Currency: bring dollars, the blue rate matters. Flights to Patagonia and Iguazú from here.",
 hi:["San Telmo Sunday fair","La Boca and a Boca Juniors match","Milonga night (La Catedral)","Parrilla dinner at 10 pm","Recoleta cemetery","Tigre delta day"],
 hostels:[{n:"Milhouse Hostel",v:"party",area:"Centro / San Telmo",price:"$$",f:["bar","rooftop"],t:"The party institution; tango classes, asados, pub crawls."},{n:"América del Sur Hostel",v:"social",area:"San Telmo",price:"$$",f:["bar","kitchen","garden"],t:"Well-run, social, quieter than Milhouse."},{n:"Circus Hostel",v:"social",area:"San Telmo",price:"$$",f:["pool","bar"],t:"Small pool, bar, design-y."},{n:"Art Factory Hostel",v:"party",area:"San Telmo",price:"$",f:["bar","rooftop"],t:"Murals in every room, loud, cheap."}]},
{id:"mendoza",name:"Mendoza",cc:"AR",lat:-32.89,lon:-68.84,kind:"city",tags:["wine","mountains","food"],days:3,dorm:15,
 tag:"Malbec by bike, Aconcagua on the horizon.",best:"Sep–Nov spring; harvest festival is March.",
 blurb:"Between Santiago (7 h bus over the Andes) and Buenos Aires. Cycle the Maipú wineries, drive to Aconcagua park, rafting in the Mendoza river. Tree-lined city with the best steak-and-wine value in the country.",
 hi:["Maipú wineries by bike","Aconcagua viewpoint day trip","Plaza Independencia at night","Uco valley winery lunch"],
 hostels:[{n:"Hostel Lao",v:"social",area:"Centre",price:"$$",f:["pool","garden","bar"],t:"Pool, garden asados, social."},{n:"Mendoza Inn",v:"chill",area:"Centre",price:"$",f:["kitchen","garden"],verify:true,t:"Cheap, garden, quiet."}]},
{id:"salta",name:"Salta & Jujuy",cc:"AR",lat:-24.79,lon:-65.41,kind:"culture",major:true,tags:["mountains","culture","colonial","desert"],days:4,dorm:14,
 tag:"Colonial Salta, the 14-colour hill of Humahuaca, salt flats and cactus canyons.",best:"Sep–Nov dry and warm; Jan wet.",
 blurb:"Where the Atacama/Uyuni bus lands in Argentina. Salta's plaza and peñas (folk-music dinners), then north through the Quebrada de Humahuaca: Purmamarca, Tilcara, the Hornocal 14-colour hill, Salinas Grandes. Cafayate wineries to the south.",
 hi:["Hornocal 14-colour hill","Purmamarca and Salinas Grandes","Peña night in Salta","Cafayate torrontés wineries","Tren a las Nubes (if running)"],
 hostels:[{n:"Coloria Hostel (Salta)",v:"social",area:"Salta centre",price:"$",f:["bar","rooftop","kitchen"],t:"Rooftop, colourful, social."},{n:"Hostal La Casa de Tilcara",v:"chill",area:"Tilcara",price:"$",f:["garden","kitchen"],verify:true,t:"Adobe house in the quebrada village."}]},
{id:"bariloche",name:"Bariloche",cc:"AR",lat:-41.13,lon:-71.31,kind:"mountain",major:true,tags:["lakes","hiking","chocolate","mountains"],days:4,dorm:16,
 tag:"Lake district: Refugio Frey hike, Circuito Chico by bike, chocolate and craft beer.",best:"Nov–Mar for hiking; Oct still snowy up high.",
 blurb:"Alpine town on Nahuel Huapi lake. Refugio Frey day hike (or overnight), Circuito Chico cycling, Cerro Campanario chairlift, Patagonia's beer scene. El Bolsón, the hippie town, is two hours south.",
 hi:["Refugio Frey hike","Circuito Chico by bike","Cerro Campanario viewpoint","Craft beer on Mitre street","El Bolsón day trip"],
 hostels:[{n:"Periko's Youth Hostel",v:"social",area:"Centre",price:"$$",f:["kitchen","garden","view"],t:"Lake views, garden, well-run."},{n:"Hopa Home Hostel",v:"chill",area:"Centre",price:"$$",f:["kitchen","quiet"],verify:true,t:"Small, warm, calm."},{n:"Selina Bariloche",v:"social",area:"Centre",price:"$$",f:["bar","cowork"],t:"Bar, coworking."}]},
{id:"chalten",name:"El Chaltén",cc:"AR",lat:-49.33,lon:-72.89,kind:"mountain",major:true,tags:["trekking","mountains","glaciers"],days:4,dorm:18,
 tag:"Fitz Roy at sunrise, free trails from the village. Argentina's trekking capital.",best:"Nov–Mar; Oct is possible with wind and snow.",
 blurb:"No entry fees, no permits: Laguna de los Tres (Fitz Roy) and Laguna Torre are day hikes from the door. Three hours from El Calafate. Wind is the weather; be flexible with days.",
 hi:["Laguna de los Tres at sunrise","Laguna Torre","Loma del Pliegue Tumbado viewpoint","Beer at La Cervecería after"],
 hostels:[{n:"Rancho Grande Hostel",v:"social",area:"Village",price:"$$",f:["kitchen","bar","breakfast"],t:"Big, social, bus terminal next door."},{n:"Aylen-Aike Hostel",v:"chill",area:"Village",price:"$$",f:["kitchen","quiet"],verify:true,t:"Small wooden house, calm."}]},
{id:"calafate",name:"El Calafate",cc:"AR",lat:-50.34,lon:-72.26,kind:"nature",major:true,tags:["glaciers","nature"],days:2,dorm:16,
 tag:"Perito Moreno glacier: ice the size of a city collapsing into the lake.",best:"Oct–Apr.",
 blurb:"The glacier is the reason: walkways in front of the 60 m wall, ice trekking on it if you pay. Flights from Buenos Aires and Ushuaia; buses to El Chaltén and Puerto Natales.",
 hi:["Perito Moreno walkways (whole day)","Minitrekking on the ice","Laguna Nimez birds at sunset"],
 hostels:[{n:"América del Sur Hostel",v:"social",area:"Hill above town",price:"$$",f:["view","bar","dinner"],t:"Lake views, asado nights, sister of the BA one."},{n:"Che Lagarto El Calafate",v:"social",area:"Centre",price:"$$",f:["bar","kitchen"],t:"Chain, central."}]},
{id:"ushuaia",name:"Ushuaia",cc:"AR",lat:-54.80,lon:-68.30,kind:"city",major:true,tags:["end-of-world","hiking","penguins"],days:3,dorm:18,
 tag:"End of the world: Beagle Channel penguins, Tierra del Fuego park, last-minute Antarctica deals.",best:"Nov–Mar; Oct cold and quiet.",
 blurb:"Southernmost city, flights from Buenos Aires and El Calafate. Beagle Channel boat to the penguin colony, Laguna Esmeralda hike, Tierra del Fuego park by the End of the World train. Last-minute Antarctica cruises from ~$5,000 if you have the time.",
 hi:["Beagle Channel boat to Martillo island penguins","Laguna Esmeralda hike","Tierra del Fuego national park","King crab dinner"],
 hostels:[{n:"Antarctica Hostel",v:"social",area:"Centre",price:"$$",f:["kitchen","bar"],t:"Warm, social, the classic."},{n:"Los Cormoranes Hostel",v:"chill",area:"Hill above port",price:"$$",f:["view","kitchen"],t:"Views over the channel, quiet."}]},
{id:"madryn",name:"Puerto Madryn (Valdés)",cc:"AR",lat:-42.77,lon:-65.04,kind:"nature",major:true,tags:["whales","wildlife","coast"],days:3,dorm:15,
 tag:"Southern right whales next to the pier, Sep–Nov. Penguins, orcas, elephant seals on Valdés.",best:"Sep–Nov whale season, exactly your window.",
 blurb:"Between Buenos Aires and Patagonia on the coast. In your months the whales are 50 m off the beach at Playa El Doradillo; Península Valdés day trip for elephant seals and Magellanic penguins; Punta Tombo has half a million penguins.",
 hi:["Whales from the beach at El Doradillo","Península Valdés day trip","Punta Tombo penguins","Snorkel with sea lions"],
 hostels:[{n:"La Tosca Hostel",v:"social",area:"Centre",price:"$$",f:["kitchen","garden","breakfast"],t:"Garden, bikes, the backpacker choice."},{n:"Chepatagonia Hostel",v:"chill",area:"Centre",price:"$$",f:["kitchen","quiet"],verify:true,t:"Quiet, near the beach."}]},
// ---- Paraguay ----
{id:"asuncion",name:"Asunción",cc:"PY",lat:-25.28,lon:-57.64,kind:"city",tags:["city","off-beat","culture"],days:2,dorm:12,
 tag:"The capital nobody visits. Tereré, river sunsets, cheapest country on the continent.",best:"Sep–Nov warm; Dec–Jan very hot.",
 blurb:"Between Iguazú/Encarnación and Bolivia or Buenos Aires. Faded grand buildings, the Costanera at sunset, Mercado 4, a friendly and cheap city where you will be the only tourist in the hostel.",
 hi:["Costanera and Palacio de López at sunset","Mercado 4","Tereré with locals in a plaza","Day trip to Areguá lake town"],
 hostels:[{n:"El Viajero Asunción",v:"social",area:"Centre",price:"$",f:["pool","bar","kitchen"],t:"Pool, bar, the only real backpacker hostel."},{n:"Nómada Hostel",v:"chill",area:"Centre",price:"$",f:["kitchen","garden"],verify:true,t:"Garden, calm, cheap."}]},
{id:"encarnacion",name:"Encarnación & Jesuit missions",cc:"PY",lat:-27.33,lon:-55.87,kind:"culture",tags:["ruins","history","river","off-beat"],days:2,dorm:12,
 tag:"UNESCO Jesuit ruins of Trinidad, a river beach town, bridge to Argentina.",best:"Sep–Nov; Encarnación beach opens in summer.",
 blurb:"Paraguay's most relaxed town, on the Paraná opposite Posadas (Argentina). Trinidad and Jesús de Tavarangue Jesuit ruins are 30 minutes away and empty. A half-way stop between Iguazú and Buenos Aires without flying.",
 hi:["Trinidad Jesuit ruins (light show at night)","Jesús de Tavarangue","San José beach on the Paraná","Cross to Posadas"],
 hostels:[{n:"Casa de la Y Hostel",v:"chill",area:"Centre",price:"$",f:["kitchen","garden"],verify:true,t:"Small, friendly, garden."}]},
];
const TIER1_SOUTH=["atacama","torres","buenosaires","chalten","bariloche"];
const COUNTRIES_SOUTH={
 CL:{img:"torres",currency:"Chilean peso (CLP), ~1,000 per €",cash:"Cards everywhere; ATMs charge ~$8 per withdrawal (Scotiabank/BancoEstado cheapest).",budget:"$50–70 / day; Patagonia and Atacama more",visa:"Visa-free, 90 days.",safety:"Very safe outside Santiago's centre at night. Earthquakes and wind are the hazards.",
   must:["San Pedro de Atacama","Torres del Paine W trek","Valparaíso hills","Pucón volcano"],note:"Chile is the expensive one: budget like Europe. Long-distance buses (Turbus, Pullman) are excellent."},
 AR:{img:"chalten",currency:"Argentine peso (ARS); bring US dollars",cash:"Bring crisp US$100 bills and change at cuevas / Western Union for the parallel rate; cards charge the official rate. Inflation makes prices unreliable.",budget:"$35–55 / day depending on the exchange rate",visa:"Visa-free, 90 days.",safety:"Buenos Aires: phone snatching, fake taxis; use the app taxis. Patagonia is safe.",
   must:["Buenos Aires for a week","El Chaltén and Perito Moreno","Bariloche lakes","Salta and Humahuaca"],note:"Aerolíneas domestic flights are cheap if booked as a resident fare through an agency; Patagonia distances are huge."},
 PY:{img:"asuncion",currency:"Guaraní (PYG), ~8,000 per €",cash:"Cash country; ATMs fine in cities. Cheapest prices on the continent.",budget:"$25–35 / day",visa:"Visa-free, 90 days.",safety:"Relaxed; Ciudad del Este is the only edgy spot. Heat in Dec–Jan.",
   must:["Jesuit missions at Trinidad","Asunción costanera at sunset","Tereré culture"],note:"Only worth it as the overland link between Iguazú and Buenos Aires, or for the Chaco if you have time."},
};
const CLIM_SOUTH={
 santiago:{hi:[19,23,26,29,30],lo:[6,9,11,13,14],rain:[20,10,5,3,1],n:"Dry spring, hot Dec–Jan."},
 valparaiso:{hi:[17,18,20,21,22],lo:[9,10,11,12,13],rain:[15,10,5,2,1],n:"Mild, foggy mornings, sea 15 °C."},
 atacama:{hi:[22,24,26,27,27],lo:[0,3,5,7,8],rain:[0,0,0,1,5],n:"Bone dry; nights freeze; Jan afternoon storms possible (altiplano winter)."},
 pucon:{hi:[14,17,19,22,24],lo:[4,6,8,10,11],rain:[150,110,80,60,50],n:"Wet spring, dry summer from Dec."},
 puertovaras:{hi:[14,16,18,20,21],lo:[5,7,8,10,11],rain:[170,150,110,100,80],n:"Rainy all year; Dec–Jan the driest."},
 carretera:{hi:[11,14,16,18,19],lo:[2,4,6,8,9],rain:[90,80,70,60,60],n:"Cool, showers, wind. Dec–Mar season."},
 torres:{hi:[10,13,15,17,18],lo:[2,4,6,7,8],rain:[40,50,50,60,70],n:"Wind is the weather; 4 seasons a day. Oct cold and closed refugios possible."},
 buenosaires:{hi:[19,22,25,28,30],lo:[10,13,16,19,21],rain:[70,110,110,100,120],n:"Spring; Dec–Jan hot and humid with storms."},
 mendoza:{hi:[21,25,28,31,32],lo:[7,11,14,17,19],rain:[10,15,20,25,30],n:"Dry and sunny; hot from Nov."},
 salta:{hi:[24,26,27,27,27],lo:[9,13,15,16,17],rain:[5,20,50,90,150],n:"Dry Sep–Nov; summer rains from Dec, Humahuaca stays drier."},
 bariloche:{hi:[12,15,18,21,23],lo:[2,4,6,8,9],rain:[60,50,40,30,25],n:"Spring snowmelt; Dec–Jan is the hiking window."},
 chalten:{hi:[10,13,15,17,18],lo:[1,3,5,7,8],rain:[20,25,25,30,35],n:"Wind and fast changes; Nov–Mar."},
 calafate:{hi:[11,14,17,19,20],lo:[1,3,5,7,8],rain:[10,15,15,15,20],n:"Dry, windy, cold nights."},
 ushuaia:{hi:[8,11,13,15,16],lo:[1,3,4,6,6],rain:[45,45,50,55,55],n:"Cold; Dec–Jan mildest; 17 h of daylight in Dec."},
 madryn:{hi:[17,21,24,27,29],lo:[7,10,13,15,17],rain:[15,20,15,15,15],n:"Dry, windy; whales Sep–Nov."},
 asuncion:{hi:[26,29,31,32,33],lo:[15,18,20,22,23],rain:[90,130,150,140,130],n:"Hot; Dec–Jan sweltering."},
 encarnacion:{hi:[24,27,29,31,32],lo:[13,16,18,20,21],rain:[130,170,160,150,150],n:"Humid, storms in summer."},
};
const LEGS_SOUTH={
 "santiago>valparaiso":{m:"bus",h:1.7,u:6,d:0,n:"Turbus / Pullman every 15 min from Pajaritos."},
 "valparaiso>santiago":{m:"bus",h:1.7,u:6,d:0,n:""},
 "santiago>atacama":{m:"flight",h:2,u:70,d:0,n:"Fly to Calama (LATAM/Sky), 1.5 h shuttle to San Pedro. Bus is 23 h."},
 "atacama>santiago":{m:"flight",h:2,u:70,d:0,n:"Shuttle to Calama, fly."},
 "uyuni>atacama":{m:"4x4",h:72,u:180,d:3,n:"The classic 3-day jeep tour ends at the Chilean border; transfer to San Pedro included."},
 "atacama>uyuni":{m:"4x4",h:72,u:180,d:3,n:"3-day jeep tour from San Pedro ending in Uyuni."},
 "atacama>salta":{m:"bus",h:10,u:45,d:0,n:"Pullman / Andesmar via the Paso de Jama, stunning, book ahead."},
 "salta>atacama":{m:"bus",h:10,u:45,d:0,n:""},
 "salta>buenosaires":{m:"flight",h:2.5,u:90,d:0,n:"Aerolíneas / Flybondi; bus is 20 h ($60)."},
 "salta>mendoza":{m:"bus",h:18,u:60,d:0,n:"Night bus via Tucumán."},
 "santiago>mendoza":{m:"bus",h:7,u:35,d:0,n:"Over the Andes via Los Libertadores pass; can close in snow."},
 "mendoza>santiago":{m:"bus",h:7,u:35,d:0,n:""},
 "mendoza>buenosaires":{m:"bus",h:14,u:50,d:0,n:"Night bus, cama class; or fly 1.5 h ~$70."},
 "buenosaires>iguazu":{m:"flight",h:2,u:80,d:0,n:"Or 18 h bus ($70)."},
 "iguazu>buenosaires":{m:"flight",h:2,u:80,d:0,n:""},
 "buenosaires>bariloche":{m:"flight",h:2.5,u:90,d:0,n:"Or 22 h bus."},
 "bariloche>buenosaires":{m:"flight",h:2.5,u:90,d:0,n:""},
 "buenosaires>madryn":{m:"bus",h:19,u:70,d:0,n:"Night bus; or fly to Trelew 2 h ~$80."},
 "madryn>bariloche":{m:"bus",h:14,u:60,d:0,n:"Via Esquel, night bus."},
 "madryn>calafate":{m:"flight",h:2,u:120,d:0,n:"From Trelew; bus is 26 h."},
 "bariloche>chalten":{m:"bus",h:28,u:110,d:1,n:"Ruta 40 two-day bus (Chaltén Travel), or fly BRC → FTE and bus."},
 "bariloche>puertovaras":{m:"bus",h:7,u:35,d:0,n:"Bus via Osorno; the lakes crossing is a full day ~$300."},
 "puertovaras>bariloche":{m:"bus",h:7,u:35,d:0,n:""},
 "pucon>puertovaras":{m:"bus",h:5,u:15,d:0,n:""},
 "santiago>pucon":{m:"bus",h:10,u:30,d:0,n:"Night bus."},
 "pucon>bariloche":{m:"bus",h:8,u:40,d:0,n:"Via the Mamuil Malal pass."},
 "puertovaras>carretera":{m:"bus",h:6,u:30,d:0,n:"Bus + ferry to Chaitén, or ferry from Puerto Montt."},
 "carretera>chalten":{m:"bus",h:12,u:50,d:1,n:"Coyhaique → Chile Chico → Los Antiguos → Ruta 40; slow."},
 "chalten>calafate":{m:"bus",h:3,u:25,d:0,n:"Several daily."},
 "calafate>chalten":{m:"bus",h:3,u:25,d:0,n:""},
 "calafate>torres":{m:"bus",h:5,u:30,d:0,n:"To Puerto Natales, border included."},
 "torres>calafate":{m:"bus",h:5,u:30,d:0,n:""},
 "torres>ushuaia":{m:"bus",h:12,u:60,d:0,n:"Via Punta Arenas and the ferry; or fly from Punta Arenas."},
 "calafate>ushuaia":{m:"flight",h:1.5,u:90,d:0,n:"Or 17 h bus."},
 "ushuaia>buenosaires":{m:"flight",h:3.5,u:120,d:0,n:""},
 "calafate>buenosaires":{m:"flight",h:3,u:110,d:0,n:""},
 "buenosaires>rio":{m:"flight",h:3,u:150,d:0,n:"Direct, several daily."},
 "buenosaires>floripa":{m:"flight",h:2,u:120,d:0,n:"Or 24 h bus."},
 "buenosaires>asuncion":{m:"bus",h:18,u:50,d:0,n:"Night bus; or fly 2 h ~$120."},
 "asuncion>iguazu":{m:"bus",h:6,u:20,d:0,n:"To Ciudad del Este, cross to Foz."},
 "iguazu>asuncion":{m:"bus",h:6,u:20,d:0,n:""},
 "asuncion>encarnacion":{m:"bus",h:5,u:12,d:0,n:""},
 "encarnacion>buenosaires":{m:"bus",h:14,u:45,d:0,n:"Cross to Posadas, night bus."},
 "iguazu>encarnacion":{m:"bus",h:6,u:20,d:0,n:"Via Posadas."},
 "asuncion>samaipata":{m:"bus",h:24,u:60,d:1,n:"Trans-Chaco bus to Santa Cruz, rough; then 3 h."},
 "uyuni>salta":{m:"bus",h:14,u:40,d:0,n:"Via Villazón / La Quiaca border, buses to Salta."},
 "samaipata>asuncion":{m:"bus",h:24,u:60,d:1,n:"Santa Cruz → Asunción across the Chaco."},
 "santiago>rio":{m:"flight",h:4,u:200,d:0,n:""},
 "santiago>buenosaires":{m:"flight",h:2,u:100,d:0,n:""},
 "lima>santiago":{m:"flight",h:3.5,u:150,d:0,n:""},
 "cusco>santiago":{m:"flight",h:6,u:220,d:0,n:"Via Lima."},
 "lapaz>atacama":{m:"bus",h:14,u:45,d:0,n:"Via Uyuni or Calama."},
 "lapaz>santiago":{m:"flight",h:3,u:180,d:0,n:""},
};
const PRESETS_SOUTH=[
 {name:"Andes South",tagline:"Peru, then Bolivia's salt flats into the Atacama, Salta, Buenos Aires and Iguazú, up the coast to Rio. No Colombia.",
  stops:[["lima",2],["mancora",7],["huaraz",6],["lima",1],["huacachina",3],["arequipa",5],["cusco",7],["machu",3],["titicaca",3],["lapaz",5],["uyuni",4],["atacama",6],["salta",6],["buenosaires",9],["madryn",5],["bariloche",6],["buenosaires",2],["iguazu",3],["floripa",6],["ilhagrande",6],["paraty",4]]},
];
